### ISSUE TITLE
How to access the title bar

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#10]
How do I access properties of the title bar? specifically I would like to do something like this:
https://github.com/binaryfunt/electron-seamless-titlebar-tutorial

**Comment by rjaros** [comment]
Are you creating an Electron application and trying to follow this tutorial to make custom title bar?

**Comment by robert-cronin** [comment]
Yes that is correct, I hope I'm on the right track!

**Comment by rjaros** [comment]
From what I can see in the docs, it's not possible to change the electron window to frameless after it is created. So you can not do this from KVision app, which runs in the renderer process (in an already created window). 

But it is very easy to do this from the main process, it just requires some changes in JavaScript code in `src/main/electron/index.js` file. Just like in the tutorial, you can change:

```const window = new BrowserWindow()```

to

```const window = new BrowserWindow({frame: false})```

and the window will have no frame and no title bar. You can get the reference to the main window from KVision code with this:
```
val remote: Remote = require("electron").remote
val mainWindow = remote.getCurrentWindow()
```
and just follow the rest of the tutorial to generate and manage custom title bar.

**Comment by robert-cronin** [comment]
Thank you rjaros, much appreciated, I will give it a try

**Comment by robert-cronin** [comment]
Just an update for anyone looking to do this in future, Node has a [package](https://www.npmjs.com/package/custom-electron-titlebar) especially for custom electron titlebars. Everything is defined in main.js but it seems like it makes it a lot easier than messing around with multiple files.
