### ISSUE TITLE
Possbility to extract headers from rest client response

### ISSUE THREAD

**Issue by g3blv** [rjaros/kvision#100]
I would be great if it was possible to extract the headers from the response when making a request with the rest client.

**Comment by rjaros** [comment]
I've created a new set of methods in `RestClient` class - `remoteRequest` and `request`. They are doing exactly the same thing as current `remoteCall` and `call` methods, but they are returning:
```
data class Response<T>(val data: T, val textStatus: String, val jqXHR: JQueryXHR)
```
You can use `jqXHR.getResponseHeader("...")` or `jqXHR.getAllResponseHeaders()` to get what you need. It will be soon available in 2.1.0 release.
