### ISSUE TITLE
Links in DropDowns

### ISSUE THREAD

**Issue by joerg-rade** [rjaros/kvision#102]
```
    fun buildMenuAction(action: String, iconName: String? = null): Link {
        val label = tr(action)
        val icon = iconName ?: IconManager.find(action)
        return Link(label, icon = icon)
    }
```

with kvision < 2 it rendered as 
![krovizSystemMenu1](https://user-images.githubusercontent.com/4637858/68140000-64b87e80-ff2b-11e9-8cf5-51bbd3df343e.png)

with 2.0.0  it looks like
![krovizSystemMenu2x](https://user-images.githubusercontent.com/4637858/68140080-7d289900-ff2b-11e9-86be-997ff1e188f6.png)

What should I do to \<br/\> after each item?

**Comment by rjaros** [comment]
Try adding `dropdown-item` class to the `Link`:
```
return Link(label, icon = icon, classes = setOf("dropdown-item"))
```

**Comment by joerg-rade** [comment]
Menu items still not on separate lines. 

Can I have icons with
```
dropDown(
                        tr("Favourites"),
                        listOf(tr("HTML") to "#!/basic", tr("Forms") to "#!/forms"),
                        icon = "fas fa-star",
                        forNavbar = true
                    )
```
?

**Comment by rjaros** [comment]
Not directly with `elements` parameter. But you can easily add links with icons manually using `ddLink` extension function.
```
                    dropDown(
                        tr("Favourites"),
                        icon = "fas fa-star",
                        forNavbar = true
                    ) {
                        ddLink("HTML", "#!/basic", "fas fa-file")
                        ddLink("Forms", "#!/forms", "fab fa-form")
                    }

```

**Comment by rjaros** [comment]
Only the menu? 
Are you sure you have included bootstrap-css module?

**Comment by joerg-rade** [comment]
https://github.com/joerg-rade/kroviz/blob/kvision2/build.gradle l:53 reads
```
compile "pl.treksoft:kvision-bootstrap-css:${kvisionVersion}"`
```

**Comment by rjaros** [comment]
I've cloned and build you app from `kvision2` branch, and the main menu looks ok to me:
![menu](https://user-images.githubusercontent.com/5646804/68227297-b9bfc780-fff3-11e9-9b25-a5cc712f66ed.png)

**Comment by joerg-rade** [comment]
Yep - gradlew.bat clean helped!
I appreciate your help.
