### ISSUE TITLE
REST Service

### ISSUE THREAD

**Issue by csab3266** [rjaros/kvision#106]
Trying to use the openweathermap api with kvision. Doesn't work for me. 

val result = restClient.call<SerchResult, Query>("https://api.openweathermap.org/data/2.5/weather", Query("Innsbruck","...key...."))

I get an error "405 Method Not Allowed"

Don't know if I make an error or if its is a error in kvision.

BTW Thanks for kvision

**Comment by rjaros** [comment]
The 405 error is because of CORS (the browser calls the API endpoint with OPTIONS method first). You can use universal cors proxy from cors-anywhere. The following code works fine for me:
```
@Serializable
data class Main(val temp: Double, val temp_min: Double, val temp_max: Double)

@Serializable
data class Result(val name: String, val id: Int, val main: Main)

@Serializable
data class Query(val q: String, val APPID: String)

class App : Application() {
    override fun start() {
            val restClient = RestClient()
            val result = restClient.call<Result, Query>("https://cors-anywhere.herokuapp.com/https://api.openweathermap.org/data/2.5/weather", Query("Innsbruck","API_KEY"))
            result.then {
                println(it)
            }
    }
}
```

**Comment by csab3266** [comment]
Works fine with your solution!
Thanks a lot!
