### ISSUE TITLE
How can i use other nodejs libraries.

### ISSUE THREAD

**Issue by ziakhan110** [rjaros/kvision#108]
i am planing to build a large web app using kvision. i will need to use some nodejs packages.
i need to access sqlite on browser to store data for offline usage.
how will i do it using kvision.

**Comment by robert-cronin** [comment]
right now you have to use Kotlin's inbuilt [JS Module](https://kotlinlang.org/docs/reference/js-modules.html) functionality, once you have a module built you can call it directly from Kotlin alongside KVision

**Comment by rjaros** [comment]
KVision apps work in browser. You can only use js/nodejs libraries which are supported in the browser environment. If you want sqlite, you won't be able to use this: https://www.npmjs.com/package/sqlite3, but you can try to use this one: https://www.npmjs.com/package/sql.js

**Comment by robert-cronin** [comment]
There are templates you can follow already within KVision (https://github.com/rjaros/kvision/tree/master/kvision-modules)
I think the `Moment` or `Pace` modules are relatively simple, I only have experience with these two but you might be able to start there.

**Comment by ziakhan110** [comment]
> There are templates you can follow already within KVision (https://github.com/rjaros/kvision/tree/master/kvision-modules)
> I think the `Moment` or `Pace` modules are relatively simple, I only have experience with these two but you might be able to start there.

i am going to start writing module for sql.js . i am going to use generics for data retrieving function. what do you think. also i am going to use json convesion library like gson.

**Comment by rjaros** [comment]
Remember you do not have to write a module to use a library. You can just add a dependency in your `build.gradle.kts` file and use it in your project. But of course if you want to contribute a module for KVision, it would be great :-)
