### ISSUE TITLE
DateTime - How to set only for time or date

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#109]
How do I make the DateTime picker set only for time, in JavaScript I can do the following:
```
<div class='input-group date' id='datetimepicker3'>
    <input type='text' class="form-control" />
    <span class="input-group-addon">
        <span class="glyphicon glyphicon-time"></span>
    </span>
</div>
```
But I can't seem to set the class of the DateTime component

**Comment by rjaros** [comment]
Just use the `HH:mm` format:
https://kvision.gitbook.io/kvision-guide/part-2-advanced-features/form-controls-guide#p-t-k-f-time-datetime

**Comment by robert-cronin** [comment]
ok that worked, my mistake was using the capitalised minute form: "HH:MM". Thanks Robert 👍
