### ISSUE TITLE
Dependencies issues with version 2.4.0

### ISSUE THREAD

**Issue by samirsayegh** [rjaros/kvision#112]
When I'm updating the version of kvision to the new version 2.4.0, the other dependencies that we are using like:
- kvision-datetime
- kvision-dialog
- kvision-select
Are giving us error with a 404 when retrieving "https://registry.npmjs.org/kotlinx-serialization-kotlinx-serialization-runtime" 

[error_log.txt](https://github.com/rjaros/kvision/files/3896211/error_log.txt)

**Comment by rjaros** [comment]
Module names have changed in KVision 2.x. It should be `kvision-bootstrap-datetime` and so on.
Look at the migration guide: https://kvision.gitbook.io/kvision-guide/part-1-fundamentals/migration

**Comment by samirsayegh** [comment]
Now I see that there was a migration guide that I didn't pay attention.
Thank you!
