### ISSUE TITLE
Cannot read property 'sel' of null

### ISSUE THREAD

**Issue by joerg-rade** [rjaros/kvision#113]
After migrating to 2.x, my karma tests do not work anymore, cf. 
https://github.com/joerg-rade/kroviz/compare/52ad2965585d%5E...83778a77d673

karma.log shows:
```
28 11 2019 17:32:45.924:INFO [Chrome 78.0.3904 (Windows 10.0.0)]: Connected on socket SiDpIThDRgwz0B8vAAAB with id manual-1931
PhantomJS 2.1.1 (Windows 8.0.0) ERROR
  TypeError: null is not an object (evaluating 'vnode.sel')
  at undefined:22

Chrome 78.0.3904 (Windows 10.0.0) ERROR
  Uncaught TypeError: Cannot read property 'sel' of null
  at webpack:///../node_modules/snabbdom/es/snabbdom.js?:22
```

https://github.com/snabbdom/snabbdom-to-html/issues/14 suggets that there might be a place where a number is passed but a string expected. When I set a breakpoint  I see in 

```
  KVManager.prototype.patch_cdbjll$ = function (id, vnode) {
    var container = document.getElementById(id);
    container != null ? (clear(container), Unit) : null;
    return this.sdPatch_0(container, vnode);
  };
```
```
Local
container: null
id: "kroviz"
this: KVManager
vnode:
children: [{…}]
data: {key: "kv_widget_0", attrs: {…}, style: {…}, class: {…}, on: null, …}
elm: undefined
key: "kv_widget_0"
sel: "div#null"
text: undefined
__proto__:
```

Anything ovious I do wrong?

**Comment by rjaros** [comment]
It's not your fault. It's an issue in KVision, I was aware of during development of 2.x, but I've completely forgot about it :-/
I'll try to fix this in the next release. As a workaround for now add one line at the beginning of your `main()` function in `App.kt`:
```
fun main() {
    if (window.asDynamic().__karma__) return
    startApplication(::App)
}
```

**Comment by joerg-rade** [comment]
Thanks for the workaround!

**Comment by rjaros** [comment]
BTW: your project builds **a lot of** faster for me, if I remove `maven { url = "http://bintray.com/" }` from `repositories` sections in `build.gradle`.

**Comment by joerg-rade** [comment]
Oh yes, here it cuts down by 50%!

**Comment by joerg-rade** [comment]
.. and removing the second occurrence as well cuts down by another 75% 
All in all factor 6 !
