### ISSUE TITLE
Using button.focus() / onEvent{}

### ISSUE THREAD

**Issue by joerg-rade** [rjaros/kvision#114]
Is there an example how to use the features introduced with 2.4.0?

My expectation is, that pressing Enter would execute the action associated with OK.
I assume that I should use onEvent instead of onClick. How? 
```    
    private val okButton = Button(caption, "fas fa-check", ButtonStyle.SUCCESS).onClick {
        execute()
    }

// second button omitted

    var panel: FormPanel<String>?
    init {
        init?.invoke(this)
        icon = IconManager.find(caption)
        isDraggable = true
        isResizable = true
        closeButton = true
        verticalAlign = VerticalAlign.MIDDLE
        panel = formPanel {
        // code omitted 
        }
        val buttonBar = HPanel(spacing = 10) {
            margin = 10.px
        }
        buttonBar.add(okButton)
        buttonBar.add(cancelButton)
        add(buttonBar)
        okButton.focus()
    }
```
Full code at: https://github.com/joerg-rade/kroviz/blob/kvision2/src/main/kotlin/org/ro/ui/kv/RoDialog.kt

**Comment by rjaros** [comment]
`onClick` is just a helper method to bind `click` event, so it just the same as using:
```
onEvent {
    click = {
    }
}
```
Using `onClick` is still the correct way in 2.4, so there is no need to change anything.

Introducing `onEvent` method in 2.4 is not related to any internal change in KVision - it's just a shorter way to write the same code when it comes to type detection - there is no need to write explicit type parameters.

**Comment by rjaros** [comment]
The new `focus()` method it's just a shortcut to call `getElementJQuery()?.focus()`. So it must be called when the button is already rendered. One of the use cases is focusing a default button after a Modal window appears. It can be done with an `shownBsModal` event:
```
object MyWindow : Modal("My Window") {
    init {
        val okButton = Button("OK", "fas fa-check").onClick {
            this@MyWindow.hide()
        }
        addButton(okButton)
        onEvent {
            shownBsModal = {
                okButton.focus()
            }
        }
    }
    fun open() {
        this.show()
    }
}
```

**Comment by joerg-rade** [comment]
Thanks again!

**Comment by joerg-rade** [comment]
Unfortunately shownBsModal  doesn't work for me. Probably due to the fact that RoDialog inherits from Window (I want my 'modals' to be resizeable and moveable).
I skimmed through https://getbootstrap.com/docs/4.0/components/ and https://www.w3schools.com/jsref/dom_obj_event.asp but didn't find anything that rang a bell in my had (yet).

Suggestions?

**Comment by rjaros** [comment]
I think it would be easier with `Window`, because unlike with modals, you have explicit control over `Window` lifecycle. So imho it should be enough to call `okButton.focus()` after `super.show()` in this `show` method https://github.com/joerg-rade/kroviz/blob/946927bd368d971351702209f0770212a3681421/src/main/kotlin/org/ro/ui/kv/RoDialog.kt#L85

**Comment by joerg-rade** [comment]
That was it. (Looks like I should further my understanding of the UI lifecycles ;-)
