### ISSUE TITLE
Tabulator: Menu pops up off screen

### ISSUE THREAD

**Issue by joerg-rade** [rjaros/kvision#115]
Records in my tables have an icon on the right hand side  (3 vertical dots) that open up a ContextMenu.
When there are few elements in the table, the menu pops up at the expected location.
When the list is long (exceeds the visible page length and the scrollbar is shown), the menu pops up far too way south.

Same behaviour < v2.x

Am I doing something wrong?
Is there a way to force pageX/pageY?

```
    private fun buildContextMenu(mouseEvent: MouseEvent, cell: Tabulator.CellComponent): ContextMenu {
        console.log("[ColumnFactory.buildContextMenu]")
        console.log(mouseEvent)
        val exposer = getData(cell)
        val tObject = exposer.delegate
        val menu = MenuFactory.buildFor(tObject)
        //FIXME x/y coordinates are sometimes off screen
        val mei = MouseEventInit(
                clientX = (mouseEvent.clientX - 250),
                clientY = (mouseEvent.clientY - 500),
                screenY = (mouseEvent.clientY - 500),
                screenX = (mouseEvent.screenX))
        val positionedEvent = MouseEvent("", mei)
        menu.positionMenu(positionedEvent)
        console.log(positionedEvent)
        return menu
    }
```
![contextMenu_off_screen](https://user-images.githubusercontent.com/4637858/70340061-5aeaa980-1850-11ea-98f6-185e7a284791.png)

**Comment by rjaros** [comment]
I'm not sure how to help without a working example. But perhaps you could take the coordinates from the cell element instead of the mouse event.

**Comment by joerg-rade** [comment]
The required serverpart can be installed via:
```bash
mvn archetype:generate \
    -D archetypeGroupId=org.apache.isis.archetype \
    -D archetypeArtifactId=simpleapp-archetype \
    -D archetypeVersion=1.16.0 \
    -D groupId=org.my \ 
    -D artifactId=myapp-1.16.0 \ 
    -D version=1.0.0 -B
```
cd into ./wepapp and execute
```
mvn jetty:run -Djetty.port=8080
```
The server should now be available - check http://localhost:8080/

To open the tab:
-> Burger -> Connect
-> Configuration -> configuration

**Comment by rjaros** [comment]
This server application fails to build for me. The error message is strange and I don't have any idea how to fix this:
```
[ERROR] Failed to execute goal org.datanucleus:datanucleus-maven-plugin:4.0.5:enhance 
(process-classes) on project myapp-1.16.0-module-simple: Error executing DataNucleus tool
 org.datanucleus.enhancer.DataNucleusEnhancer: InvocationTargetException: Plugin (Bundle) 
"org.datanucleus.api.jdo" is already registered. Ensure you dont have multiple JAR versions of the
 same plugin in the classpath. The URL "file:/home/rjaros/.m2/repository/org/datanucleus/datanucleus-api-jdo/4.1.1/datanucleus-api-jdo-
4.1.1.jar" is already registered, and you are trying to register an identical plugin located at URL
 "file:/opt/rjaros/.m2/repository/org/datanucleus/datanucleus-api-jdo/4.1.1/datanucleus-api-jdo
-4.1.1.jar." -> [Help 1]
```
On my machine `/home/rjaros/.m2` is the same dir as `/opt/rjaros/.m2` (a symlink).
BTW: this reminded me why do I hate Maven ;-)

**Comment by joerg-rade** [comment]
IIRC I hit a similar problem and resolved it by adding the following at the top of my .m2/settings.xml:

```
	<!-- define where local repository to be stored -->
	<localRepository>C:/data/.m2_repo/</localRepository>
```
And yes: often I think Maven is not the solution but part of the problem ;-)

**Comment by joerg-rade** [comment]
As a workaround I use DropDown

**Comment by rjaros** [comment]
So I'm closing this issue. If anyone has this problem, please reopen.
