### ISSUE TITLE
Date input height is not modifiable

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#116]
If I set the height in a DateTimeInput, the button will expand to the specified height but the text input field will not:
![image](https://user-images.githubusercontent.com/8540764/70401590-5221ef80-1a6b-11ea-854e-188733b5ee39.png)
I am unable to affect the height of the input field.

**Comment by rjaros** [comment]
It should be possible to fix this by overriding height property. I'll think about this for the next release.
As a workaround for now you can just use some simple css styling:

```
val style = Style {
    height = 50.px
    style("input") {
        height = 50.px
    }
}
// ...
            dateTimeInput {
                addCssStyle(style)
            }
// or
            dateTime(label = "A label") {
                input.addCssStyle(style)
            }
```

**Comment by robert-cronin** [comment]
I get the following error when trying to addCssStyle to input:
`Cannot access 'input': it is internal in 'DateTimeInput'`

**Comment by robert-cronin** [comment]
Yes, that worked, thanks Robert!
