### ISSUE TITLE
How about webassembly?

### ISSUE THREAD

**Issue by atonamy** [rjaros/kvision#120]
How to configure kvision to compile into webassembly?
For example in [Blazor](https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor) is just working out of the box. But kvision didn't mention anything about it which is outmoded.

**Comment by rjaros** [comment]
KVision is a Kotlin/JS framework and you can't compile KVision app to webassembly. At least for now. There are some ideas, which may be implemented in the future.

**Comment by rjaros** [comment]
Of course, I welcome any contributions :-)
