### ISSUE TITLE
What about implement Material Design look and feel?

### ISSUE THREAD

**Issue by LucasAlfare** [rjaros/kvision#121]
Bootstrap styles are very cool but is possible in future some updates bringing Material Design to this project? It might be very cool. Thanks in advance!

**Comment by rjaros** [comment]
Material Design support is on my long TODO list. But I'm unable to say when it will be done. In the meantime you can use Materia theme from Bootswatch https://kvision.gitbook.io/kvision-guide/part-1-fundamentals/themes#using-free-themes-from-bootswatch

**Comment by rjaros** [comment]
This is surely not the full implementation, but Onsen UI library supports large part of the Material Design look and feel. If someone wants to create mobile applications this is probably a solution worth considering. Now with full KVision support!

https://rjaros.github.io/kvision-examples/onsenui-kitchensink/?platform=android
