### ISSUE TITLE
Problems building the showcase in 2.7.0

### ISSUE THREAD

**Issue by rojeras** [rjaros/kvision#123]
When I clone and build the showcase I get the following:

➜  tmp git:(master) ✗ git clone https://github.com/rjaros/kvision-examples.git
Cloning into 'kvision-examples'...
remote: Enumerating objects: 1549, done.
remote: Counting objects: 100% (1549/1549), done.
remote: Compressing objects: 100% (583/583), done.
remote: Total 6519 (delta 839), reused 1354 (delta 694), pack-reused 4970
Receiving objects: 100% (6519/6519), 26.91 MiB | 11.37 MiB/s, done.
Resolving deltas: 100% (3496/3496), done.
➜  tmp git:(master) ✗ cd kvision-examples/showcase 
➜  showcase git:(master) ./gradlew -t run
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :kotlinNpmInstall
warning workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision > phantomjs-prebuilt@2.1.16: this package is now deprecated
warning workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision-bootstrap > phantomjs-prebuilt@2.1.16: this package is now deprecated
warning workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision-bootstrap-css > phantomjs-prebuilt@2.1.16: this package is now deprecated
warning workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision-bootstrap-datetime > phantomjs-prebuilt@2.1.16: this package is now deprecated
warning workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision-bootstrap-select > phantomjs-prebuilt@2.1.16: this package is now deprecated
warning workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision-bootstrap-spinner > phantomjs-prebuilt@2.1.16: this package is now deprecated
warning workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision-bootstrap-upload > phantomjs-prebuilt@2.1.16: this package is now deprecated
warning workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision-bootstrap-dialog > phantomjs-prebuilt@2.1.16: this package is now deprecated
warning workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision-fontawesome > phantomjs-prebuilt@2.1.16: this package is now deprecated
warning workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision-i18n > phantomjs-prebuilt@2.1.16: this package is now deprecated
warning workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision-richtext > phantomjs-prebuilt@2.1.16: this package is now deprecated
warning workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision-handlebars > phantomjs-prebuilt@2.1.16: this package is now deprecated
warning workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision-datacontainer > phantomjs-prebuilt@2.1.16: this package is now deprecated
warning workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision-chart > phantomjs-prebuilt@2.1.16: this package is now deprecated
warning workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision-tabulator > phantomjs-prebuilt@2.1.16: this package is now deprecated
warning workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision-redux > phantomjs-prebuilt@2.1.16: this package is now deprecated
warning workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision-pace > phantomjs-prebuilt@2.1.16: this package is now deprecated
warning workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision > karma-phantomjs-launcher > phantomjs-prebuilt@2.1.16: this package is now deprecated
warning workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > showcase > po2json > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning "workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision > snabbdom-virtualize@0.7.0" has incorrect peer dependency "snabbdom@~0.6.6".
warning "workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision-bootstrap > bootstrap@4.4.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning "workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision-bootstrap-datetime > pc-bootstrap4-datetimepicker@4.17.50" has unmet peer dependency "bootstrap@^4.0.0-beta.2".
warning "workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision-bootstrap-datetime > pc-bootstrap4-datetimepicker@4.17.50" has unmet peer dependency "jquery@^1.8.3 || ^2.0 || ^3.0".
warning "workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision-bootstrap-datetime > pc-bootstrap4-datetimepicker@4.17.50" has unmet peer dependency "moment@^2.10".
warning "workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision-bootstrap-datetime > pc-bootstrap4-datetimepicker@4.17.50" has unmet peer dependency "moment-timezone@^0.4.0 || ^0.5.0".
warning "workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision-bootstrap-select > bootstrap-select@1.13.12" has unmet peer dependency "jquery@1.9.1 - 3".
warning "workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision-bootstrap-select > bootstrap-select@1.13.12" has unmet peer dependency "bootstrap@>=3.0.0".
warning "workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision-bootstrap-upload > bootstrap-fileinput@5.0.7" has unmet peer dependency "jquery@>= 1.9.0".
warning "workspace-aggregator-15c59d36-3b85-499d-acac-cfc4d894e832 > kvision-bootstrap-upload > bootstrap-fileinput@5.0.7" has unmet peer dependency "bootstrap@>= 3.0.0".
warning Error running install script for optional dependency: "/Users/leo/tmp/kvision-examples/showcase/build/js/node_modules/fsevents: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/leo/tmp/kvision-examples/showcase/build/js/node_modules/fsevents
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | darwin | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/Users/leo/.gradle/nodejs/node-v10.15.3-darwin-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/leo/tmp/kvision-examples/showcase/build/js/node_modules/fsevents/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/leo/.gradle/nodejs/node-v10.15.3-darwin-x64/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/leo/.node-gyp/10.15.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/leo/.node-gyp/10.15.3',
gyp info spawn args   '-Dnode_gyp_dir=/Users/leo/.gradle/nodejs/node-v10.15.3-darwin-x64/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/leo/.node-gyp/10.15.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/leo/tmp/kvision-examples/showcase/build/js/node_modules/fsevents',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/leo/.gradle/nodejs/node-v10.15.3-darwin-x64/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command \"/Users/leo/.gradle/nodejs/node-v10.15.3-darwin-x64/bin/node\" \"/Users/leo/.gradle/nodejs/node-v10.15.3-darwin-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/leo/tmp/kvision-examples/showcase/build/js/node_modules/fsevents
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok"

> Task :processResources
Converted messages-en.po to messages-en.json
Converted messages-pl.po to messages-pl.json

BUILD SUCCESSFUL in 1m 1s
5 actionable tasks: 5 executed

Waiting for changes to input files of tasks... (ctrl-d to exit)
(node:3036) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
<-------------> 0% WAITING
> IDLE

**Comment by rjaros** [comment]
Do you have node.js installed on your system?

**Comment by rojeras** [comment]
➜  showcase git:(master) node --version
v13.4.0

**Comment by rjaros** [comment]
It looks like some kind of nodejs macos bug. There are some solutions given here:
https://github.com/nodejs/node-gyp/issues/1927

**Comment by rojeras** [comment]
Yes, yet another Catalina problem. I solved it with the instruction from bbehling in thread https://github.com/nodejs/node-gyp/issues/1927:

uninstall XCode Command Line tools by deleting
/Library/Developer/CommandLineTools/

reinstall XCode CLI
sudo xcode-select --install

intall gyp
npm install -g node-gyp
-------------------------------------------
Thank you, Robert!
