### ISSUE TITLE
Web and Electron

### ISSUE THREAD

**Issue by bmalkow** [rjaros/kvision#124]
Hi!

I'm trying to create application for website and for electron.
How should I organize and configure that project?

**Comment by rjaros** [comment]
If you are not using any Electron API and just want to build the same app for both platforms it should be easy - the  `build.gradle.kts` file in the `template-electron` project just adds some additional gradle tasks (`buildApp`, `runApp`, `bundleApp`) but all standard tasks (`run`, `zip`) are still available. So you can develop your app as a standard kvision web application and bundle it as an Electron app when it's ready.
But if you want to create some kind of "multiplatform" app, using a bit different code for web and for electron target, it will be more difficult. You will need to analyze what Electron API is required and what to use instead in the web version. Perhaps with the help of Kotlin MPP configuration, you can try to split your code into separate source sets.

**Comment by bmalkow** [comment]
Thanks for suggestion! I will try with source sets.
If I can do it, I will pull request with example.
