### ISSUE TITLE
pl.treksoft.kvision.types.LocalDateTime missing .now() initializer

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#127]
I can't seem to find a way to initialize a LocalDateTime in KVision.
Trying `LocalDateTime()` also throws an error telling me there are no default constructors. This is in a common module between a front end kvision and a backend ktor.

**Comment by rjaros** [comment]
You need to initialize it in a common module?

**Comment by robert-cronin** [comment]
it was just as a default value in the initializer of a custom class but I guess I can set it to null

**Comment by rjaros** [comment]
If you don't want a nulllable type, you can also easily add yourself a multiplatform initialization function:
In common:
```
expect fun LocalDateTimeNow(): LocalDateTime

val dateTime = LocalDateTimeNow()

```
In backend:
```
actual fun LocalDateTimeNow() = LocalDateTime.now()
```
In frontend:
```
actual fun LocalDateTimeNow() = Date()
```
