### ISSUE TITLE
dataContainer factory receiver

### ISSUE THREAD

**Issue by exaV** [rjaros/kvision#128]
I stumbled upon this weirdness: 

```
        root("kvapp") {
            vPanel(alignItems = FlexAlignItems.STRETCH) {
                dataContainer(data, { element, _, _ ->
                        text(value = element.name)
                })
            }
        }
```
The code above does not behave like I would have expected (add a text to the dom and update it when element.name changes). It adds a gazillion divs to the DOM, one for every update of `element.name`.

It took me a while to figure out that because the factory function does not have a receiver, the surrounding vPanel is used. Changing `text(value = element.name)` to `Text(value = element.name)` with a capital **T** solves the issue.

IMO this behavious is a bit inconsistent and confusing for newcomers.

**Comment by rjaros** [comment]
I'v commited a change that will allow to work with both "styles" of coding factory function. If you just return a component (e.g. `Text`) from a factory function, it will be used just like it's been until now. 
But the factory will also have a `Container` receiver and DSL builder functions will work correctly as well.
