### ISSUE TITLE
GroupBox?

### ISSUE THREAD

**Issue by joerg-rade** [rjaros/kvision#129]
Nowadays GroupBoxes seem to be out of fashion ;-)

Should I compose one myself?

**Comment by rjaros** [comment]
What is a group box ? :-)

**Comment by joerg-rade** [comment]
https://www.wpf-tutorial.com/Images/ArticleImages/1/misc-controls/groupbox_sample.png

**Comment by rjaros** [comment]
No group box in Bootstrap styles, so we don't have one in KVision. 
It should be easy to style such box with css, if you are using plain form controls. But it won't be so easy to add groupbox support for `FormPanel` container. I'll look at this.

**Comment by rjaros** [comment]
What do you think?

![fieldset](https://user-images.githubusercontent.com/5646804/73555164-5f48d280-444d-11ea-8af4-a5852b94b54b.png)

**Comment by joerg-rade** [comment]
I like it!

Meanwhile I followed your other suggestion and tweaked some css:
```
.panel-heading {
    padding: 3px 15px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    min-height: 3em;
    background-color: #ecf0f1;
    border-color: #ecf0f1;
    border-bottom: 1px solid transparent;
    border-top-left-radius: 3px;
    border-top-right-radius: 3px;
    box-sizing: border-box;
}

.panel-body {
    padding: 15px;
    box-sizing: border-box;
    font-size: 15px;
    border-left: 1px solid #ecf0f1;
    border-bottom: 1px solid #ecf0f1;
    border-right: 1px solid #ecf0f1;
}
```
