### ISSUE TITLE
Backend to frontend Image and Binary datatypes

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#13]
I'm trying to share data between my backend and front end by following your Ktor full stack example.
I have a data class like below:
```
data class Aircraft(var id:String = "",
                    var aircraft_image:Image? = null,
                    var aircraft_pdf:Binary? = null)
```
The my question is are there any Kvision native types that I can use to transfer these from back to front? or is it best to just encode them in Base64 and then decode on the frontend?

**Comment by rjaros** [comment]
KVision doesn't have any built in classes for binary data. So you should probably use base64 encoding and transfer the data as string (comunication is json based, so it would have to end up as base64 anyway).

You could probably define some suitable classes in your common module and custom serializers on the client side, to make it look more elegant.

**Comment by robert-cronin** [comment]
Okay thank you, I'll give it a go
