### ISSUE TITLE
Support jvm 9+, Jigsaw module

### ISSUE THREAD

**Issue by SchweinchenFuntik** [rjaros/kvision#131]
append support Jigsaw module

**Comment by rjaros** [comment]
What do you mean by Jigsaw module support? KVision is a Kotlin/JS project, and it doesn't work on JVM. Most of KVision jars doesn't contain any Java classes. The only parts using Java/JVM are bindings for Ktor, Spring and Jooby servers. But as I'm still using JDK8, I don't even know what should/could be done about this.

**Comment by SchweinchenFuntik** [comment]
yes, I meant the server side

**Comment by rjaros** [comment]
Do you have any issues running KVision fullstack apps on Java9+? What server do you use? Could you give more details about your problems?

**Comment by SchweinchenFuntik** [comment]
I haven’t started yet, I plan to transfer the server to java 11+, and modify the client part, so I looked at `KVision`

**Comment by SchweinchenFuntik** [comment]
I'll try to run and write about the results
