### ISSUE TITLE
Sliders

### ISSUE THREAD

**Issue by joerg-rade** [rjaros/kvision#132]
Bootstrap (at least the free variant) doesn't have sliders, but W3C references some:
https://www.w3schools.com/howto/howto_js_rangeslider.asp

Would be nice to have something like this

**Comment by rjaros** [comment]
Bootstrap 4 has slider: https://getbootstrap.com/docs/4.1/components/forms/#range-inputs
I'll try to add a slider component.

**Comment by joerg-rade** [comment]
cool

**Comment by rjaros** [comment]
`RangeInput` an `Range` components will be available in 2.10.0
