### ISSUE TITLE
Textarea in Window Scales Horizontally but Not Vertically

### ISSUE THREAD

**Issue by joerg-rade** [rjaros/kvision#133]
https://github.com/joerg-rade/kroviz/blob/master/src/main/resources/css/kroviz.css includes: 
```
textarea { height: auto; }
```
https://github.com/joerg-rade/kroviz/blob/master/src/main/kotlin/org/ro/ui/kv/RoDialog.kt  init reads:
```
    init {
        icon = IconManager.find(caption)
        isDraggable = true
        isResizable = true
        closeButton = true
        verticalAlign = VerticalAlign.BOTTOM
        panel = FormPanelFactory(items).panel
        panel?.let { add(it) }

        val buttonBar = HPanel(spacing = 10) {
            margin = 10.px
        }
        buttonBar.add(okButton)
        buttonBar.add(cancelButton)
        add(buttonBar)
    }
```
_Actual_: Buttons stick with the TextArea.bottom
**Expected**: Buttons stick with RoDialog:Window.bottom

![ScreenShot 381 kroViz - Google Chrome](https://user-images.githubusercontent.com/4637858/73726754-6105e500-4730-11ea-9495-f1874411577b.png)

What am I doing wrong?

**Comment by rjaros** [comment]
How is your textarea created? Does it have any other sizing?

**Comment by joerg-rade** [comment]
https://github.com/joerg-rade/kroviz/blob/master/src/main/kotlin/org/ro/ui/kv/FormPanelFactory.kt contains:
```    
private fun createTextArea(fi: FormItem): TextArea {
        val rowCnt = maxOf(3, fi.size)
        val item = TextArea(label = fi.label, value = fi.content as String, rows = rowCnt)
        item.readonly = fi.readOnly
        item.onEvent {
            change = {
                fi.changed(item.value)
                it.stopPropagation()
            }
        }
        return item
    }

```

**Comment by rjaros** [comment]
If you just want your buttons at the bottom of the window put everything in `vPanel(justify = FlexJustify.SPACEBETWEEN)` like this:

```
    init {
        vPanel(justify = FlexJustify.SPACEBETWEEN) {
            height = 100.perc
            // add(formPanel)
            // add(buttonBar)
        }
    }
```

**Comment by joerg-rade** [comment]
THX!

**Comment by rjaros** [comment]
If you would also like your textarea to fill the rest of the window size you can do this with some flexbox attributes and a simple CSS calc:
1. Remove `rows` parameter from `TextArea` constructor.
2. In your .css file put:
```
textarea {
    height: calc(100% - 30px) !important;
}
```
3. Initialize your components with something like this:
```
        vPanel(justify = FlexJustify.SPACEBETWEEN) {
            height = 100.perc
            val formPanel = FormPanel.create<Form> {
                height = 100.perc
                add(
                    Form::textarea,
                    TextArea(
                        value = "Lorem ipsum.",
                        label = "JSON"
                    ).apply {
                        height = 100.perc
                    })
            }
            add(formPanel, grow = 2)
            val buttonBar = HPanel(spacing = 10) {
                margin = 10.px
            }
            buttonBar.add(Button("OK"))
            buttonBar.add(Button("Cancel"))
            add(buttonBar)
        }
```
You need your formPanel to `grow` and then apply height = 100% to both form panel content and form item content. Finally the textarea is resized to 100% as well, but with CSS calc correction (substracting label height).

**Comment by joerg-rade** [comment]
When I resize the modal window, it is split horizontally with a scrollbar attached to the upper third, containing formpanel and buttonbar.
Could it be that the two overflow settings are conflicting?
![2020-05-29_18h46_20](https://user-images.githubusercontent.com/4637858/83321316-182deb00-a24f-11ea-9d2a-fa967cf80de4.png)

**Comment by rjaros** [comment]
Could you please post some code snippet?

**Comment by joerg-rade** [comment]
Here you go. Please note that the effect occurrs with and without TEXTAREA.
```
    init {
        icon = IconManager.find(caption)
        isDraggable = true
        isResizable = true
        closeButton = true
        contentWidth = CssSize(widthPerc, UNIT.perc)
        contentHeight = CssSize(heightPerc, UNIT.perc)

        vPanel(justify = FlexJustify.SPACEBETWEEN) {
            height = 100.perc
            formPanel = FormPanelFactory(items).panel
            //formPanel?.height = 100.perc  -- omitted here, already set in creating function

            add(formPanel!!, grow = 2)

            val buttonBar = HPanel(spacing = 10) {
                id = "button-bar"
                marginLeft = 10.px
            }
            buttonBar.add(okButton)
            buttonBar.add(cancelButton)
            if (items.isNotEmpty() && hasScalableContent()) {
                buttonBar.add(scaleDownButton)
                buttonBar.add(scaleUpButton)
            }
            add(buttonBar)
        }
    }
```
For full code see: 
* https://github.com/apache/isis/blob/master/incubator/clients/kroviz/src/main/kotlin/org/apache/isis/client/kroviz/ui/kv/RoDialog.kt
* https://github.com/apache/isis/blob/master/incubator/clients/kroviz/src/main/kotlin/org/apache/isis/client/kroviz/ui/kv/FormPanelFactory.kt
* https://github.com/apache/isis/blob/master/incubator/clients/kroviz/src/main/kotlin/org/apache/isis/client/kroviz/ui/kv/RoWindow.kt

**Comment by rjaros** [comment]
I see you are using your own window component (`RoWindow`). Why don't you use standard KVision `Window`? Also you are setting explicitly the height of the inner container to 30% - that's why it fills only 1/3 of the window.

**Comment by joerg-rade** [comment]
Unfortunately I do not remeber why I introduced it. I'll try to remove it (Less is more!).
I did set 30% my self - oh my goodness - that's a bit embarrassing!
