### ISSUE TITLE
Add Feature/Example: OpenSteetMap Integration 

### ISSUE THREAD

**Issue by joerg-rade** [rjaros/kvision#137]
https://wiki.openstreetmap.org/wiki/Main_Page
https://leafletjs.com/

**Comment by rjaros** [comment]
Leaflet has very complex API. Creating a module for KVision would require a lot of work, which unfortunately I can't do right now. I can try to create a very basic, skeleton module, but someone else would have to deal with the details.

**Comment by rjaros** [comment]
I've pushed a new module. For now it just allows to show a map:
```kotlin
        root("kvapp") {
            maps(51.505, -0.09, 13) {
                width = 600.px
                height = 300.px
            }
        }
```

**Comment by rjaros** [comment]
Any PR are welcomed :-)

**Comment by joerg-rade** [comment]
Thanks for the sample, Robert. I've put it on my list.

**Comment by joerg-rade** [comment]
I see ~build\js\node_modules\kvision-kvision-maps\kvision-kvision-maps.js 
What should I read in order to understand how js is mapped to kotlin?

**Comment by rjaros** [comment]
I assume we are talking about expanding the `kvision-maps` module. So in short:
1. The module integrates with [Leaflet.js](https://leafletjs.com/) JS library. So you have to read the [documentation](https://leafletjs.com/reference-1.6.0.html) first.
2. You need to implement new methods in `pl.treksoft.kvision.maps.Maps.kt` file in the `kvision-modules/kvision-maps` directory.
3. There is `jsMaps: dynamic` property in this class, which is initialized with a [Map](https://leafletjs.com/reference-1.6.0.html#map-example) instance. You should be able to call all the [methods](https://leafletjs.com/reference-1.6.0.html#map-methods-for-modifying-map-state) on this object. Typically you create new Kotlin methods in the `Maps` class, with type-safe arguments and parameters, and then map those calls to the dynamic calls on `jsMaps` instance.
4. There is also ` KVManagerMaps.leaflet` internal helper object, which is a `L` factory object used to create other Leaflet objects (layers, makers etc).

If you have more questions we can talk on the Slack channel.

**Comment by joerg-rade** [comment]
I would like to use slack, but it look like I need an invitation.
Please send one.

**Comment by rjaros** [comment]
As far as I know, you need to submit your request and just wait till someone from JB accepts your invitation. I can't do this.
