### ISSUE TITLE
Use kotlinx.serialization on server and client side

### ISSUE THREAD

**Issue by rossdanderson** [rjaros/kvision#139]
If possible, it would be nice to use kotlinx.serialization on both the server side and the client side.

In a Spring project I believe it currently uses Jackson on the server side, and kotlinx.serialization on the client side, this makes it tricky to use things like sealed class hierarchies.

I've used a slight workaround to get around this by wrapping it in an outer message:

```
@Serializable
data class OuterServerMessage(
    val payload: String
) {
    constructor(serverMessage: ServerMessage) : this(json.stringify(ServerMessage.serializer(), serverMessage))

    val message: ServerMessage
        get() = json.parse(ServerMessage.serializer(), payload)
}

@Serializable
sealed class ServerMessage {

    @Serializable
    data class ResponseContainer(
        val requestId: String,
        val response: Response
    ) {
        @Serializable
        sealed class Response {

            @Serializable
            data class ProductPairs(
                val productPairs: List<ProductPair>
            ) : Response()
        }
    }

    sealed class StreamEvent : ServerMessage() {
        abstract val requestId: String

        @Serializable
        data class StreamComplete(
            override val requestId: String
        ) : StreamEvent()

        @Serializable
        data class StreamResponseContainer(
            override val requestId: String,
            val streamResponse: StreamResponse
        ) : StreamEvent() {

            @Serializable
            sealed class StreamResponse {

                @Serializable
                data class Book(
                    val rates: List<String>
                ) : StreamResponse()

                @Serializable
                data class ReferencePrice(
                    val bidPrice: String,
                    val offerPrice: String
                ) : StreamResponse()
            }
        }
    }
}
```

**Comment by rjaros** [comment]
I've already tried using `kotlinx.serialization` on the server side. But it doesn't work. KVision needs to serialize/deserialize almost any data automatically and `kotlinx.serialization` just can't do this (yet?). It requires explicit serializers in many cases (generics, collections) and has some limiting type bounds on almost any inline helper function. It's **a lot** easier to use jackson, which just works.
On the client side there is no other choice, but serialization/deserialization code with `kotlinx.serialization` is really a bunch of hacks with lots of try/catch and JS dynamic types - just look at this file: https://github.com/rjaros/kvision/blob/master/kvision-modules/kvision-remote/src/main/kotlin/pl/treksoft/kvision/remote/RemoteAgent.kt

**Comment by rjaros** [comment]
Perhaps there is some other possibility to fix your problems with sealed classes. Please give some more details. See also https://github.com/FasterXML/jackson-module-kotlin/issues/239

**Comment by joerg-rade** [comment]
Thanks for the pointer to RemoteAgent.kt - I'll take it as template to improve my own code.
Could you take a look  at https://github.com/Kotlin/kotlinx.serialization/issues/701 and eventually suggest a solution?

**Comment by rjaros** [comment]
I'm not an expert of kotlinx.serialization. My complex code is just a matter of lots of trial and error ;-)

**Comment by joerg-rade** [comment]
OK - thanks - so is mine ;-)
