### ISSUE TITLE
Something strange with onEvent in 3.0.0

### ISSUE THREAD

**Issue by rojeras** [rjaros/kvision#143]
I copied your construct from the Data-tab in the showcase:

`            textInput(type = TextInputType.SEARCH) {
                placeholder = tr("Search ...")
                onEvent {
                    input = {
                        searchFilter = self.value
                        dataContainer.update()
                    }
                }
            }`

With 3.0.0 I got a problem with that the last character typed is missing. When I try it out in showcase data tab (https://rjaros.github.io/kvision-examples/showcase/#!/data) the problem is reproducable. When you type one character nothing happens, type another and the first one is used and so forth.

**Comment by rjaros** [comment]
Confirmed. It's a very stupid mistake of mine ;-) I've no idea how could I have missed it ;-) I'm building 3.0.1 right now.

**Comment by rjaros** [comment]
Fixed in 3.0.1

**Comment by rojeras** [comment]
I can confirm that it is fixed in 3.0.1. Splendid support!
