### ISSUE TITLE
paginationELement not working in Kvision Framework (Kotlin Language)

### ISSUE THREAD

**Issue by harshit9033** [rjaros/kvision#146]
I had used tabulator where I came across paginationElement feature, which wasn't working as per the documentation. Would you please look into it.

**Comment by rjaros** [comment]
Hello,
What value do you pass as `paginationElement` parameter?

**Comment by harshit9033** [comment]
paginationElement = document.getElementsByClassName("demo")
or
paginationElement = document.getElementById("demo")

either not working!

**Comment by rjaros** [comment]
And how do you create this "demo" element? Is this a KVision component?

**Comment by harshit9033** [comment]
div (classes = setOf("demo")) { id = "demo" }

**Comment by rjaros** [comment]
The problem is the DOM element with `"demo"` id doesn't exists, when you use `getElementById()` function. If you create such element in the main `index.html` file, it will work. But of course is not a good solution. I'll think about an alternative.

**Comment by harshit9033** [comment]
Ok. Appreciate for your efforts.

**Comment by rjaros** [comment]
There is no way to use `paginationElement` attribute directly, unless you create and insert your tabulator component dynamically, when the pagination element is already rendered.

But this "hack" seems to work for me:
```
// create your tabulator component as always, just store the reference in a variable
        val tab = tabulator(...)
// create an element for pagination with a custom component, which overrides afterInsert() method.
// here I use anonymous class inheriting from Div
        add(object : Div() {
            override fun afterInsert(node: VNode) {
// force tabulator to reinit it's pagination element when DOM node is ready
// no need to give ID, because we can reference this element directly from VNode
                tab.jsTabulator?.options?.paginationElement = node.elm
                tab.jsTabulator?.modules.asDynamic().page.initialize()
            }
        })
```

**Comment by harshit9033** [comment]
It worked. Thanks.

**Comment by rjaros** [comment]
Since version 3.6.0 you no longer need to inherit from a class to access `afterInsert` callback. You can do:
```kotlin
div {
	afterInsertHook = { vnode ->
		tab.jsTabulator?.options?.paginationElement = vnode.elm
		tab.jsTabulator?.modules.asDynamic().page.initialize()
	}
}
```
