### ISSUE TITLE
RestClient - response access issue

### ISSUE THREAD

**Issue by harshit9033** [rjaros/kvision#149]
While performing Rest API Functionality, I came across an issue of accessing response value which is been received as json.

code:- 
@Serializable
data class StudentsData( var id: String, var name: String, var age: String )

val restClient = RestClient()
val result: Promise<Response<StudentsData>> = restClient.remoteRequest("http://10.68.101.9/rest-api/students/" + StudentsGrid.studentId)
        
result.then {
            it.data.let {
                window.alert(it.name.toString())
            }
 }

api response:- {"id":"1","name":"Harshit","age":"26"}

Thanks in advance.

**Comment by rjaros** [comment]
How is `Response` defined?

**Comment by rjaros** [comment]
This simple code should work:
```
val restClient = RestClient()
val result: Promise<Response<StudentsData>> = restClient.request("http://10.68.101.9/rest-api/students/" + StudentsGrid.studentId)
result.then {
    window.alert(it.data.name.toString())
}
```

**Comment by harshit9033** [comment]
It is showing undefined in laert.!

**Comment by rjaros** [comment]
I've tested the code below with PokeApi, and it works fine. Please compare to yours:
```
@Serializable
data class PokemonData(var id: Int, var name: String)

fun main() {
    val restClient = RestClient() 
    val result: Promise<Response<PokemonData>> = restClient.request("https://pokeapi.co/api/v2/pokemon/ditto/")
    result.then {
        window.alert(it.data.name)
    }
}
```

**Comment by rjaros** [comment]
I hope we can close this issue.
