### ISSUE TITLE
DataContainer adding duplicate elements when using table row

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#15]
I am getting some strange results when using DataContainer with table rows.
I have a table that looks something like this:
```
table(
    listOf("Column 1", "Column 2"),
    setOf(TableType.BORDERED, TableType.CONDENSED, TableType.STRIPED, TableType.HOVER), responsive = true
) {
    dataContainer(pairList, { element, idx, list ->
        row {
            cell(element.first)
            cell(element.second)
        }
    })
}
```
where `pairList` is defined as:
```
var pairList:ObservableList<Pair<String, String>> = observableListOf()
init {
    pairList.add(Pair("first","second"))
    pairList.add(Pair("third","fourth"))
}
```
and the result I am getting looks like this:
![Screen Shot 2019-03-14 at 9 48 26 am](https://user-images.githubusercontent.com/8540764/54325657-589b4c00-463e-11e9-9150-b44a50746ca1.png)

Nowhere else is pairList being set to an element, so I'm not sure why the duplicate values are showing up

**Comment by rjaros** [comment]
When using DataContainer's `factory` lambda you should just return the created Row component. And you are using DSL function `row` which also adds the created component to the outer container. Just change `row` to `Row` and it should be OK.

**Comment by robert-cronin** [comment]
Yeah that solved the problem, do you want me to post these mostly how to use questions on stackoverflow? Might be a bit easier to keep actual issues separate

**Comment by rjaros** [comment]
For now it's OK to post it here :)
