### ISSUE TITLE
New Html/Component Template Design

### ISSUE THREAD

**Issue by djeang** [rjaros/kvision#152]
Hi,

Would it be possible to add an Html/Compoonent template based on [parent-chaining pattern](https://github.com/djeang/parent-chaining/blob/master/readme.md) ?

It may lead in much clearer code when designing Html component. What do you think of ?

**Comment by rjaros** [comment]
Could you provide an example, where parent-chaining pattern has advantages over currently implemented DSL builders? I could be wrong, but it seems to me like a solution for languages which don't have support for creating DSL's (like Java).

**Comment by djeang** [comment]
Well, I admit to be a newbie in Kotlin, but I fell  expressions expressed like the following looked more concise and closest to HTML than the examples I saw about KVision. 
Maybe my own vision is biased cause of my lack of Kotlin culture.  
This is [an other example](https://github.com/djeang/vincer-dom/blob/master/readme.md) (still in Java) 
```
Html html = new Html()
    .head()
        .title("Title of my document")
        .meta().charset("UTF-8").__
        .meta().content("description", "Parent-Chaining illustrator").__
        .meta().content("keywords", "design pattern, chaining, tree structure, Java").__
        .meta().content("author", "Jerome Angibaud").__.__
    .body()
        .text("This is a simple page for describing Parent-Chaining pattern.")
        .div().attr("style", "bold")
            .text("A first div displayed in bold.")
            .div()
                .img().attr("src", "fuse.png").attr("alt", "A fuse image.").__
                .text("This is a new table")
                .table().attr("style", "width:100%")
                    .tr()
                        .th().text("Firstname").__
                        .th().text("Lastname").__
                        .th().text("Age").__.__
                    .tr()
                        .td().text("Jill").__
                        .td().text("Smith").__
                        .td().text("50").__.__
                    .tr()
                        .td().text("Eve").__
                        .td().text("Jackson").__
                        .td().text("94").__.__.__.__.__
        .div()
            .text("This is the end of this page.").__.__;
```

**Comment by rjaros** [comment]
Thx for your feedback! :-)

With KVision you generally do not generate HTML, because you build your app with ready to use components. And that's what you find when you look at KVision examples.

But if you like, you can also generate HTML markup at low level using DSL. I've dropped the page header from your example (because you do not generate this with KVision), but the rest of your sample would look similar the code below with KVision DSL:
```
root("kvapp") {
	+"This is a sample layout with KVision DSL."
	div {
		bold {
			+"A first div displayed in bold."
		}
		div {
			image("fuse.png", alt = "A fuse image.")
			+"This is a new table"
			table {
				width = 100.perc
				row {
					thcell("Firstname")
					thcell("Lastname")
					thcell("Age")
				}
				row {
					cell("Jill")
					cell("Smith")
					cell("50")
				}
				row {
					cell("Eve")
					cell("Jackson")
					cell("94")
				}
			}
		}
	}
	div {
		+"This is the end of this page."
	}
}
```
I think it's very clean and very readable (and 100% type safe at the same time). What do you think?

**Comment by djeang** [comment]
Ok, I get it. Thank you :-)
