### ISSUE TITLE
Add support for Jquery animations or similiar

### ISSUE THREAD

**Issue by SKeeneCode** [rjaros/kvision#154]
Animating components are a great way to add flavor and user feedback to applications.

This is a feature request for KVision to support the animation of components and their properties.

**Comment by rjaros** [comment]
I've implemented jQuery effects with new methods in `Widget` class - `showAnim`, `hideAnim`, `fadeIn`, `fadeOut`, `slideDown`, `slideUp`. I've also added `animate()` method for custom animations with https://api.jquery.com/animate/. All methods allow to configure duration and easing (swing/linear). 
An example:
```
                val div = div("Lorem ipsum").apply {
                    border = Border(2.px, BorderStyle.SOLID, Color.name(Col.BLUE))
                    width = 50.px
                    height = 50.px
                }
                button("animate").onClick {
                    div.animate(1500, Easing.LINEAR, complete = {
                        div.fadeOut(1000)
                    }) {
                        width = 450.px
                        height = 150.px
                    }
                }
```
