### ISSUE TITLE
Set focus on first element in a DropDown?

### ISSUE THREAD

**Issue by joerg-rade** [rjaros/kvision#157]
This could reduce switching back and forth between keyboard and mouse.

**Comment by rjaros** [comment]
When the DropDown is focused, press Space or Enter to open it and then Tab to focus first element. Does it work for you?

**Comment by joerg-rade** [comment]
* Neither Space nor Enter seem to have an effect, when the DD (in a NavBar) is focused (in my case: color changes from white to grey). 
* DD menulist is shown when I select [v] by mouse.
* Pressing Tab when DD is expanded leads to collapsing the list

**Comment by joerg-rade** [comment]
While we are at it (making keyboard a 1st class citizen, too):

Is there an example for attaching keyboard shortcuts to menu entries, like in [Save ... <CTRL>-<S>]?

**Comment by rjaros** [comment]
What browser do you use? I'm testing the dropdowns in the Showcase example (https://rjaros.github.io/kvision-examples/showcase/#!/dropdowns) - one is inside the navbar, and three are standalone. And it works fine with Space/Enter and Tab keys in both Chrome and Firefox.

**Comment by rjaros** [comment]
> Is there an example for attaching keyboard shortcuts to menu entries, like in [Save ... CTRL-S] ?

No support for hotkeys yet. You will have to implement this by yourself. You can do it like this:
```
        jQuery(window).keydown {
            if (it.key == "s" && it.ctrlKey) {
                console.log("saving ...")
                it.preventDefault()
            }
        }
```

**Comment by joerg-rade** [comment]
I use Version 81.0.4044.113 (Official Build) (64-bit)
And you are right, dropdowns works like you describe / expected.
So I must have overriden some default, unintetionally.
