### ISSUE TITLE
Drag and Drop / DataTransferItem getAsString Example?

### ISSUE THREAD

**Issue by joerg-rade** [rjaros/kvision#159]
getAsString is given  as:
```
    fun getAsString(_callback: ((String) -> Unit)?)
```
An example for such a callback function would be very much appreciated!

**Comment by rjaros** [comment]
Could you please write what you are trying to do? In KVision D&D is supported at a `Widget` level, and you do not need to use `DataTransferItem` directly.

**Comment by joerg-rade** [comment]
I want to drag an Object onto a panel.
The Object is supposed to present itself as a Button (which later on shall become a drop target - but that´s is a different story).
I pass on a url (String) which is a unique identifier for the Object:
```
        b.setDragDropData(RoToolPanel.format, data.url)
```
On the target side I use:
```
        panel.setDropTarget(format) { data ->
            val dti = data.dataTransfer!!.items[0]
            var url = ""
            dti?.getAsString { it: String ->
                url = it
            }
            val reSpec = ResourceSpecification(url)
            val logEntry = EventStore.find(reSpec)!!
            val to = logEntry.obj!! as TObject
            val exp = Exposer(to)
            addButton(exp)
        }
```
Is there a better, simpler way to access my POS (Poor Old String:-) ?

**Comment by rjaros** [comment]
Why don't you use `setDropTargetData` function? It should work like this:
```
panel.setDropTargetData(format) { url -> 

}
```

**Comment by joerg-rade** [comment]
Easy answer: PEBKAC (to be more specific: I did not C&P from your docs, but relied on autocompletion)
