### ISSUE TITLE
Modal background effect not disappearing with modal.hide(), Version 0.0.29

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#16]
I have a modal I initialize and show with the following code in the root of the showcase example:
```
root = Root("showcase") {
    val modal = Modal("Example Modal", size = ModalSize.LARGE, closeButton = true,
            animation = false, escape = false)
    modal.show()

    tabPanel {
        width = 80.perc
        margin = 20.px
       .....
}
```
The result looks fine:
![Screen Shot 2019-03-14 at 11 44 07 am](https://user-images.githubusercontent.com/8540764/54330044-31994600-464f-11e9-8173-de312402aedf.png)
until I try to close the modal:
![Screen Shot 2019-03-14 at 11 44 17 am](https://user-images.githubusercontent.com/8540764/54330055-3c53db00-464f-11e9-8f3b-fd55903e3f46.png)
Is there any way to remove the background effect and UI blocking after calling modal.hide() or pressing the closeButton?

**Comment by rjaros** [comment]
The problem is you are trying to display the modal window before the root component is initialized and rendered. And the modal is actually showing twice (the background effect is darker than normally). The easiest way to fix this, is to move `modal.show()` after the `Root` initializer.
```
        lateinit var modal: Modal
        root = Root("showcase") {
            modal = Modal("Example Modal", size = ModalSize.LARGE, closeButton = true,
                animation = false, escape = false)
            tabPanel {
                width = 80.perc
                margin = 20.px
                // ...
            }
            // ...
        }
        modal.show()
```

**Comment by robert-cronin** [comment]
Cheers, closing this issue as solved
