### ISSUE TITLE
Styling DropDown.button

### ISSUE THREAD

**Issue by joerg-rade** [rjaros/kvision#161]
I would like to colorize (etc.) the button (image) in a DropDown  eg. via css:
```
.tool-icon-factory {
    color: green !important;
    caret-shape: unset !important;
}
```
but button is defined as:
```
    internal val button: DropDownButton = DropDownButton(
        idc, text, icon, style, disabled, forNavbar, forDropDown
    )
```
and I can assign the style only to DropDown, but not to DropDownButton.
Am I missing something?

Subclassing is not an option - should I use brute force and c&p DropDown into MyDropDown?
What would you recommend?

**Comment by rjaros** [comment]
There are a few solutions possible:
1. Add CSS class to the button using `afterInsertHook` and jQuery bindings.
```
dropDown("A drop down", ...) {
    // ...
    afterInsertHook = {
        getElementJQuery()?.find("button")?.addClass("my-css-class")
    }
}
```
2. Define your CSS for child selector and add CSS class name to the `DropDown`.
```
.my-css-class > button {
}
```
3. Filll an issue and I can change button property from internal to public in the next release ;-)
