### ISSUE TITLE
Micronaut support

### ISSUE THREAD

**Issue by dave08** [rjaros/kvision#168]
Follow up from slack: https://kotlinlang.slack.com/archives/C0BJ0GTE2/p1593551723298700

**Comment by rjaros** [comment]
I'm afraid there is currently no way to add support for Micronaut to KVision. KVision fullstack apps use MPP (Kotlin Multiplatform) architecture. But kapt is not compatible with MPP and it cannot be used with such projects. Until I find an example Kotlin MPP project with Micronaut, I have no idea how to resolve this.

**Comment by rjaros** [comment]
I have found a way to run kapt in MPP, so there is still a chance ... ;-)

**Comment by dave08** [comment]
Great, thanks!

**Comment by rjaros** [comment]
Micronaut support is ready. Will be available in the next release.
