### ISSUE TITLE
Using an Observable List with Select Form

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#17]
I might be using Select form the wrong way, but I have an internal API that returns an observable list which I would like to use in a select box. I'm not sure how to make the select options update with the new elements added to the observable list.
This is what I have so far:
```
class SomeContainer: SimplePanel() {
    var someList: ObservableList<Pair<String, String>> = observableListOf()
    init {
        val formPanel = formPanel<SomeForm> {
            add(
                    SomeForm::select,
                    Select(
                            label = "Simple select"
                    ).also {
                        options = someList
                        liveSearch = true
                    }
            )
        }
        someList.add(Pair("someValue", "someLabel"))
        someList.add(Pair("someOtherValue", "someOtherLabel"))
        .....
    }
}
```
The result is an empty options list when selecting, perhaps this is expected since options expects a non-mutable list.
Is there any way to do this?

**Comment by rjaros** [comment]
The `options` parameter of the `Select` component is designed for static usage. To have dynamic list of options use the `DataContainer` as a non-visual wrapper, like that:
```
val someList: ObservableList<Pair<String, String>> = observableListOf()
val select = Select(label = "Simple select").apply {
    liveSearch = true
}
DataContainer(someList, { pair, _, _ -> SelectOption(pair.first, pair.second) }, select)
add(SomeForm::select, select)
```

**Comment by rjaros** [comment]
And remeber to add the `Select` component to the `FormPanel` **after** the `DataContainer` is created. It's important, because it must be a child of some visual container (one "connected" to the root component).

**Comment by robert-cronin** [comment]
Is there any way to make a formPanel return data when an option is selected?
something like the way a link registers a click:
```
link("label").onclick {
    print("link clicked)
}
```
Maybe something like 
```
val select = Select(label = "Simple select").apply { liveSearch = true }.onClick {
    doSomething(text: select.value)
}
```

**Comment by rjaros** [comment]
Just add an event listener. You can listen to the standard `change` event or custom `changedBsSelect` event, which transfers a little more information.
```
            val select = Select(
                options = listOf("first" to tr("First option"), "second" to tr("Second option")),
                label = tr("Simple select")
            ).apply {
                setEventListener<Select> {
                    change = {
                        console.log("change event, value: ${self.value}")
                    }
                    changedBsSelect = { e ->
                        console.log("changedBsSelect event, new value: ${self.value}")
                        console.log("changedBsSelect event, clicked position index: ${e.detail.clickedIndex}")
                    }
                }
            }
```
See [this chapter](https://kvision.gitbook.io/kvision-guide/part-1-fundamentals/events) for more details.

**Comment by robert-cronin** [comment]
Awesome thanks!

**Comment by robert-cronin** [comment]
I'm now trying to use the same method for a table view, this is what I have:
```

val tableTemplate = Table(
        listOf("TestColumn"),
        setOf(TableType.BORDERED)
)
DataContainer(testObservableList, { element, idx, list ->
    row {
        cell(element)
    }
}, tableTemplate)
```
However I am getting row and cell undefined. 
The error dissappears if I use `Row {..` but nothing shows up in the DOM. 
What would be the right way to approach this?

**Comment by rjaros** [comment]
```
import com.lightningkite.kotlin.observable.list.observableListOf
import pl.treksoft.kvision.data.DataContainer.Companion.dataContainer
import pl.treksoft.kvision.table.Table
import pl.treksoft.kvision.table.TableType
import pl.treksoft.kvision.table.Row
import pl.treksoft.kvision.table.Cell.Companion.cell

val testObservableList = observableListOf("a", "b", "c")

root = Root("kvapp") {
            val tableTemplate = Table(
                listOf("TestColumn"),
                setOf(TableType.BORDERED)
            )
            dataContainer(testObservableList, { element, idx, list ->
                Row {
                    cell(element)
                }
            }, tableTemplate)
}
```

**Comment by rjaros** [comment]
"Table" - constructor of the Table component, which will be passed to the DataContainer
"dataContainer" - DSL builder function, which creates DataContainer object and adds it to the Root container
"Row" - constructor of the Row component, which will be returned by the factory lambda
"cell" - DSL builder function, which creates Cell component and adds it to the Row component

Constructor is always uppercase. DSL function lowercase. You need some practice to know which to use :-)

**Comment by robert-cronin** [comment]
I figured it would be some combination of the constructors and DSL, probably would have found it if I kept fiddling, thanks Robert
