### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by eugenio1590** [rjaros/kvision#173]
I have been working with that library. And It is a great tool to simplify the syntax of the Kotlin Wrapper and React. But I have a problem with navigation. It is common to use [React Router](https://reactrouter.com/) for navigation, but KVision uses the [Navigo](https://github.com/krasimir/navigo) library with the routing global object. I need to change the "content" section manually with a handler function. How to do it? I can use `jQuery("#content").replaceAll(/***/)` or something like that but I am not sure. [React Router](https://reactrouter.com/) library makes this for me, I only need to specify the routing. So, how to handle this?

**Comment by rjaros** [comment]
Routing in KVision is probably supported on a bit lower-level than in React. Look how this example application defines routing, extract parameters and dispatches actions based on the extracted data: 

https://github.com/rjaros/kvision-realworld-example-app/blob/master/src/main/kotlin/io/realworld/Routing.kt#L16

The routing doesn't do anything else - it just executes actions and changes the state (stored in ReduxStore in this example, but it can be any other observable store). And the view is updated with state bindings:

https://github.com/rjaros/kvision-realworld-example-app/blob/master/src/main/kotlin/io/realworld/App.kt#L36

**Comment by eugenio1590** [comment]
Thanks for the quick response. I create the store and the reducer for the view, and update the routing. But this does not work for me. Ok, the view updated, but I am using component classes and added them to the view. This is my code:

````
main {
  bind(ConduitManager.store) { state ->
     when (state.viewRoute) {
        ViewRoute.Invoices-> add(InvoicesUI())
         else -> div { +"Empty" }
     }
  }
}

class InvoicesUI : SimplePanel() {
    init {
        p(content = "InvoicesUI")
    }
}
````

**Comment by rjaros** [comment]
I think there is nothing wrong with this code. It should work. 
Could you please show more of your code (or even a full application if it's open source)?

**Comment by eugenio1590** [comment]
Sorry for the delay. Yes, sure. I'll make a demo application with that issue later.

**Comment by eugenio1590** [comment]
It worked. I make a mistake adding the binding to the store on the UI. So, you can close this issue.

I only have a problem with the React dependency. I mean this dependency:

````
kvisionVersion = "3.11.2"
implementation("pl.treksoft:kvision-react:$kvisionVersion")
````

I got the following error:

````
error Couldn't find any versions for "kotlinx-html-js" that matches "0.6.12"
````

**Comment by rjaros** [comment]
It's definitely available both on maven central:
https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-html-js/0.6.12
and bintray:
https://bintray.com/kotlin/kotlinx.html/kotlinx.html/0.6.12

Could you try to clean your project and copy here the whole log with this error?

**Comment by rjaros** [comment]
Current [showcase example](https://github.com/rjaros/kvision-examples/blob/master/showcase/build.gradle.kts#L89) uses `kvision-react` module and is working fine.

**Comment by eugenio1590** [comment]
The problem happens because I am using a [Kotlin/JS project](https://kotlinlang.org/docs/reference/js-project-setup.html#npm-dependencies) and the npm dependencies have been installed using Yarn. I'll try to fix this. Thanks for your help.

**Comment by rjaros** [comment]
Ok. Closing the issue then.
