### ISSUE TITLE
Component Lifecycle

### ISSUE THREAD

**Issue by eugenio1590** [rjaros/kvision#174]
I am migrating my application from react because KVision is easier to understand and the syntax is shorter than React Wrapper. But I do not understand what is the component lifecycle and I have not seen anything about that in the KVision documentation.

I need to change this:

`override fun componentDidMount() = props.onLoad()`

I found a couple of function to do it:

````
override fun afterCreate(node: VNode) 
override fun afterInsert(node: VNode) 
````

But which of them should be overridden?

**Comment by rjaros** [comment]
You probably need `afterInsert`. KVision lifecycle methods are bound to [snabbdom hooks](https://github.com/snabbdom/snabbdom#hooks), so `afterInsert` is called when native element is inserted into the DOM. 

Also remember, if you don't want to inherit from KVision class and override its methods, you can use `afterInsertHook` property for any component, like this:
```
component.afterInsertHook = { vnode ->
    console.log(vnode.elm)
}
```

**Comment by eugenio1590** [comment]
Thanks for the quick response. But I have some problems. When I added the navigation, I create a binding to the store similar to that:

````
main {
  bind(ConduitManager.store) { state ->
     when (state.viewRoute) {
        ViewRoute.Invoices-> add(InvoicesUI())
         else -> div { +"Empty" }
     }
  }
}

class InvoicesUI : SimplePanel() {
    init {
        p(content = "InvoicesUI")
    }
}
````

That worked. But if I change the InvoicesUI class like that:

````
class InvoicesUI(private val store: ReduxStore<State, RAction>) : SimplePanel() {
    init {
        p(content = "InvoicesUI")
    }
   override fun afterInsert(node: VNode) {
        super.afterInsert(node)
        store.dispatch { dispatch, _ ->
           Services.fetchInvoces(dispatch)
        }
   }
}

//navigation
//add(InvoicesUI(store))
````

This didn't work. I think It is because the navigation creates a new InvoicesUI object when the store is updated and add it indefinitely to the DOM. So, I am not sure how to handle it because React manages the lifecycle of the components otherwise.

**Comment by rjaros** [comment]
Why do you need to dispatch this redux action in the `afterInsert` method?

**Comment by rjaros** [comment]
Generally you should use `afterInsert` hook for doing things that require the DOM element to exist in the DOM tree. It could be using some external library, jquery plugin and other things that work directly with the DOM element. Fetching data is usually no such thing. So in my opinion it should be run independently (e.g. in a routing handler function).

**Comment by eugenio1590** [comment]
Yes, I need to fetch some data from the server. Let me try to do this using a routing handler function.

**Comment by eugenio1590** [comment]
It is not exactly what I expected but it worked. Thanks.
