### ISSUE TITLE
toast onClick handler does not work

### ISSUE THREAD

**Issue by rjtg** [rjaros/kvision#179]
when specifying an onClick handler via ToastOptions for a Toast, the onClick handler is not executed.
The cause is that the onClick handler is turned into a callback called "onClick" in the ToastOptions.toJs() function, while it should be turned into one called "onclick" with a minor "c"

Toast.kt line 120
        if (onClick != null) this.onClick = onClick
needs to be
        if (onClick != null) this.onclick = onClick

**Comment by rjaros** [comment]
You are right. Thx for the report.

**Comment by rjaros** [comment]
Fixed in 3.13.1
