### ISSUE TITLE
Typeahead/Select component with remote data source

### ISSUE THREAD

**Issue by eugenio1590** [rjaros/kvision#180]
I am trying to use these components with remote data source but I do not understand how to configure. I think it is better to create a parameter like that:

````
suspend fun getOptions(search?: String): List<String>
````

It is more customizable and I can use that with the base component (~remote~).

I have seen the ajax options for the base component, I mean [AjaxOptions](https://rjaros.github.io/kvision/api/pl.treksoft.kvision.form.select/-ajax-options/index.html) class, but to separate the UI components from the business logic, I prefer to use a custom service class.

On the other hand, I have not been seeing a function parameter to display each option of the components. I mean I want to include images and more information like a description or a date. Currently, I can only see a list of items.

**Comment by eugenio1590** [comment]
Hi rjaros

Sorry for the delay in reply. Thanks for your explanation. I have read about the `SelectRemote` and `TypeaheadRemote` components in the documentation, but I don't like them. I prefer to use the base component. Let me explain this a little better.

My issue is the following. I need to search for some records from a remote data source. I can use the Typeahead component for that. Check this configuration:

````
typeahead(
  label = "Customers",
  taAjaxOptions = TaAjaxOptions(
    url = "http://localhost:3000/customers",
    preprocessData = {
      // I am not sure how to parse the data here, but I think it is something similar to this
      val customers: List<Customer> = JSON.parse(it.customers.toString())
      customers.map { it.email }.toTypedArray()
    }
  )
)
````

That's great and very simple to set up.

So. I have a component that accesses to a remote data source, that's not good. And the data is parsed in a callback in the UI, so bad. That is not a good design pattern. If the URL changes or if I need to add some special parameter to the query, I need to change the component settings in the UI.

Even, If I need to search for the customers in the background, I need to create a service for that because the Ajax query to do it does not exist.

So, to resolve this. Why not adds a new parameter called "source" or "getOptions" or something like that to obtain the items from the data source?

````
suspend fun source(search?: String, callback: (Array<String>) -> Unit)
````
The callback method will update the "options" in runtime

````
typeahead(
  label = "Customers",
  source = { search, callback ->
    jQuery.ajax("http://localhost:3000/customers", obj {
         this.success = { data: dynamic, _: Any, _: Any ->
              // I am not sure how to parse the data here, but I think it is something similar to this
             val customers: List<Customer> = JSON.parse(data.customers.toString())
             val processedData = customers.map { it.email }.toTypedArray()
             callback(processedData)
         }
    })
  }
)
````

I can use this new parameter to access the remote data source and this "source" function can be a method of a "service". Something like this:

````
typeahead(
  label = "Customers",
  source = { search, callback ->
     CustomerService.searchByEmail(search) { customers ->
         val processedData = customers.map { it.email }.toTypedArray() 
         callback(processedData)
     }
  }
)
````

**Comment by rjaros** [comment]
In fact it's easy to add `source` parameter to the `Typeahead`/`TypeaheadInput` component, because it's already there in the underlying JS component. I've just kept it hidden, because I've modeled these components to have similar API to the `Select`/`SelectInput` components. I will expose `source` parameter in the next version. 

But note:

1. Source function will not be suspendin, because I'm trying to avoid coroutines dependency whenever possible. So if you like to use remote service you will have to run some coroutines scope:
```
typeahead(
  label = "Customers",
  source = { search, callback ->
     GlobalScope.launch {
         CustomerService.searchByEmail(search) { customers ->
            val processedData = customers.map { it.email }.toTypedArray() 
             callback(processedData)
         }
     }
  }
)
```
2. Unfortunately it's possible only for `Typeahead` component and not for `Select`. The Bootstrap Select component does not support dynamic data sources other than those supported by the [AJAX](https://github.com/truckingsim/Ajax-Bootstrap-Select) extension.

**Comment by eugenio1590** [comment]
Hi @rjaros that would be great. I'll be waiting for the next version. Thanks.

**Comment by rjaros** [comment]
Added in 3.14.0.

**Comment by eugenio1590** [comment]
Hi @rjaros 

Thanks for the update. But I am getting the following issue:

`Uncaught TypeError: typeahead is not a function`

I tried using the `Typeahead` component instead, like this:

````
add(
    Typeahead(
        label = "Customers",
        source = { _,_ -> emptyArray<String>() }
    )
)
````

This worked for me. But the `source` method is never called and I couldn't see the label component.

**Comment by rjaros** [comment]
This is working for me without problems:
```
package com.example

import pl.treksoft.kvision.Application
import pl.treksoft.kvision.form.text.typeahead
import pl.treksoft.kvision.panel.root
import pl.treksoft.kvision.startApplication

class App : Application() {
    override fun start() {
        root("kvapp") {
            typeahead(
                label = "Customers",
                source = { search, callback ->
                    callback(arrayOf(search, search + search, search + search + search))
                }
            )
        }
    }
}

fun main() {
    startApplication(::App)
}
```

**Comment by eugenio1590** [comment]
> This is working for me without problems:
> 
> ```
> package com.example
> 
> import pl.treksoft.kvision.Application
> import pl.treksoft.kvision.form.text.typeahead
> import pl.treksoft.kvision.panel.root
> import pl.treksoft.kvision.startApplication
> 
> class App : Application() {
>     override fun start() {
>         root("kvapp") {
>             typeahead(
>                 label = "Customers",
>                 source = { search, callback ->
>                     callback(arrayOf(search, search + search, search + search + search))
>                 }
>             )
>         }
>     }
> }
> 
> fun main() {
>     startApplication(::App)
> }
> ```

This example is not worked for me. I get the same issue. But I have noticed the following message on the console when I updated the KVision version:

> Task :rootPackageJson
There are multiple versions of "kotlin" used in nodejs build: 1.4.0, 1.4.10. Only latest version will be used.

This message does not appear with the version "3.13.1".

**Comment by rjaros** [comment]
You should also update `systemProp.kotlinVersion=1.4.10` in `gradle.properties`.

Is your project open source? Can you share the sources?

The above example is working with the current template project, you just need to add `bootstrap-typeahead` module to the dependencies in the `build.gradle.kts` file. If you can't share the project sources, you will need to carefully compare your build configuration and the content of `webpack.config.d` directory with the current example projects. Perhaps you have some old configuration.

**Comment by eugenio1590** [comment]
Ok, I updated the Kotlin version and the message disappeared. But I am still getting _"Uncaught TypeError: typeahead is not a function"_.

I'm sorry. But my project is not open source. If you have an example project with that versions of Kotlin and KVision, that can be helped me to check the configuration.

Kotlin: 3.13.
KVision: 3.14.0.

Thanks for your help.

**Comment by rjaros** [comment]
Look at this project https://github.com/rjaros/typeahead

**Comment by eugenio1590** [comment]
> Look at this project https://github.com/rjaros/typeahead

I replaced the _gradle_ folder in my project and the issue was resolved. 
Thanks for your help.
