### ISSUE TITLE
in showcase example tables sample breaks whole app under IE 11

### ISSUE THREAD

**Issue by mgrouch** [rjaros/kvision#188]
in showcase example tables sample breaks whole app under IE 11

See https://rjaros.github.io/kvision-examples/showcase/#!/tabulator
under IE 11

Thanks

**Comment by rjaros** [comment]
KVision has limited support for IE11. You can use polyfill in your application to make most of the things work in a usable way.
Try adding this line to your `index.html` before `main.bunde.js` 
```
<script src="https://polyfill.io/v3/polyfill.min.js?features=Promise%2CCustomEvent"></script>
```
I'll add this to the showcase example as well.
