### ISSUE TITLE
Update chart data

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#19]
In Chart.js, I can update the chart like this, how would I access these methods in KVision?
```
chart.data.labels.push(label);
chart.data.datasets.forEach((dataset) => { 
    dataset.data.push(data);
});
chart.update();
```
Specifically, I am trying to bind the chart state to an observable list of data but I'm not sure if Chart.js can handle observables so I can just update the chart manually if there is a way to do so.

**Comment by robert-cronin** [comment]
Just realised I can do it with DataContainer! I originally thought it would be different since it's an external library

**Comment by robert-cronin** [comment]
well I guess my question now is what would be the unit subview to go in the Data Container. I have my chart as the container view, but then when I define a chart configuration inside the Data Container, it throws an error.

**Comment by rjaros** [comment]
KVision `Chart` component has a `configuration` property. It's initialized in the constructor and it is a read/write property. Just set different configuration and the chart will get updated. There is no need to use DataContainer.
