### ISSUE TITLE
How can I add kvison to exisitng gradle project?

### ISSUE THREAD

**Issue by lUNuXl** [rjaros/kvision#190]
Hello,

The examples repository is really useful however it doesn't cover any case where there's existing code in some gradle module, written in Groovy/Java/Scala and Kvision is just for frontend in a separate module.

How does one add kvision as a module to existing project?

**Comment by rjaros** [comment]
Hi and thanks for your feedback.

The answer to your question depends whether you are talking about multimodule gradle project or multiplatform project. In the first case, you should be able to just copy kvision template project as a submodule. In the latter case, you will need to modify current project, taking any of the fullstack templates as an example. In any case, it shouldn't be much harder then adding any other module to the existing project. Take a look at the `mini-template` example - you will see KVision can work with almost empty, default gradle configuration.
Do you have any specific project in mind? Have you tried and encountered any problems?

**Comment by lUNuXl** [comment]
I'm talking about multi module, as soon as I include the module with kvision even the clean task fails:

```
toaster@larry ~/git/KvisionTest $ gradle clean

FAILURE: Build failed with an exception.

* Where:
Build file '/home/larry/git/KvisionTest/frontend/build.gradle.kts' line: 87

* What went wrong:
Check failed.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 511ms
toaster@larry ~/git/KvisionTest $ 
```
[KvisionTest.zip](https://github.com/rjaros/kvision/files/5360847/KvisionTest.zip)

**Comment by rjaros** [comment]
You need to adjust some paths in your configuration. I've made some small changes in two files:
`frontend/buid.gradle.kts`
`frontend/webpack.config.d/webpack.js`

Check the attachment.
[changed.zip](https://github.com/rjaros/kvision/files/5360962/changed.zip)
