### ISSUE TITLE
support kotlin IR

### ISSUE THREAD

**Issue by SchweinchenFuntik** [rjaros/kvision#192]
a new `IR` was released in Kotlin 1.4, and there is a mode - `BOTH`, especially for libraries.
https://kotlinlang.org/docs/reference/js-ir-compiler.html

According to reviews, reduces the final size of the application.

**Comment by rjaros** [comment]
With current IR compiler backend KVision applications are lot larger than with the legacy version, so there is no sense building with IR for now. We are waiting for https://youtrack.jetbrains.com/issue/KT-41227 and https://youtrack.jetbrains.com/issue/KT-39740 to be fixed. It should be released with 1.4.30.

**Comment by mpetuska** [comment]
It would be nice to have KVision published with BOTH mode regards to allow for lib consumers to experiment with IR

Regards,

Martynas Petuška

________________________________

**Comment by rjaros** [comment]
There are some additional issues with BOTH mode. But I'll try to release such version soon (I'm waiting for Spring Boot 2.4.0 to be able to also upgrade coroutines to 1.4.0).

**Comment by altavir** [comment]
It would be nice to have IR artifact anyway. I wanted to finally try KVision, but I can't since we do not support Legacy mode. Size is not important for me right now.
