### ISSUE TITLE
Site's and examples' layout display bug on 

### ISSUE THREAD

**Issue by y9san9** [rjaros/kvision#194]
![Screenshot_20201118_213402_com android chrome](https://user-images.githubusercontent.com/46930374/99572493-cd16b880-29e5-11eb-85be-c221e73c0736.jpg)
![Screenshot_20201118_213439_com android chrome](https://user-images.githubusercontent.com/46930374/99572639-04856500-29e6-11eb-9b83-4733045815ff.jpg)

Please do something with it, because it demonstrates how library works

**Comment by rjaros** [comment]
Thanks for your feedback!

I've fixed the site and the showcase example a bit as well, although I can't do much about the example because it's just not designed for mobile view :-)

**Comment by y9san9** [comment]
Yeah, I've thought about that it's just not designer for mobile, but anyway now it looks better, ty for fix :)
