### ISSUE TITLE
Percent does not work correctly in css properties.

### ISSUE THREAD

**Issue by rahimklaber** [rjaros/kvision#195]
I'm having the same problem described in #82 and #20 . Every component gets rendered in another div, which results in setting width, height etc. with percent not possible ( It's possible but it doesn't work correctly). 

I read #82 and #20 but it didn't address the problem.

## Example

```kotlin
class App : Application() {

    override fun start(state: Map<String, Any>) {
        root("kvapp") {
            style{
                width = 100.vw
                height = 100.vh
            }
            hPanel {
                style {
                    width = 100.perc
                    height = 100.perc
                    background = Background(Color.name(Col.RED))
                }
                button("hi")
            }
        }
    }

    override fun dispose(): Map<String, Any> {
        return mapOf()
    }

}
```

Running the above application will produce this: 
![image](https://user-images.githubusercontent.com/21971137/99887485-17e23b80-2c45-11eb-83fb-695921474517.png)

Changing the hPanel style and button style to:
```kotlin
            hPanel {
                style {
                    width = 100.vw
                    height = 100.vh
                    background = Background(Color.name(Col.RED))
                }
                button("hi"){
                    style{
                        marginTop = 50.perc
                    }
                }
            }
```
results in:
![image](https://user-images.githubusercontent.com/21971137/99887553-9212c000-2c45-11eb-8c8c-4f4f2ba43da0.png)

**Comment by rjaros** [comment]
Hello and thanks for your feedback :)

Since KVision 3.13.0 `FlexPanel`, `VPanel`, `HPanel` and `GridPanel` containers have additional parameter `noWrappers` (default `false`). You can set its value to `true` and those additional div wrappers won't be used. Percentage units will work better. Like this:
```
hPanel(noWrappers = true) {
                style {
                    width = 100.vw
                    height = 100.vh
                    background = Background(Color.name(Col.RED))
                }
                button("hi"){
                    style{
                        marginTop = 50.perc
                    }
                }
            }
```

And by the way. those `style` functions are not necessary in your code. It's easier to write:
```
hPanel(noWrappers = true) {
                width = 100.vw
                height = 100.vh
                background = Background(Color.name(Col.RED))
                button("hi"){
                    marginTop = 50.perc
                }
            }
```

**Comment by rahimklaber** [comment]
Wow, that was fast. Thanks for the help!

**Comment by rjaros** [comment]
One more thing - in this case, the `style` function can indeed be useful within the `Button` component. Because with `noWrappers` set to true, hPanel will automatically reset margins on its children components. Setting margin within `style` will workaround this problem.

**Comment by rjaros** [comment]
I'll fix this because it looks like a bug for me.
