### ISSUE TITLE
KVision adds a row div between Root and initial specified container

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#20]
I am trying to stretch my containers vertically to fill available space. To give you an example:
```
root = Root("kvapp") {
    width = 100.perc
    height = 100.perc
    vPanel {
        background = Background(Col.RED)
        width = 100.perc
        height = 100.perc
        label("Label") {  }
    }
}
```
When I run the app however, it appears there is an extra container being inserted between the Root and first divs which I can't access:
![Screen Shot 2019-03-19 at 1 37 55 pm](https://user-images.githubusercontent.com/8540764/54582581-42312e00-4a4c-11e9-8a26-bf4d08a711dd.png)

**Comment by rjaros** [comment]
try using 
```
vPanel(alignItems = FlexAlignItems.STRETCH) {
    // ...
}
```

**Comment by robert-cronin** [comment]
I still get the same result, I also had some trouble defining height = 100% on normal CSS. Unless you know of another way to get the root container to stretch to the current window height, I might just set a default height to begin with.

**Comment by rjaros** [comment]
I didn't notice the "vertically" word at first.
You can't really use height specified as "100%" in HTML/CSS, because "percent" means always the size relative to the parent. But you can use "vw" and "vh" units. This should do the trick:
```
import pl.treksoft.kvision.utils.vh
import pl.treksoft.kvision.utils.vw

// ...
        root = Root("kvapp") {
            vPanel {
                width = 100.vw
                height = 100.vh
                background = Background(Col.RED)
                label("Label") {  }
            }
        }
```

**Comment by robert-cronin** [comment]
yeah that's exactly what I was after, thanks!
