### ISSUE TITLE
flexBasis should accept CSSSize

### ISSUE THREAD

**Issue by lorefnon** [rjaros/kvision#202]
In StyledComponent flexBasis [accepts Int](https://github.com/rjaros/kvision/blob/352893817b1aa9c7d88f1721c413efdc2d8dac3d/src/main/kotlin/pl/treksoft/kvision/core/StyledComponent.kt#L399) but ideally it should accept CSSSize so that we can set flex-basis in other units.

---

BTW, thanks a lot for this library. I have been experimenting with it for a few days and it has been a really pleasant experience.

**Comment by rjaros** [comment]
Thanks for your feedback :-)
Even though it's a kind of breaking change, I'll just fix this with your PR, because it was an obvious bug (I've copied type from `flexShrink` property instead of making it right).

**Comment by lorefnon** [comment]
Thank you :)
