### ISSUE TITLE
Tabulator's deselectRow() and selectRow() have a no-arg call that is not supported on KVision

### ISSUE THREAD

**Issue by MikiLoz92** [rjaros/kvision#204]
According to [the Tabulator docs](http://tabulator.info/docs/4.9/select), if you don't pass any arguments to the `selectRow()` and `deselectRow()` functions, Tabulator will respectively select and deselect all rows in the table.

I couldn't see any way to replicate such behavior with the KVision bindings, since they require an Int parameter, at the very least.

**Comment by rjaros** [comment]
It's a bug. We should be able to call those functions with a lot of different parameter values, not just `Int`.
As a temporary workaround you can use `tabulator.jsTabulator?.selectRow(undefined)` (it takes a `dynamic` parameter).

**Comment by MikiLoz92** [comment]
Great, thanks for the tip!

**Comment by rjaros** [comment]
Fixed in 3.18.0
