### ISSUE TITLE
Click on TabPanel's tab always navigates to "/#" if route is set to null

### ISSUE THREAD

**Issue by MikiLoz92** [rjaros/kvision#214]
When using `TabPanel`, I have noticed that Tabs that are being added always navigate to route `/#` when clicked, if their `route` parameter is left as null when constructed (by default).

Is this intended behaviour?

Thanks,
Miguel

**Comment by rjaros** [comment]
No, it's not.
And I can't reproduce such behavior. Could you please provide some example code you are using?

**Comment by MikiLoz92** [comment]
I'm creating a TabPanel and its tabs like this:
```kotlin
tabPanel = tabPanel(TabPosition.TOP, SideTabSize.SIZE_4) {
                tab(tr("Status"), icon = "fas fa-compass") {
                    flexPanel(FlexDirection.ROW, FlexWrap.NOWRAP, JustifyContent.STRETCH, AlignItems.STRETCH) {
                        paddingLeft = 20.px
                        paddingRight = 20.px
                        paddingTop = 20.px
                        paddingBottom = 20.px
                        style {
                            border = Border(1.px, BorderStyle.SOLID, Color.hex(0xdddddd))
                            borderTop = Border(0.px, BorderStyle.SOLID)
                        }
                        options(basis = 50.perc, grow = 0) {
                            add(vehicleStatusText)
                        }
                        options(basis = 50.perc, grow = 0) {
                            div {
                                width = 100.perc
                                add(mapIFrame)
                            }
                        }
                    }
                }
                reportsTab = tab(tr("Reports"), icon = "fas fa-wave-square") {
                    reportsTabContainer = vPanel {
                        style {
                            border = Border(1.px, BorderStyle.SOLID, Color.hex(0xdddddd))
                            borderTop = Border(0.px, BorderStyle.SOLID)
                        }
                        paddingLeft = 20.px
                        paddingRight = 20.px
                        paddingBottom = 20.px
                        flexPanel(direction = FlexDirection.ROW,
                                  wrap = FlexWrap.WRAP,
                                  justify = JustifyContent.FLEXSTART,
                                  alignItems = AlignItems.CENTER,
                                  spacing = 5) {
                            add(reportsStartDatetimeField)
                            add(reportsEndDatetimeField)
                            add(reportsTableConfigButton)
                            button("", icon = "fas fa-play", style = ButtonStyle.SUCCESS) {
                                marginTop = 4.px
                                onClick {
                                    rebuildReportsTable()
                                }
                            }
                        }
                    }
                }
```

It appears to be caused by the inner `<a>` tag that is created when a tab component is created (there is a `#` set as link):

![image](https://user-images.githubusercontent.com/786375/103300435-c3c23800-49f6-11eb-846a-3b6a7c35b5e2.png)

**Comment by rjaros** [comment]
Perhaps it's a browser compatibility problem? What browser do you use?

**Comment by rjaros** [comment]
In the source code I see there is `click` event handler on the `LI` element, which calls `preventDefault()`. For me (both Chrome/Firefox on Linux) it prevents `<a>` from being activated by the click. But perhaps it's different for you.

**Comment by MikiLoz92** [comment]
I've tried in Opera, Firefox and Safari and in all of them it's going to `#` either way. It's like it's ignoring the `<li>` element and jumping straight to the `<a>` when clicking... it's weird, I'll keep trying stuff, see if I can come up with something else and let you know! thanks for the feedback ;)

**Comment by rjaros** [comment]
Could you please check what kind of event listeners do you see for the `a` element in the `Event Listeners` tab in DevTools:
For me it looks like here:
![screenshot-kv](https://user-images.githubusercontent.com/5646804/103305182-bd3dbb80-4a0a-11eb-819b-ba857779e3b4.png)

**Comment by MikiLoz92** [comment]
![image](https://user-images.githubusercontent.com/786375/103439280-5a7b3880-4c33-11eb-99c0-df17bca8f534.png)

You got it right with that: good news is, as soon as I manually remove the `Window` listener, everything starts working as you described should work. Seems to be a weird interaction with the zenscroll JS library... I'll take a look at it.

Sorry for the false positive here, I'm a backend guy, not used to debug browser issues 😬... In any case, thanks for your help!!
