### ISSUE TITLE
Color.hex has incorrect math

### ISSUE THREAD

**Issue by reubenfirmin** [rjaros/kvision#215]
For example, Color.hex(222222) produces "03640e", a shade of green.

**Comment by rjaros** [comment]
It should be used with a hexadecimal literal: 
```
Color.hex(0x222222)
```
See: https://kvision.gitbook.io/kvision-guide/part-1-fundamentals/css-properties#colors

**Comment by reubenfirmin** [comment]
Got it. Thanks.
