### ISSUE TITLE
Custom header filter function on Tabulator

### ISSUE THREAD

**Issue by MikiLoz92** [rjaros/kvision#216]
Filling a feature request for custom header filter functions: 

According to [this](https://github.com/olifolkerd/tabulator/issues/527) Tabulator GitHub issue and the [official docs](http://tabulator.info/docs/4.9/filter#header) (under `Filter Comparison Types` section), one can pass a function to the `headerFilterFunc` param when constructing a column, and that function will be called to filter rows.

However, the same behaviour, cannot be replicated at the moment in KVision since the `headerFilterFunc` param expects a value of type `Filter`, which is an enum class.

**Comment by rjaros** [comment]
I've added additional `headerFilterFuncCustom` parameter, which will be used if defined. `headerFilterFunc` with typesafe enum values will be used as before, if custom parameter is not set.

**Comment by rjaros** [comment]
Released in 3.19.1
Sorry for the delay, but I had to work a bit for living  ;-)
