### ISSUE TITLE
Request - support focus() function on Tag

### ISSUE THREAD

**Issue by reubenfirmin** [rjaros/kvision#217]
[](url)
![2021-01-22_10-21](https://user-images.githubusercontent.com/14217993/105520676-9d638580-5ca0-11eb-8518-e4c9be293bd3.png)

Please consider adding support for focus() directly on Tag. Right now it's tough to find in the class hierarchy unless you know where to look.

**Comment by rjaros** [comment]
Released with 4.0.0
