### ISSUE TITLE
Running project errors about webpack loaders

### ISSUE THREAD

**Issue by 89jd** [rjaros/kvision#219]
```
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @charset "UTF-8";
| .abc-checkbox {
|   cursor: default;
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> .text-justify  { text-align: justify !important; }
| .text-left   { text-align: left !important; }
| .text-right  { text-align: right !important; }
Module parse failed: Unexpected token (6:3)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  * Copyright 2011-2021 Twitter, Inc.
|  * Licensed under MIT (https://github.com/twbs/bootstrap/blob/main/LICENSE)
```

I get the following errors, when trying to launch a simple project. I just want to use it for frontend, can you advise? Happy to give any more information needed

```
class App: Application() {
    override fun start() {
        root("app") {
            vPanel {
                h1("hi")
            }
        }
    }
}
```

**Comment by rjaros** [comment]
Hello,

Have you created your project from scratch or have you started with a [template](https://github.com/rjaros/kvision-examples/tree/master/template) or [kvision-project-wizard](https://github.com/JakubNeukirch/kvision-project-wizard)? 

The log suggests you don't have css webpack loader configured. Make sure you have at least those files in your `webpack.config.d` directory:
https://github.com/rjaros/kvision-examples/tree/master/mini-template/webpack.config.d

**Comment by 89jd** [comment]
I have an existing multiplatform project that I added the project too. I followed the getting started guide but maybe I missed a step

**Comment by 89jd** [comment]
That did it, cheers!
