### ISSUE TITLE
node: Permission denied when building kvision project

### ISSUE THREAD

**Issue by tyrel** [rjaros/kvision#220]
I'm building a KVision+Micronaut project on Linux and running into an error during my Gradle build, starting with no gradle cache:
```shell
> Task :kotlinNpmInstall
...
error /home/tyrel/devel/northpass/build/js/node_modules/core-js: Command failed.
Exit code: 127
Command: node -e "try{require('./postinstall')}catch(e){}"
Arguments: 
Directory: /home/tyrel/devel/northpass/build/js/node_modules/core-js
Output:
/bin/sh: 1: node: not found
```
If I try to run in a second time, I get nearly the exact same error except it says "Permission denied" instead of "not found". That error then continues.

Here are some potentially relevant portions of my gradle file, which are copied from various kvision samples:
```kotlin
     val frontendMain by getting {
        resources.srcDir(webDir)
        dependencies {
            implementation(kotlin("stdlib-js"))
            implementation("pl.treksoft:kvision:$kvisionVersion")
            implementation("pl.treksoft:kvision-fontawesome:$kvisionVersion")
            implementation("pl.treksoft:kvision-i18n:$kvisionVersion")
            implementation("pl.treksoft:kvision-onsenui:$kvisionVersion")
            implementation("pl.treksoft:kvision-onsenui-css:$kvisionVersion")
        }
        kotlin.srcDir("build/generated-src/frontend")
    }
```

```kotlin
fun getNodeJsBinaryExecutable(): String {
    val nodeDir = NodeJsRootPlugin.apply(project).nodeJsSetupTaskProvider.get().destination
    val isWindows = System.getProperty("os.name").toLowerCase().contains("windows")
    val nodeBinDir = if (isWindows) nodeDir else nodeDir.resolve("bin")
    val command = NodeJsRootPlugin.apply(project).nodeCommand
    val finalCommand = if (isWindows && command == "node") "node.exe" else command
    return nodeBinDir.resolve(finalCommand).absolutePath
}
```

Any suggestions on finding our more about the problem here?

**Comment by rjaros** [comment]
Can you check if gradle downloaded node binaries into your $HOME/.gradle/nodejs/node-v12.16.1-linux-x64 directory?
What gradle task do you execute? Can you post the whole log from a clean build?

**Comment by tyrel** [comment]
Yep, node exists in that path, and I can run it manually. 
```
$ ~/.gradle/nodejs/node-v12.16.1-linux-x64/bin/node --version
v12.16.1
```
I'm not familiar with node at all but I notice it can pick up the env var NODE_DEBUG with a list of modules to print debug information. If you know what modules I might put there to get more info, I could try that.

Here's an entire log run with `./gradlew build --info`: https://gist.github.com/tyrel/c45ef12868e2628cea5599f934e7f154

Given that the command that seems to be failing is `try{require('./postinstall')}catch(e){}`, it made me wonder if `./postinstall` is what's actually throwing `Permission denied`. There is a `build/js/node_modules/core-js/postinstall.js`, which is what I assume this is referring to, but that file has global read access so I'm not sure why it would give `Permission denied`.

**Comment by tyrel** [comment]
I noticed in the log that it prints the whole command and working directory, and see that it's while yarn is running. I then ran it with --verbose to see if I could get more detail.
```shell
[4/4] Building fresh packages...
⠁ 
6.334851989 Error: /home/tyrel/devel/northpass/build/js/node_modules/core-js: Command failed.
Exit code: 126
Command: node -e "try{require('./postinstall')}catch(e){}"
Arguments: 
Directory: /home/tyrel/devel/northpass/build/js/node_modules/core-js
Output:
/bin/sh: 1: node: Permission denied
    at ProcessTermError.ExtendableBuiltin (/home/tyrel/.gradle/yarn/yarn-v1.22.4/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/home/tyrel/.gradle/yarn/yarn-v1.22.4/lib/cli.js:750:123)
    at new ProcessTermError (/home/tyrel/.gradle/yarn/yarn-v1.22.4/lib/cli.js:790:113)
    at ChildProcess.<anonymous> (/home/tyrel/.gradle/yarn/yarn-v1.22.4/lib/cli.js:25884:17)
    at ChildProcess.emit (events.js:311:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:311:20)
    at Pipe.<anonymous> (net.js:668:12)
error /home/tyrel/devel/northpass/build/js/node_modules/core-js: Command failed.
Exit code: 126
Command: node -e "try{require('./postinstall')}catch(e){}"
Arguments: 
Directory: /home/tyrel/devel/northpass/build/js/node_modules/core-js
Output:
/bin/sh: 1: node: Permission denied

6.36516717 Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
```
I don't know if that helps very much. It looks like yarn is trying to start another instance of node in order to run `postinstall` and that's getting Permission denied? But I don't know why.

**Comment by rjaros** [comment]
Is your project open source? Could you share it?

**Comment by rjaros** [comment]
I've found some similar issues in Google - e.g. https://forum.vuejs.org/t/cannot-install-vue-cli-permission-error-in-require-postinstall/82017/3, which suggest you could be running your build process as root? Is it your case perhaps?

**Comment by tyrel** [comment]
No, it is not open source. I also found results like that from Googling but so far none have been helpful. I'm not running node as root and I never have -- node actually isn't installed in the PATH on this machine, it's only in the gradle registry created by this build (and I removed it prior to the log I attached earlier -- that was a fresh "install" of node).

There have been mentions in some of the results of logs that show up in `/root/.npm/_logs/` but I have no `.npm` directory anywhere that I can find (and certainly not under `/root/). 

I also don't see these `npm ERR!` lines that seem to appear in others' output,

I realized I forgot to mention that this _was_ working fine two days ago, but stopped working yesterday. In that time I switched from using Bootstrap to Onsen, and a couple other changes. I could try rolling back to an older commit and see if I can find what change the failure started happening in, although my change from Bootstrap to Onsen was one big commit so I may not be able to narrow it down much.

**Comment by tyrel** [comment]
Yes, if I roll back to before switching from Bootstrap to Onsen, the failure goes away. So it's related to those changes. I'll see if I can narrow it down.

**Comment by tyrel** [comment]
It's definitely this dependency causing the issue:
```kotlin
implementation("pl.treksoft:kvision-onsenui:$kvisionVersion")
```
If I comment it out, the build gets past this task (but fails later because of unresolved symbols, as expected).
If I uncomment it, the build then fails at this task again.

**Comment by rjaros** [comment]
Could you post your `build/js/yarn.lock` file?

**Comment by rjaros** [comment]
Is there any reason you are not using latest KVision?

**Comment by tyrel** [comment]
Oh, right, `kvisionVersion` is set to 3.17.2. I don't know why I didn't check that first.
I think I got that from the kvision-project-wizard. https://github.com/JakubNeukirch/kvision-project-wizard/blob/3dc89fadc4d39a19c2d5cb494f0c4aee8e49f4d1/src/main/kotlin/tech/stonks/kvizard/generator/TreeGenerator.kt#L247

I upgraded to KVision 3.19.1 and I get the same error.

There is no file at `build/js/yarn.lock`
```shell
$ ls -l
total 32
drwxrwxr-x 516 tyrel tyrel 20480 Jan 29 15:08 node_modules/
-rw-rw-r--   1 tyrel tyrel   314 Jan 29 15:08 package.json
drwxrwxr-x   4 tyrel tyrel  4096 Jan 29 15:08 packages/
drwxrwxr-x  21 tyrel tyrel  4096 Jan 29 15:08 packages_imported/
```
There are a few `yarn.lock` files scattered around `node_modules` but I assume those aren't relevant.

**Comment by rjaros** [comment]
I think I know.
Could you please create a fake "node" binary in your PATH (e.g. /usr/local/bin/node"). It can be empty executable file. I think it will help.

**Comment by rjaros** [comment]
I'm almost sure the problem is `core-js` npm dependency, which is required by OnsenUI. It has this `postinstall` section in `package.json`:

`"postinstall": "node -e \"try{require('./postinstall')}catch(e){}\""`

There is no node in your system, so it fails. I have node installed, so it never failed for me. If i remove my `node` binary it fails for me with almost the same message.

**Comment by rjaros** [comment]
They have even an open issue for this:
https://github.com/zloirock/core-js/issues/843

**Comment by tyrel** [comment]
Yes, that's it! I created an empty, executable `/usr/local/bin/node` and got past that error. Thank you!

**Comment by rjaros** [comment]
Great! I'm glad I could help :-)
