### ISSUE TITLE
How to start project from production-zip?

### ISSUE THREAD

**Issue by fpue** [rjaros/kvision#222]
Hey,
I'm loving this project so far. I'm relatively new programmer so this question may be a bit dumb.
I'm trying to get tmy project running in an production like environment and zipped id it like its explained here: https://kvision.gitbook.io/kvision-guide/part-1-fundamentals/setting-up 
But what comes next, how do I start the project inside the zip-file?
Thanks in advance!

**Comment by rjaros** [comment]
The zipped package is just for easy transfer :-)
Unzip the file at your hosting server.

**Comment by fpue** [comment]
Thank you for your fast answer!
My question was probably a bit unclear. I already did that, but I'm unsure how to procede. Do I start the project with node? Or somehow with npm?

**Comment by rjaros** [comment]
KVision apps are static websites. Just open `index.html` in your browser. Preferably upload all the files to a web server.

**Comment by fpue** [comment]
Ah I tried that, now after you confirmed my first instinct, I found why it did not work for me:
The script the `index.html` refered to was `main.bundle.js`, for a reason unknown to me in the zip _the script was named after my project_ and therefore the `index.html` couldn't run the script.

Thanks for your help!

**Comment by rjaros** [comment]
In Kotlin/JS the default name of the script is the project name. KVision template projects overwrite this with `outputFileName = "main.bundle.js"` option in `build.gradle.kts`. Perhaps you removed this option from your build.
