### ISSUE TITLE
Button that opens window will result in focus problems

### ISSUE THREAD

**Issue by jschneider** [rjaros/kvision#226]
I created a minimal example that contains one button that opens a new window:

```
    root("rootContainer") {
      button("button") {
        onClick {
          window("Window", 600.px, 300.px, closeButton = true,
                 maximizeButton = true, minimizeButton = true, icon = "fas fa-edit") {
            left = ((Random.nextDouble() * 800).toInt()).px
            top = ((Random.nextDouble() * 300).toInt()).px
            span("A window content")
          }
        }
      }
    }
```

Clicking on the button opens the window (as expected). But every subsequent click will open a new window - even if clicked on the close button.
I assume this is some kind of focus problem?

The mouse over effect of the button is triggered, if the mouse is moved over the newly opened window

**Comment by rjaros** [comment]
In your code you are creating a window object with a DSL builder function `window`, thereby adding it as a child component of the button. That's why a click inside the window is at the same time a click of the button. The best way to fix this is to add newly created `Window` object to the root container, like this:
```
            button("button") {
                onClick {
                    this@root.add(Window(
                        "Window", 600.px, 300.px, closeButton = true,
                        maximizeButton = true, minimizeButton = true, icon = "fas fa-edit"
                    ) {
                        left = ((Random.nextDouble() * 800).toInt()).px
                        top = ((Random.nextDouble() * 300).toInt()).px
                        span("A window content")
                    })
                }
            }
```
