### ISSUE TITLE
Button: Tooltip doesn't fade when button is clicked

### ISSUE THREAD

**Issue by jschneider** [rjaros/kvision#227]
1. Hover over button - wait until tooltip is shown
2. click on the button

Expected: Tooltip is closed 
Actual: Tooltip is always shown (never hidden anymore)

```
      root("rootContainer") {
      button("button") {
        title = "da tooltip"
        enableTooltip()
      }
    }
```

**Comment by rjaros** [comment]
This is a Bootstrap issue. You can check here: https://getbootstrap.com/docs/4.6/components/tooltips/#examples it works the same with plain Bootstrap. Of course you can easily get your expected behavior with:
```
            button("button") {
                title = "da tooltip"
                enableTooltip()
                onClick {
                    this.hideTooltip()
                }
            }
```
