### ISSUE TITLE
"-Xir-property-lazy-initialization" seems to be not supported

### ISSUE THREAD

**Issue by jschneider** [rjaros/kvision#231]
I created a sample project:

https://github.com/jschneider/kvision-minimal-multi-module-project

In the build.gradle.kts (https://github.com/jschneider/kvision-minimal-multi-module-project/blob/master/build.gradle.kts) the kotlin plugin is configured to enable "ir-property-lazy-initialization"

Steps to reproduce:
* `cd kvision`
* `gradle run`

Open the browser: The CSS file is not loaded correctly.
Removing the parameter from the build.gradle.kts solves this issue.

**Comment by rjaros** [comment]
The automatic css loading is based on eager component loading. This new option is not supported for now.

**Comment by rjaros** [comment]
With KVision 5 introducing explicit modules initialization, this should work now.
