### ISSUE TITLE
Improve Routing

### ISSUE THREAD

**Issue by kormik** [rjaros/kvision#232]
I've couple of ideas for improve routing in KVision. we are facing these issues:

- It is not possible to configure router, because the instance is created in KVision and constructor parameters are hard coded. We would like to set `root` and `hash` parameters.
- In complex UI structure with nested StackPanels and TabPanels and we need to activate all appropriate components in the hierarchy up to the Root component on navigate. 
- When the component handle multiple routes it's more convenient to register them inside the component and set the route base(prefix) from outside.
- Navigo 8, has some nice features (e.g matching multiple routes)

We have a custom functions for most of it, but I think it would be useful to have them in KVision.

It would help moving routing into own module, after that we can introduce a new module with new version of Navigo and these features. It seems is should not be that hard and usages of router(StackPanel, TabPanel) can be hide behind the interface (technically it only needs methods `on` and `off`)

What do you think?

**Comment by rjaros** [comment]
I've decided to move routing to a separate module in 4.1.0. Apart from adding new module dependency, one other change is required for all projects using built-in routing - a call to `Routing.init()` at the beginning of `start()` method. Optional parameters of `init()` allow to fully configure Navigo instance.

The `kvision-routing-navigo` module is compatible with current version and is based on Navigo 7. 

New `kvision-routing-navigo-ng` module is based on Navigo 8 but is configured for hash based routing by default (a switch to new module is very easy unless some advanced API is used).

**Comment by rjaros** [comment]
Released with 4.1.0
