### ISSUE TITLE
Translation with parameters

### ISSUE THREAD

**Issue by jschneider** [rjaros/kvision#233]
I would like to translate this:

> "Your name is Robert" 

but "Robert" is only known at runtime. Therefore we need some kind of placeholder that are replaced at runtime.

**Comment by rjaros** [comment]
Will be supported in the next version. `gettext()` and `I18n.ngettext()` functions will accept additional parameters. I'll describe how to construct expressions with variables for both singular and plural translations in the guide.

**Comment by rjaros** [comment]
Released with 4.1.0
