### ISSUE TITLE
Sealed classes cannot be deserialised on JS side with new IR compiler

### ISSUE THREAD

**Issue by zypus** [rjaros/kvision#234]
I just tried upgrading my fullstack (ktor) project to kvision 4.0.0, however I ran into issues with the IR compiler. Apparently kotlinx.serialization 1.0.0 does not yet support finding the serializer for sealed classes: [https://github.com/Kotlin/kotlinx.serialization/issues/1116 ](https://github.com/Kotlin/kotlinx.serialization/issues/1116)

ie. something like this in the common module:

```
@Serializable
sealed class FirmwareLogResponse {
    @Serializable
    object Clear: FirmwareLogResponse()
    @Serializable
    data class InitLog(val logLines: List<LogLine>): FirmwareLogResponse()
    @Serializable
    data class UpdateLog(val logLine: LogLine): FirmwareLogResponse()
    @Serializable
    object LogHeartBeat: FirmwareLogResponse()
}
```

**So this is no direct issue of kvision, but I put this here to be aware of this issue.** 

It works fine when I use the legacy compiler on the js side.

`kotlin.js.compiler=legacy`

**Comment by rjaros** [comment]
Thanks for the information! 
I've added this note to KVision documentation as well.

**Comment by zypus** [comment]
Thanks I have seen the entry.
Might be worth mentioning in the migration guide as well.

**Comment by rjaros** [comment]
Should be fixed now
