### ISSUE TITLE
Can't use custom bootstrap

### ISSUE THREAD

**Issue by baillyjamy** [rjaros/kvision#235]
Hello, I can't use a custom bootstrap. A style tag with a default Bootstrap v4.6.0 is always rendred after the stule tag of my custom bootstrap css file.
As said in the [documentation ](https://kvision.gitbook.io/kvision-guide/part-1-fundamentals/themes), I remove kvision-bootstrap-css from my dependencies but default Bootstrap is still here. I have two bootstrap imported but the default bootstrap override my custom file.

Here are my dependencies:
```kotlin
            implementation(project(":common"))
            implementation("io.kvision:kvision:$kvision_version")
            implementation("io.kvision:kvision-bootstrap:$kvision_version")
            implementation("io.kvision:kvision-bootstrap-datetime:$kvision_version")
            implementation("io.kvision:kvision-bootstrap-select:$kvision_version")
            implementation("io.kvision:kvision-bootstrap-spinner:$kvision_version")
            implementation("io.kvision:kvision-bootstrap-upload:$kvision_version")
            implementation("io.kvision:kvision-bootstrap-dialog:$kvision_version")
            implementation("io.kvision:kvision-fontawesome:$kvision_version")
            implementation("io.kvision:kvision-i18n:$kvision_version")
            implementation("io.kvision:kvision-richtext:$kvision_version")
            implementation("io.kvision:kvision-handlebars:$kvision_version")
            implementation("io.kvision:kvision-datacontainer:$kvision_version")
            implementation("io.kvision:kvision-redux:$kvision_version")
            implementation("io.kvision:kvision-chart:$kvision_version")
            implementation("io.kvision:kvision-tabulator:$kvision_version")
            implementation("io.kvision:kvision-pace:$kvision_version")
            implementation("io.kvision:kvision-moment:$kvision_version")
            implementation("io.kvision:kvision-toast:$kvision_version")
            implementation("io.kvision:kvision-print:$kvision_version")
            implementation("io.kvision:kvision-electron:$kvision_version")
            implementation(npm("sass", "^1.32.7"))
            implementation(npm("sass-loader", "^10.1.1"))
```

index.html:
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Mercuro</title>
    <link href="//fonts.googleapis.com/css?family=Titillium+Web:700|Source+Serif+Pro:400,700|Merriweather+Sans:400,700|Source+Sans+Pro:400,300,600,700,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="css/mybootstrap.min.css" >
    <!--    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.6.0/dist/litera/bootstrap.min.css" integrity="sha256-8Obip54rU+V9PyFohmXAD2VMVpBENHdnZtlsEmxGD/k=" crossorigin="anonymous">-->
    <!--    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/united/bootstrap.min.css" integrity="sha384-JW3PJkbqVWtBhuV/gsuyVVt3m/ecRJjwXC3gCXlTzZZV+zIEEl6AnryAriT7GWYm" crossorigin="anonymous">-->
    <script type="text/javascript" src="main.bundle.js"></script>
</head>
<body>
<div id="kvapp"></div>
</body>
</html>
```
As you can see, I tried to import custom bootstrap from bootstrapcdn and jsdelivr but I still have the default bootstrap that goes in the last tags so it override my custom bootstrap.
Do you know why the default bootstrap is always imported ?

**Comment by rjaros** [comment]
Have you tried cleaning your project after removing `bootstrap-css` module? We have just talked about similar issue yesterday on Slack (https://kotlinlang.slack.com/archives/CL4C1SLKC/p1613563683123400) and the problem was gone after running `clean`.

**Comment by baillyjamy** [comment]
Yes I did it and I did it again now to verify but nothing changes. I also remove my gradle caches folder in my home to be sure.

**Comment by rjaros** [comment]
Your dependencies look a bit unusual. Are you creating a multi-platform Electron application?

**Comment by baillyjamy** [comment]
This is a multi-module project, and this module uses electron yes. The common module allows me to share some data classes.

**Comment by rjaros** [comment]
Is your project open source? Can you share it?

**Comment by rjaros** [comment]
If you are using IR backend, perhaps you can send me the file `build/js/packages/$projectName/kotlin/$projectName.js`? Or just check if it contains `require('bootstrap/dist/css/bootstrap.min.css')`?

**Comment by baillyjamy** [comment]
Thank you windows. This was the mix between the windows file system and Windows Subsystem for Linux.
I exec `./gradlew module:run` on wsl and `clean` via Intellij. Build folder disappear from Intellij but still in my project if I do `ls -l`a on the wsl shell...
With a complete cleaning the default bootstrap is removed....
Sorry for the inconvenience

**Comment by rjaros** [comment]
No problem. I'm glad your problem is solved :-)
