### ISSUE TITLE
Allow Tags to be added as label for checkbox

### ISSUE THREAD

**Issue by reubenfirmin** [rjaros/kvision#236]
CheckBox has signature:

```
open class CheckBox(
    value: Boolean = false, name: String? = null, label: String? = null,
    rich: Boolean = false
) 
```

It renders the label as a private FieldLabel:
```
    final override val flabel: FieldLabel = FieldLabel(idc, label, rich, classes = setOf("form-check-label"))
```

Please allow a list of Tags to be designated as the label, rather than just a (potentially rich) string.

Thanks

**Comment by rjaros** [comment]
Hi,
Could you please explain your use case? Why would you like something else then `<label>`? The `<label>` HTML tag is designed for describing form controls and is required by WCAG specification for correct accessibility.

If you really don't want standard labels, you can just add another tag to your layout. Or you can use `CheckBoxInput`, which renders only the `input` element and doesn't have any label.

**Comment by reubenfirmin** [comment]
My checkbox labels end up as something like:

```
<label for...><span>some text</span> <a href="...">a link</a> <span>some more text</span></label>
```

Of course I can generate html and shovel that into the string if I really had to, but that seems counter to the framework's design.

**Comment by rjaros** [comment]
So I would say you need to access the label container.  I'll think about it.

**Comment by rjaros** [comment]
The `flabel: FieldLabel` property is not private at all. You can modify it's content using standard KVision methods, e.g.:
```kotlin
            checkBox {
                flabel.apply {
                    span("some text")
                    +" "
                    link("link", "http://...")
                    +" "
                    span("some more text")
                }
            }
```

**Comment by reubenfirmin** [comment]
You are correct - looks like I misread that. Is it worth exposing this in a more public API?

**Comment by rjaros** [comment]
I don't think so. Adding additional code (for consistency it would have to be added to all form controls) would only make the final bundle larger. And it won't let you do anything more than is already possible with direct access to `FieldLabel`.
