### ISSUE TITLE
V4 Defined field cannot be used

### ISSUE THREAD

**Issue by kabacinsp** [rjaros/kvision#237]
Version:
4.0.0 4.1.0

After updating from version 3.X.X to version 4.1.0, I get the following error in case I try to pass a value from a field.
**_'val anyValue: String' can't be called in this context by implicit receiver. Use the explicit one if necessary_**

Below I am sending a sample code which this error message occurs

```
class ExamplePanel : SimplePanel() {
  val anyValue = "value"

  init {
    main {
      label(anyValue)
    }
  }
}
```

I can ask for some way to solve this problem, I digged through the internet but didn't find much useful information

**Comment by rjaros** [comment]
Use explicit receiver with `this@ExamplePanel`:
```
class ExamplePanel : SimplePanel() {
    val anyValue = "value"

    init {
        main {
            label(this@ExamplePanel.anyValue)
        }
    }
}
```
It's because of `@DslMarker` annotations introduced in 4.1.0. It may look more verbose, but I think it's worth it. DSL constraints can really help detect bugs.

**Comment by rjaros** [comment]
And if you just need to extend a simple container (like `SimplePanel`) there is new `BasicPanel` class in 4.1.0, which is almost identical to `SimplePanel` but isn't annotated with `@DslMarker`. So you can just inherit from `BasicPanel` without receivers constraints:
```
class ExamplePanel : BasicPanel() {
    val anyValue = "value"

    init {
        main {
            label(anyValue)
        }
    }
}
```

**Comment by kabacinsp** [comment]
Both solutions work fine. Thank you!
