### ISSUE TITLE
jQuery unresolved reference

### ISSUE THREAD

**Issue by marcelorcorrea** [rjaros/kvision#239]
Hello!
It's not an issue actually, just a question.
I would like to understand how I can use jQuery to get an element from the dom. I tried what the documentation says:
https://kvision.gitbook.io/kvision-guide/part-1-fundamentals/jquery-bindings#jquery-object
But it didn't work.
My goal is to add a behavior to an element after a button click.
![image](https://user-images.githubusercontent.com/1151483/110171458-80ab8900-7dda-11eb-9da5-6cbb997756f8.png)

What am I doing wrong?
Thanks!

**Comment by rjaros** [comment]
You should use two imports:
```kotlin
import io.kvision.jquery.invoke
import io.kvision.jquery.jQuery
```
Unfortunately IntelliJ has problems with auto-imports and doesn't help with this.

**Comment by marcelorcorrea** [comment]
Awesome!
I'll try it out!
Thanks for the tip and the great framework ;-)
