### ISSUE TITLE
Gateway timeout on ktor full stack example

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#24]
I have a karma proxy.js on the client like the following:
```
var old = module.exports;

module.exports = function(config) {
    var temp = new Object();
    temp.set = function(c) {
	temp.conf = c;
    };
    var oldConfig = old(temp);
    temp.conf.proxies = {
	'/tmp/_karma_webpack_/': 'http://localhost:8088/'
    }
    config.set(temp.conf);
};
```
My server port is set to 8080 just like in the example, when I run the client and  the server it says webpack is already running, and throws an error on localhost:8088:
```
POST http://localhost:8088/kv/routeMongoDBServiceManager0 504 (Gateway Timeout)
```
I've tried changning ports but it just says webpack is still running on port 8088 and throws the gateway timeout error

**Comment by rjaros** [comment]
Are you using Windows or Linux?

**Comment by robert-cronin** [comment]
I'm actually on macOS Mojave so Unix, might be similar to Linux?

**Comment by rjaros** [comment]
Try the following (all commands should be run in the root directory of your fullstack project):
- Make sure all your gradle daemon instances are stopped (run: ./gradlew client:stop even a few times)
- Open first terminal window and run the client module: ./gradlew -t client:run
There should be no error about already used address/port in the console. If there is - repeat the first step once again.
- Open second terminal window  and run the server module: ./gradlew server:run
The ktor server should start without any errors, too.
- Open http://localhost:8088 in a browser

Let me know if it's working. If not - send some logs from both terminals.

**Comment by robert-cronin** [comment]
yeah those steps seemed to do the trick
