### ISSUE TITLE
readonly TextArea

### ISSUE THREAD

**Issue by scottmcconnell5** [rjaros/kvision#240]
Looking in the [TextArea section of the docs](https://kvision.gitbook.io/kvision-guide/v/kvision-1.x/part-2-advanced-features/form-controls-guide#p-t-k-f-text-textarea), it seems there were plans to have a readonly property of TextArea. However that doesn't seem to be an existing property of TextArea in 4.1.1. I am building a new project in kvision and this feature would be very nice to have :)

**Comment by rjaros** [comment]
Yes, `readonly` is a property and not a constructor parameter. I've fixed code samples in the guide (for some other controls as well). 
Thanks for the info!
