### ISSUE TITLE
Request - support for adding kotlinx tags as children to components

### ISSUE THREAD

**Issue by reubenfirmin** [rjaros/kvision#243]
Use case: I want to render SVG.

Following https://github.com/kotlin/kotlinx.html/wiki/Micro-templating-and-DSL-customizing, I can create some tags which look like they'll do the right thing. However, I don't have anywhere (obvious) to add them into the DOM.

```
class LINE(consumer: TagConsumer<*>, x1: Int, y1: Int, x2: Int, y2: Int):
    HTMLTag("line", consumer, mapOf("x1" to "$x1", "y1" to "$y1", "x2" to "$x2", "y2" to "$y2", "stroke" to "white"), inlineTag = true, emptyTag = true)

fun SVG.line(x1: Int, y1: Int, x2: Int, y2: Int, block: LINE.() -> Unit = {}) {
    LINE(consumer, x1, y1, x2, y2).visit(block)
}

fun DIV.svg(width: Int, height: Int, block: SVG.() -> Unit = {}) {
    SVG(mapOf("width" to "$width", "height" to "$height"), consumer).visit(block)
}
```

I haven't found any documentation on what they're doing with the visitor pattern or TagConsumer, but it seems that kvision would need to be able to hook into those. I think(?) I'd want to be able to do something like:

```
{
   val myDiv = Div()   // kvision's div
   myDiv.asKotlinElement<DIV>() {
        svg(500, 500) {
              line(0, 0, 100, 100)
              line(100, 100, 150, 150)
        }
   }
}
```

Etc. 

Of course I'd also take SVG support in KVision :) (which looks like it would swamp the Tag enum in noise, so probably would be best done as an extension -- https://developer.mozilla.org/en-US/docs/Web/SVG/Element) but it seems that a connection to kotlinx html like the above would be more flexible.

**Comment by rjaros** [comment]
You don't need kotlinx.html to define your own custom elements and DSL with KVision. You can do this even without defining any custom class:
```
fun Div.svg(width: Int, height: Int, block: CustomTag.() -> Unit = {}) {
    customTag("svg") {
        setAttribute("width", "$width")
        setAttribute("height", "$height")
        block()
    }
}

fun CustomTag.line(x1: Int, y1: Int, x2: Int, y2: Int, stroke: Col, block: CustomTag.() -> Unit = {}) {
    customTag("line") {
        setAttribute("x1", "$x1")
        setAttribute("y1", "$y1")
        setAttribute("x2", "$x2")
        setAttribute("y2", "$y2")
        setAttribute("stroke", stroke.name)
        block()
    }
}
```
and to use:
```
        root("kvapp") {
            div {
                svg(500, 500) {
                    line(0, 0, 100, 100, Col.AQUA)
                    line(100, 100, 150, 150, Col.BLACK)
                }
            }
        }

```

**Comment by rjaros** [comment]
If you want to reuse existing DSL for SVG you can also check https://github.com/nwillc/ksvg (unfortunately there is only legacy compiler version),  create your SVG as a text and use `rich = true` to render it inside KVision `Div` component.

**Comment by rjaros** [comment]
And one more comment :-) If you really would like to use `kotlinx.html` in KVision I suggest using `kvision-react` module. It allows you to use `kotlin-react` components which are based directly on `kotlinx.html`.
```
        inline fun RBuilder.custom(tagName: String, block: RDOMBuilder<HTMLTag>.() -> Unit): ReactElement = tag(block) {
            HTMLTag(tagName, it, mapOf(), null, true, false)
        }

        root("kvapp") {
            react {
                svg {
                    attrs["width"] = 500
                    attrs["height"] = 500
                    custom("line") {
                        attrs["x1"] = 0
                        attrs["y1"] = 0
                        attrs["x2"] = 100
                        attrs["y2"] = 100
                        attrs["stroke"] = "black"
                    }
                }
            }
        }

```

**Comment by reubenfirmin** [comment]
Much appreciated - thanks.
