### ISSUE TITLE
Possible memory leak on Tabulator's ColumnDefinition formatterComponentFunction

### ISSUE THREAD

**Issue by MikiLoz92** [rjaros/kvision#244]
I have detected what seems to be a memory leak when using the Tabulator's ColumnDefinition `formatterComponentFunction` param. 

This is our JS memory profile when adding a column without using `formatterComponentFunction`, and recreating the tabulator multiple times (result of switching between pages of our app):

<img width="546" alt="image" src="https://user-images.githubusercontent.com/786375/112636719-c25dab80-8e3d-11eb-9354-382559225ef0.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/786375/112636960-fafd8500-8e3d-11eb-83fb-3e44034fe2e0.png">

And this is the same code, but adding a simple Div with a text inside the `formatterComponentFunction`, and doing the page-switching again:

<img width="546" alt="image" src="https://user-images.githubusercontent.com/786375/112636682-b70a8000-8e3d-11eb-858a-5a6cf1b42d24.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/786375/112636847-e28d6a80-8e3d-11eb-95e3-3cf765273624.png">

Again, the only code that changes between executions is the code above. Test procedure was, for both cases:
1. Run Vision app.
2. Change between pages of our app, forcing the Tabulator instance to be created and disposed of multiple times.
3. Do that for about a minute and gather JS profile results.

Maybe I'm doing something wrong here, but the thing is that adding those Divs makes me wonder where are the references of those Divs being stored, and whether they are disposed of whenever the Tabulator instance is destroyed.

**Comment by rjaros** [comment]
Hi and thanks for your feedback.
You are absolutely right - there is a memory leak. In fact I've found a similar issue https://github.com/olifolkerd/tabulator/issues/2388 about Vue integration. Unfortunately the solution proposed by Tabulator maintainer is not working. But I'll think about a workaround.

**Comment by rjaros** [comment]
Fixed in 4.2.2.
