### ISSUE TITLE
Is KVision BootstrapVue compatible?

### ISSUE THREAD

**Issue by BFergerson** [rjaros/kvision#245]
I'm primarily a backend developer with some experience working with Bootstrap. I'm looking to build a UI in Kotlin without much JS/CSS and KVision appears to be exactly what I'm looking for. However, I'm curious if KVision is compatible with BootstrapVue. I see it works with Bootstrap but does that mean it'll also work with BootstrapVue? Does KVision care either way?

For some context, I'm purchasing a UI template and it comes with an implementation using Bootstrap and another using BootstrapVue. The BootstrapVue version appears to load pages cleaner so if possible I would like to use that version with KVision.

**Comment by rjaros** [comment]
Hello.
The answer is no - it is not. BootstrapVue is a set of components designed for Vue.js framework. You will not be able to use it without Vue.js. And unfortunately there is no way to mix Vue.js and KVision.
