### ISSUE TITLE
Maps module minimum working example

### ISSUE THREAD

**Issue by LonerDan** [rjaros/kvision#247]
Hello,
I am trying to use the maps module, but I could not find any example and when I try to use it based on reading the source code, it compiles and runs but nothing is displayed. Am I using it correctly? Could you please help me?

I am basing my code on the example generated by the kvision wizard plugin for Intellij. This is my App.kt.
![image](https://user-images.githubusercontent.com/11718484/113731145-d1274680-96f8-11eb-9f85-0fd3ddd5fb1b.png)
I tried it with also with the default container.

**Comment by rjaros** [comment]
Just set `width` and `height` for the `Maps` component:
```
        root("kvapp") {
            maps(49.93, 17.90, zoom = 13) {
                width = 400.px
                height = 400.px
            }
        }
```

**Comment by LonerDan** [comment]
Thank you, that works. Is there also a way to make it automatically use all the available space?

**Comment by rjaros** [comment]
Yes, but it depends what you mean by "available space". 
You can make it fill the whole browser window:
```
            maps(49.93, 17.90, zoom = 13) {
                width = 100.vw
                height = 100.vh
            }
```
Or you can make it fill the parent container:
```
            div {
                width = 800.px
                height = 600.px
                maps(49.93, 17.90, zoom = 13) {
                    width = 100.perc
                    height = 100.perc
                }
            }
```
You can use all HTML/CSS units.

**Comment by LonerDan** [comment]
Thank you :)
