### ISSUE TITLE
Application.kvisionInit on sever side breaks ktor routing

### ISSUE THREAD

**Issue by Archinamon** [rjaros/kvision#248]
Pre:
— backend application init phase
— invoke Application.kvisionInit
— define multiple get-routes in ktor

Effect:
All get requests routes to static handler, defined by kvisionInit. Then, as there's no such file lying on fs where backend application runs, server respond 404.

How to fix:
Remove routing definition by default and move it to separate method. Now I'm not able to fix this behavior and all get methods stop working after upgrading to kvision 4.+ Also I can't redefine kvisionInit method by myself to fix this issue, 'cause guice modules are internal.

**Comment by rjaros** [comment]
You should move `kvisionInit` to the end of your initialization code (or at least after get-routes definitions). It's explicitly stated in the docs since 4.0 release: https://kvision.gitbook.io/kvision-guide/part-3-server-side-interface/server-side/ktor#the-main-function

**Comment by Archinamon** [comment]
=___= Thanks, that makes routes work fine.

I'd prefer to remove all unnecessary routes and features of ktor I can't control from my own code.
My app doesn't use any statics from backend, why do kvision inits them for me?

**Comment by rjaros** [comment]
The standard way is to serve frontend application from Ktor. 
But it would not hurt to add a parameter you proposed in your PR and make it optional. I'll will merge this change for the next release.

**Comment by Archinamon** [comment]
Thank's a lot! It will make our code more clear! :)
