### ISSUE TITLE
(Div).getElement() as HTMLElement can fail

### ISSUE THREAD

**Issue by reubenfirmin** [rjaros/kvision#253]
```
    private val token = Div() {
        style {
            width = 100 to UNIT.px
            height = 10 to UNIT.px
        }
    }

    init {
        add(token)
    }

    fun popup() {
        val tokPos = (token.getElement() as HTMLElement).getBoundingClientRect()
```    
    
My first call of popup() works. "token" is never manipulated by my code. If I `console.log(token)`, both in the valid and failing conditions, it appears to be a proper div. However, in the failing condition `console.log(token.getElement())` shows that the element has become null (even though it's still visible).

I have seen this previously, and the function obviously allows for a null return.

(I'd settle for getBoundingClientRect being exposed directly on Tag :) - that's the only thing I do this cast for.)

**Comment by rjaros** [comment]
The single instance of KVision component (e.g. `Div`) is rendered by virtual DOM and can be "connected" to different `HTMLElements` during it's lifetime (or can be disconnected from the DOM, in witch case `getElement()` will return `null`).

So the question is when your `popup()` function is called. You should make sure it's called when the component is rendered. It should work fine if it's called from typical event handlers (e.g. `onClick`). Or you can use `addAfterInsertHook()`, which is called every time the component is rendered. You can also just add a condition and ignore actions when `getElement()` is `null`.

Of course when the component is not connected to the DOM, you can't use `getBoundingClientRect()` at all. There is no magic here - the result of such function would still have to be nullable.

**Comment by reubenfirmin** [comment]
It is called when the component is rendered, and works fine the first time through. Sometime during manipulation of later elements in the DOM it ended up going to null (despite not being in the area of the DOM being manipulated). Possibly the changed DOM caused the virtual DOM to no longer have it connected? I ended up reorganizing the page and the issue went away.

**Comment by rjaros** [comment]
There are many reasons a component can be disconnected from the DOM. KVision removes all invisible nodes and their children The most typical example is inactive `Tab`.
