### ISSUE TITLE
Request - provide alternate DSL for "require"

### ISSUE THREAD

**Issue by reubenfirmin** [rjaros/kvision#255]
IntelliJ/kotlin is quite unstable at the moment and takes a while to catch up with code (which is not your problem). However, the overloading of the require keyword for requiring resources ended up confusing IntelliJ for a minute or so today. 

![2021-04-24_11-40](https://user-images.githubusercontent.com/14217993/115967986-bb849000-a4f2-11eb-99f2-f0abd3171af6.png)

Suggest making an alternate "resource" DSL that doesn't clash with Kotlin's keyword.

**Comment by rjaros** [comment]
I'm not sure it can be done. Webpack needs a direct call to `require` with a string literal. But I'll make some tests with inline functions.

**Comment by rjaros** [comment]
Unfortunately even with an inline function it doesn't work, because a parameter is always converted to a variable.
