### ISSUE TITLE
Request - support for resize event

### ISSUE THREAD

**Issue by reubenfirmin** [rjaros/kvision#256]
You can currently do:

```
window.onresize = { ... }
```

However, if different parts of the app need to detect resize and act on them, there's no clean way to stack up resize behavior. I.e. if class A sets window.onresize, then when class B calls window.onresize, it clobbers A's behavior.

Granted that an application could set it up centrally, but this separation from the widget that needs to know about resizes could lead to code that's hard to debug.

**Comment by rjaros** [comment]
You should use this instead:
```
window.addEventListener("resize", {
    // ...
})
```
