### ISSUE TITLE
jQuery is not available from window object

### ISSUE THREAD

**Issue by fsmorygo** [rjaros/kvision#260]
Hello.

I have an issue. I see that KVision includes jQuery and bindings for it, however I cannot access it in my source code.

File:
```
<html>
<head>
  <script type="text/javascript" src="main.bundle.js"></script>
</head>
<body>
  <script>
    $(document).ready(); // This gives an error "$ is not defined"
  </script>
</body>
</html>
```

However if I include jQuery and some plugins like `datatables.js` in `index.html`, I can get access to it from document, but in Kotlin code this plugin is unavailable, and `$("...").DataTable()` results in an error `"DataTable is not a function"`.

It seems that in this case I have 2 jQuery instances available at different scopes, which is not something I'd want.

How can I make KVision's jQuery be accessible from document root?

**Comment by rjaros** [comment]
Probably the simplest way:
```
import io.kvision.jquery.jQuery

fun main() {
    window.asDynamic()["$"]=jQuery
    startApplication(::App, module.hot)
}
```

**Comment by fsmorygo** [comment]
Thanks, @rjaros, I have not thought of that simple solution.

This works for `$`, but `window.asDynamic()["jQuery"] = jQuery` as well as `window.asDynamic().jQuery = jQuery` gives a `jQuery360051032190791471521` function defined instead.

This can't be bypassed by `js("window.jQuery = $")` either., Why does the name gets mangled. Is this some kind of protection from Kotlin/JS compiler? This prevent using jQuery plugins, because the module factory cant find the library.

**Comment by rjaros** [comment]
That's probably because `window["jQuery"]` is somehow already defined inside Kotlin code. You can check this with `console.log(window.asDynamic()["jQuery"])` inside the `main` method. But this `window` seems to be different from the `window` inside `index.html`. I have no idea why it works like that.

**Comment by rjaros** [comment]
There is another way, look at https://github.com/rjaros/kvision/issues/166
You need to do two things:
- add external jquery (e.g. from CDN) to index.html:
```
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous"></script>
```
- add 
```
config.externals = {
    jquery: 'jQuery'
}
```
at the end of `webpack.config.d/jquery.js` file. 
This way the external jQuery should work both with KVision and your other plugins.

**Comment by fsmorygo** [comment]
Great, that works now. Thanks a lot.
