### ISSUE TITLE
Question - REST and  Server Side Interface

### ISSUE THREAD

**Issue by olivierayache** [rjaros/kvision#262]
Hello @rjaros I found this project very interesting/promising especially the server side interface.
I am wondering if there are some plans to extend this approach to be more generic by using standard REST API ?
If it is not the case it would be a pleasure to collaborate on this with you.

**Comment by rjaros** [comment]
Hi,
When talking about "standard REST API" you mean best practices described e.g. in this document:
https://docs.microsoft.com/en-us/azure/architecture/best-practices/api-design ?

**Comment by olivierayache** [comment]
In fact I was thinking about type safe RESTful services as describe here:
https://github.com/eclipse/microprofile-rest-client

**Comment by joerg-rade** [comment]
Hi,
https://en.wikipedia.org/wiki/Restful_Objects may be of interest as well.
(In fact, I'm implementing a RO viewer in Kvision.)

**Comment by rjaros** [comment]
Just to clarify, are we talking about easy generation of a client for the standard RESTful service or about generating both the client and the server, which would require changing current JSON-RPC based interfaces to something completely different?

**Comment by olivierayache** [comment]
I was thinking about automatic client proxy generation based on services interfaces that could be described using JAX-RS API. For this approach I think there is only work to do on client side.

**Comment by rjaros** [comment]
I understand. 
I think it should be possible, but will require some advanced programming inside the compiler plugin and some advanced code generation. Currently our compiler plugin is very simple, because it generates code based on simple text processing.

I'll try to experiment and prepare some skeleton code. But you will have to wait a bit, because currently I'm working on Kotlin 1.5.0 compatible release.

**Comment by olivierayache** [comment]
If you think it is interesting for the project I would be happy to work on this feature with you

**Comment by rjaros** [comment]
Looking at some older issues I think this one is no longer valid, because the same thing is already nicely done in the https://github.com/Foso/Ktorfit project.
