### ISSUE TITLE
Wrong red asterix position for CheckBox and RadioButton

### ISSUE THREAD

**Issue by kabacinsp** [rjaros/kvision#264]
Version Info
4.3.0

Describe the bug
Red asterisks appear inside  the CheckBox/RadioButton when using element in the form with required attribute

Expected behavior
Red asterisks should appear at the end of CheckBox/RadioButton label

Screenshots
![image](https://user-images.githubusercontent.com/50554080/117420734-25069480-af1e-11eb-943b-b147b9974d95.png)

**Comment by rjaros** [comment]
Fixed in 4.5.0
