### ISSUE TITLE
Pressing tab key in an editable cell in a tabulator throws Uncaught TypeError

### ISSUE THREAD

**Issue by m-kumaran** [rjaros/kvision#270]
Steps to reproduce:

In any editable Tabulator cell, edit the field
Change the content (don't press Enter)
Press tab (as some user behaviour to switch to the next cell)
Check the console for the error log

Sometimes, the content shows as updated in the UI, but any further action on the tabulator clears the whole table.

Can be reproduced in the example code too:
https://rjaros.github.io/kvision-examples/showcase/#!/tabulator

The underlined tabulator library has got this tab key feature while editing.
http://tabulator.info/examples/4.9#editable

It would be nice if this feature works in this awesome kvision component too.

Thanks

**Comment by rjaros** [comment]
I've tried to fix TAB key errors and it's not so easy. There are a couple of issues here:
- Data tree tabulator option seems to be broken when used with editable cells (I've filled an issue https://github.com/olifolkerd/tabulator/issues/3320)
- I've fixed errors in KVision code when data tree option is not used.
- `TAB` key will not always automatically activate next editable cell when KVision input components are used. Use native Tabulator editors if you need this.

**Comment by rjaros** [comment]
Released with 4.7.0
