### ISSUE TITLE
Checkbox input in tabulator does not work in touch screen devices

### ISSUE THREAD

**Issue by m-kumaran** [rjaros/kvision#273]
Steps to reproduce:
Open the showcase example (https://rjaros.github.io/kvision-examples/showcase/#!/tabulator)  in a mobile or iPad
Try to change the checkbox.

**Comment by rjaros** [comment]
It works for me on my android phone.

**Comment by rjaros** [comment]
Could you provide some more information, because I don't have any Apple device to check?

**Comment by rjaros** [comment]
I've managed to confirm this issue. For now I have no idea how to fix this.

**Comment by rjaros** [comment]
I suspect it's connected to https://github.com/olifolkerd/tabulator/issues/2157

**Comment by rjaros** [comment]
The jsfiddle example from the above issue is still failing on Safari. So I'm afraid we can't do anything on our side. The problem needs to be fixed in Tabulator.

**Comment by rjaros** [comment]
Should be fixed in KVision 6.2.1
