### ISSUE TITLE
Dynamic Table Data

### ISSUE THREAD

**Issue by joerg-rade** [rjaros/kvision#278]
The following code used to work, but ceased to do so a while ago (I really should cover it better in tests!):
(used to work = data was displayed)
```
/**
 * Makes properties of delegate available for display in tabulator.
 * For regular TObjects these are members (properties).
 * For FixtureResults these are: result, resultClass etc.
 *
 * Exposer bears some similarity to the JS "Revealing Module Pattern"
 * (see: https://addyosmani.com/resources/essentialjsdesignpatterns/book/),
 * but it goes further since it even reveals members of it's delegate.
 */
@Serializable
class Exposer(val delegate: TObject) {

    var iconName = ""
    var selected = false 

    fun dynamise(): dynamic {
        val thys = this.asDynamic()
        for (m in delegate.members) {
            val member = m.value
            if (member.memberType == MemberType.PROPERTY.type) {
                val realValue = member.value
                if (realValue != null) {
                    thys[member.id] = realValue.content
                }
            }
        }
        iconName = IconManager.find(delegate.title)
        if (iconName == IconManager.DEFAULT_ICON) {
            iconName = IconManager.find(delegate.domainType)
        }
        return thys
    }

    // eg. for dataNucleusId
    fun get(propertyName: String): Any? {
        return this.delegate.getProperty(propertyName)?.value
    }

}
```` 
I added in @OptIn(ExperimentalJsExport::class) and @JsExport without success.

Was there any change in KVision, Tabulator, or Kotlin that broke this code?

**Comment by rjaros** [comment]
Yep, there were changes to support IR backend, which also changed the behavior in legacy mode. Currently only data classes are supported as Tabulator models. I think it should be possible to fix this for legacy backend.

**Comment by rjaros** [comment]
Release 4.8.2 should be already on Maven Central. Could you please try this version and let me know if it works?

**Comment by joerg-rade** [comment]
Thanks a lot - I'll check in ~ 2h and let you know.

**Comment by joerg-rade** [comment]
I upgraded `gradle.properties` /` build.gradle.kts` according to https://github.com/rjaros/kvision-examples/tree/master/addressbook-tabulator and get:
```

Error: Compiling RuleSet failed: Query arguments on 'loader' has been removed in favor of the 'options' property (at ruleSet[1].rules[1].loader: url-loader?limit=10000&mimetype=application/font-woff)
    at RuleSetCompiler.error (C:\data\master\isis\incubator\clients\kroviz\build\js\node_modules\webpack\lib\rules\RuleSetCompiler.js:373:10)
    at C:\data\master\isis\incubator\clients\kroviz\build\js\node_modules\webpack\lib\rules\UseEffectRulePlugin.js:160:29
    at Hook.eval [as call] (eval at create (C:\data\master\isis\incubator\clients\kroviz\build\js\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:45:1)
    at RuleSetCompiler.compileRule (C:\data\master\isis\incubator\clients\kroviz\build\js\node_modules\webpack\lib\rules\RuleSetCompiler.js:177:19)
    at C:\data\master\isis\incubator\clients\kroviz\build\js\node_modules\webpack\lib\rules\RuleSetCompiler.js:154:9
    at Array.map (<anonymous>)
    at RuleSetCompiler.compileRules (C:\data\master\isis\incubator\clients\kroviz\build\js\node_modules\webpack\lib\rules\RuleSetCompiler.js:153:16)
    at RuleSetCompiler.compileRule (C:\data\master\isis\incubator\clients\kroviz\build\js\node_modules\webpack\lib\rules\RuleSetCompiler.js:184:30)
    at C:\data\master\isis\incubator\clients\kroviz\build\js\node_modules\webpack\lib\rules\RuleSetCompiler.js:154:9
    at Array.map (<anonymous>)

Execution failed for task ':browserDevelopmentRun'.
> <i> [webpack-dev-server] [HPM] Proxy created: /kv  -> http://localhost:8080
  <i> [webpack-dev-server] [HPM] Proxy created: /kvws  -> ws://localhost:8080
  C:\data\master\isis\incubator\clients\kroviz\build\js\node_modules\webpack\lib\rules\UseEffectRulePlugin.js:160
  						throw ruleSetCompiler.error(
  						^

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by rjaros** [comment]
You need to update files in your `webpack.config.d` folder.

**Comment by rjaros** [comment]
Could you share your project or at least paste your tabulator code?

**Comment by rjaros** [comment]
I think I have found the source of the problem - you are using `componentFormatterFunction`. Version 4.8.3 is on the way. I hope it will work.

**Comment by rjaros** [comment]
4.8.3 is on Maven Central

**Comment by joerg-rade** [comment]
Sorry for not responding earlier. I'm still struggeling with the Kotlin/IntelliJ update.
I'll get back ASAP.

**Comment by joerg-rade** [comment]
One thing I bang my head at is @ExperimentalStdlibApi.
Annotating methods or classes results in perculating the issue up to root.
And I could not find out how to set it in build.gradle.kts yet.

**Comment by rjaros** [comment]
Use `@OptIn` instead:
```
@OptIn(ExperimentalStdlibApi::class)
```

**Comment by joerg-rade** [comment]
KVision is now at 4.8.3
Source -> https://github.com/apache/isis/tree/ISIS-2505_Catch_Up_With_Demo_Examples/incubator/clients/kroviz

https://github.com/apache/isis/blob/ISIS-2505_Catch_Up_With_Demo_Examples/incubator/clients/kroviz/src/main/kotlin/org/apache/isis/client/kroviz/ui/core/ColumnFactory.kt actually contains various places where formatterComponentFunction is used, and commenting it out didn't do the trick yet.

(BTW: IntelliJ is back at 2020.1.4 :=)

**Comment by joerg-rade** [comment]
To run against  a backend, you may want to give https://hub.docker.com/r/apacheisis/demo-wicket-jdo a try.

**Comment by joerg-rade** [comment]
Does this throw any light on the cause?
![ScreenShot 518 DevTools - localhost_3000_](https://user-images.githubusercontent.com/4637858/124639729-cbbed100-de8c-11eb-921b-4a4ec0bcde5c.png)

**Comment by rjaros** [comment]
You are using IR backend here and my fixes are for legacy backend. 
And to be clear - with IR there is no way to use anything but standard data class for Tabulator model.

**Comment by rjaros** [comment]
Btw, I've made some local changes to test KroViz with KVision 5 snapshots and it works quite well, especially when it comes to performance (KVision 5 will be at least 50% faster). Most problematic to upgrade were your overridden classes (`RoWindow`, `RoTab`). Could you please give some info why creating your own classes was necessary in the first place? Perhaps I can port such things to KVision itself.

**Comment by joerg-rade** [comment]
Thanks Robert!

Reasons for copying/overriding are:
* RoManagerBootstrap: make dialogs transparent on move
* RoTab: add  icon menu, recreate svg
* RoTabpanel: add IconMenu
* RoWindow: make dialogs transparent on move, add menu to icon

**Comment by joerg-rade** [comment]
With `kotlin.js.compiler=legacy` and without `formatterComponentFunction` it works!

**Comment by rjaros** [comment]
When it comes to `Window` component I will:
- change access modifier of most private properties to protected (e.g. header, caption), so you will be able to inherit and modify them instead of creating your own class.
-  add two new events, which will allow intercept dragging, even without inheritance:
```
        onEvent {
            dragStartWindow = {
                self.getElementJQuery()?.css(
                    "opacity",
                    "0.5"
                )
            }
            dragEndWindow = {
                self.getElementJQuery()?.css(
                    "opacity",
                    "1.0"
                )
            }
        }
```

**Comment by rjaros** [comment]
I've change access modifiers to some properties in `TabPanel` and `Tab` components as well, so you should be able to just extend existing classes.

**Comment by rjaros** [comment]
However I am not able to comprehend what you are doing with these svgs :-)

**Comment by joerg-rade** [comment]
That's some kind of hackery/magic: 
1. a marker (UUID) is set into the DOM (synchronous) 
2 an async call is made to retrieve the SVG (eg. from kroki); UUID is logged with the request
3. response with SVG data arrives for the request, UUID is looked up and content of the DOM is replaced with SVG

Eventually there are smarter ways to handle it ;-)

**Comment by rjaros** [comment]
Is downloading svg and inserting it's code directly to the DOM  better than using normal `<img>` tag?

**Comment by joerg-rade** [comment]
Not necessarily - IIRC I tried <img> but it didn't work - but my memories may be wrong.
I'll give it a try next time I refactor that part.
