### ISSUE TITLE
Internalization in DateTime

### ISSUE THREAD

**Issue by GrishinSergeyLexpharma** [rjaros/kvision#280]
Can't get the DateTime to work in Russian locale.

In html installed` <html lang="ru_RU">`

inApp.kt
```
override fun start(state: Map<String, Any>) {
        I18n.manager =
            DefaultI18nManager(
                mapOf(
                    "ru" to io.kvision.require("i18n/messages-ru.json"),
                )
            )
        I18n.language = "ru"
```

All the same in DateTime everything is in English

In your web examples, Kvision DateTime is also in English

**Comment by rjaros** [comment]
Hello,

Since KVision 4.0.0 all example apps are configured to not include Moment.js locales, because of the large bundle size. It's configured in `webpack.config.d/moment.js` file with this code:
```
        config.plugins.push(new webpack.IgnorePlugin({
            resourceRegExp: /^\.\/locale$/,
            contextRegExp: /moment$/,
        }));
```
You can add desired locales manually in your `App.kt` with `require("moment/locale/ru")`.

**Comment by GrishinSergeyLexpharma** [comment]
`require("moment/locale/ru").`

Thanks it works!
