### ISSUE TITLE
Unable to add custom headers to Upload control

### ISSUE THREAD

**Issue by fsmorygo** [rjaros/kvision#281]
When using serivces, I can provide a `beforeSend` handler, which can add custom http headers (auth token in my case)

But i do not find any API to do same with Uploads. I do not want to use client-side file handling to send a string through `@KVService`-style service. Is it possible?

**Comment by rjaros** [comment]
I'm afraid it's currently not possible because `UploadInput` doesn't support  [ajaxSettings](https://plugins.krajee.com/file-input/plugin-options#ajaxSettings) option of the Bootstrap File Input control. It should be fixed for the next release.

**Comment by rjaros** [comment]
Released with KVision 5.0.0
