### ISSUE TITLE
Request: allow Tabulator to display sub-classed models

### ISSUE THREAD

**Issue by tfonrouge** [rjaros/kvision#282]
Hi RJaros,

First at all, thank for your amazing library.

I just want to make a request: Tabulator doesn't show correctly sub-classed class models on the columns, seems that only
root classes (with no super class) are displayed correctly as per the small bellow sample.

When you use a subclass for containing your data, only the data contained in the subclass is showed and data pertaining to the parent classes aren't showed, even when you try to set the formula with the 'formatterComponentFunction' parameter on the column definition, the value shows as 'undefined'.

This imposes an important restriction to my project because I'm trying to use KVision to process complex data coming from my REST service which exposes serialized data from complex class structures, basically base classes which are subclassed on specialized data containers.

Even that I've found a way to correctly display data contained in super classes, this is some cumbersome and I want to see if it's possible do it in the elegant way as Kotlin is and KVision itself does :-)

In the bellow sample, the tabulator only shows two columns (genre and lastMovie) which are the only two properties of the final subclass 'Actor'. I've commented out the way in which the classes are defined in order to show the information correctly, by using a lot of property re-declarations and overrides.

I'm almost sure that I'm not seeing some important point in this problem, but I'll like to know what are the reasons which make Tabulator not allow using sub-classed models.

Thanks in advance !

```kotlin
package com.example.kvtest1

import io.kvision.Application
import io.kvision.html.Span
import io.kvision.module
import io.kvision.panel.root
import io.kvision.startApplication
import io.kvision.tabulator.ColumnDefinition
import io.kvision.tabulator.TabulatorOptions
import io.kvision.tabulator.tabulator
import kotlinx.serialization.Contextual
import kotlin.js.Date

class App : Application() {

    private val list = buildActorList()

    init {
        list.forEach { console.log(": ", it) }
    }


    override fun start() {
        root("kvapp") {
            tabulator(
                data = list,
/*
                options = TabulatorOptions(
                    columns = listOf(
                        ColumnDefinition(title = "Id", field = "id",
                            formatterComponentFunction = { _, _, data -> Span("data.id = ${data.id}") }),
                        ColumnDefinition(title = "Name", field = "name",
                            formatterComponentFunction = { _, _, data -> Span(data.name) }),
                        ColumnDefinition(title = "First Name", field = "firstName"),
                        ColumnDefinition(title = "DoB", field = "dob"),
                        ColumnDefinition(title = "Genre", field = "genre"),
                        ColumnDefinition(title = "Last Movie", field = "lastMovie"),
                    )
                )
*/
            )
        }
    }
}

fun main() {
    startApplication(::App, module.hot)
}

fun buildActorList(): List<Actor> {
    return listOf(
        Actor("1", "Tom", "Hanks", Date(Date.parse("7/9/1956")), "Comedy", "Elvis"),
        Actor("2", "Jim", "Carrey", Date(Date.parse("6/17/1962")), "Comedy", "Sonic the Hedgehog"),
        Actor("3", "Morgan", "Freeman", Date(Date.parse("6/1/1937")), "Suspense", "The Hitman's Wife's Bodyguard"),
    )
}

/*
@JsExport
abstract class BaseModel(
    open val id: String
)

@JsExport
open class Person(
    override val id: String,
    open val name: String,
    open val firstName: String,
    @Contextual
    open val dob: Date,
) : BaseModel(id)

@JsExport
class Actor(
    override val id: String,
    override val name: String,
    override val firstName: String,
    override val dob: Date,
    val genre: String,
    val lastMovie: String,
) : Person(id, name, firstName, dob)
*/

@JsExport
open class BaseModel(
    var id: String
)

@JsExport
open class Person(
    id: String,
    var name: String,
    var firstName: String,
    @Contextual
    var dob: Date,
) : BaseModel(id)

@JsExport
class Actor(
    id: String,
    name: String,
    firstName: String,
    dob: Date,
    var genre: String,
    var lastMovie: String,
) : Person(id, name, firstName, dob)
```

**Comment by rjaros** [comment]
Hi and thanks for your feedback!

When using new IR compiler backend Kotlin classes are represented on the JS level in a way, which is not compatible with JavaScript Tabulator component (because it supports only plain JS objects). It was different with legacy backend and KVision currently uses some very dirty hacks to support both backends (it internally converts Kotlin classes to JS objects and JS objects to Kotlin classes). But only simple data classes are supported with IR.

Long time ago Tabulator required model classes to be serializable but we have dropped that requirement since it was not necessary with legacy backend (see issue #58). I'm considering re-introducing this as an option to support more complex use cases like yours.

**Comment by tfonrouge** [comment]
Hi, thanks for your prompt replay !.

Seems like an important limitation on the way in which Tabulator deals with the data source when is in the form of an array of objects.

However I’ve forked KVision in order to see if a hack can provide the functionality I need.

In the mean time, I’ll use the override properties model in the sub-classing because I want to keep design integrity in the backend (my REST server is in Kotlin with SpringBoot) with the frontend data structure.


Best regards,

Teo Fonrouge

**Comment by rjaros** [comment]
I've added support for complex data models with serializable classes. Unfortunately it doesn't work for your class hierarchy, because it's not serializable with kotlinx.serialization. This is what works for me (but probably there are better ways to create serializable class hierarchies):
```
@Serializable
abstract class BaseModel {
    abstract val id: String
}

@Serializable
abstract class Person : BaseModel() {
    abstract val name: String
    abstract val firstName: String
    abstract val dob: Date
}

@Serializable
class Actor(
    override val id: String,
    override val name: String,
    override val firstName: String,
    @Contextual
    override val dob: Date,
    val genre: String,
    val lastMovie: String,
) : Person()

```

**Comment by tfonrouge** [comment]
Thank you, in the mean time I'm using the same approach that I've already exposed in my example (using abstract base class and doing a lot of overrides in inherited classes).

If you don't mind, I'm closing the issue for now.

many thanks again !
