### ISSUE TITLE
Tabulator mutator methods have incorrect signature

### ISSUE THREAD

**Issue by hywelbennett** [rjaros/kvision#283]
When providing a mutator for a tabulator column, the function should return the correct type from the cell's data (e.g. http://tabulator.info/docs/4.1/mutators). 

The signatures in `ColumnDefinition`, e.g. 

`val mutator: ((value: dynamic, data: dynamic, type: String, params: dynamic, cell: Tabulator.CellComponent) -> Unit)? = null,`

indicate the type returned is Unit, and so the mutator always ends up returning Unit (the generated JS ends with `return Unit_getInstance();`)

**Comment by rjaros** [comment]
Released with KVision 5.0.0
