### ISSUE TITLE
Missing fileuploaded event in `Upload` component

### ISSUE THREAD

**Issue by fsmorygo** [rjaros/kvision#285]
In AJAX upload server can return a JSON result. Is there a way to access the result except for getting a jQuery element of `UploadInput` and subscribing to an event natively?

In `io/kvision/form/upload/UploadInput.kt:225` i see several events, but not that particular one

**Comment by fsmorygo** [comment]
Relates to #281

**Comment by rjaros** [comment]
I've rewritten jQuery event handling for KVision 5. All events will be automatically supported.

**Comment by rjaros** [comment]
Released with KVision 5.0.0
