### ISSUE TITLE
Tabulator setFilter for AJAX filters?

### ISSUE THREAD

**Issue by drammelt** [rjaros/kvision#286]
I am trying to implement AJAX filtering, the headerFilters work fine but I want to use a custom input box for some tables.

Tabulator [documentation](http://tabulator.info/docs/4.9/filter) shows 

> Equal
> The = filter displays only rows with data that exactly matches the filter value
> 
> table.setFilter("name", "=", "Steve");

Which should send through the filters field in the AJAX request body.

`filters: [{field: "name", type: "=", value: "Steve}]`

But KVision only has the local filtering function, which just sends null values for filters.

`setFilter(filter: (Any) -> Boolean)`

Is it currently possible to implement something that generate the correct filters values for AJAX without using headerFilters?

**Comment by rjaros** [comment]
Hi
The Tabulator component gives you full access to the `jsTabulator` property, which contains native component. So you should be able to just call `tabulator.jsTabulator?.setFilter("name", "=", "Steve")`. Let me know if this works for you.

**Comment by drammelt** [comment]
Works perfectly using an Observable value to update the filter thank you!

```
tabulator.bind(Model.search) {
    tabulator.jsTabulator?.setFilter("name", "like", Model.search.value)
}
```
