### ISSUE TITLE
Update Get From Marketplace button

### ISSUE THREAD

**Issue by RedPenguinIO** [rjaros/kvision#289]
Nice new updates to v4.8.3 but the button is only for v4.7.0. Is that the most stable version, or do you plan to update it? Any info would be really nice thanks

**Comment by rjaros** [comment]
There is no need to update marketplace plugin with every release, because it always takes current versions from the github repository (from the `versions.json` file - but I've just fixed it to point to `4.8.3` instead of `4.8.1`).
