### ISSUE TITLE
Integration Tests with Docker?

### ISSUE THREAD

**Issue by joerg-rade** [rjaros/kvision#290]
I would like to execute integration tests (KVision UI -> Java backend) and have the backend container automatically started before IT execution and shut down afterwards.

https://plugins.gradle.org/search?term=docker+integration+test lists many plugins.

Any experiences/recommendations?

**Comment by rjaros** [comment]
I'm afraid I don't know much about Docker.

**Comment by joerg-rade** [comment]
OK - I'll report my findings.

**Comment by joerg-rade** [comment]
I've simply added a docker directory to my project and put in there docker-compose.yml:
```
# in ~/causeway/incubator/clients/kroviz/docker/ execute
# $ sudo docker-compose up
version: "3"

services:
  causeway-app-demo:
    image: apache/causeway-app-demo-jpa:latest
    ports:
      - "8080:8080"
    environment:
      - PROTOTYPING=true
 ```
Currently this is started manually, but I guess it could easily be called from gradle.
