### ISSUE TITLE
How to Size an Image in Tabulator?

### ISSUE THREAD

**Issue by joerg-rade** [rjaros/kvision#291]
ColumnDefinition is as follows:
```
private fun buildIcon(): ColumnDefinition<Exposer> {
        return ColumnDefinition<dynamic>(
                "",
                field = "icon",
                formatter = Formatter.IMAGE,
                formatterParams = obj { width = 10.px; height = 10.px },
                hozAlign = Align.CENTER,
                width = "40"
        )
    }
```
But on the screen it looks like:
![icon_screen](https://user-images.githubusercontent.com/4637858/128736214-f4c242a5-05f8-468d-a0c9-f490a1f293b9.png)

Div is:
![icon_div](https://user-images.githubusercontent.com/4637858/128736321-ff45d489-f359-496a-a875-03549c837aa8.png)

How should I pass the parameters?

**Comment by rjaros** [comment]
I would start by replacing KVision units (`10.px`) with a CSS string (`"10px"`).

**Comment by joerg-rade** [comment]
Perfect - that did the trick!
