### ISSUE TITLE
Get Element from Component

### ISSUE THREAD

**Issue by drammelt** [rjaros/kvision#292]
I am trying to implement a Google Map within KVision but am hitting a brick wall.

The Maps initialiser takes a Div as a parameter

`external class Map(mapDiv: Element, opts: MapOptions) : MVCObject {`

I want to do something like...

```
object MapPanel: SimplePanel() {
    init {
        div { id = "googleDiv" }
    }

    fun updateMap() {
        document.getElementById("googleDiv")?.let { element ->
            Map(mapDiv = element, opts = MapOptions().apply {
                zoom = 6
                center = LatLngLiteral().apply {
                    lat = 54.3
                    lng = 12.3
                }
            })
        }
    }
}
```

However the getElementByID is always null, presumably because the div needs to be in the index.html to use this call? Is there some way to get an Element reference from a div component?

**Comment by rjaros** [comment]
You need to call your `updateMap()` after the component is rendered. You can override `afterInsert()` or use `addAfterInsertHook()` method for this.
Also have you checked `kvision-maps` module?

**Comment by drammelt** [comment]
That works perfectly, I was not aware of the maps module so will definitely check that out.

Thank you!
