### ISSUE TITLE
Guide is incorrect or incomplete regarding the debugging of KVision app

### ISSUE THREAD

**Issue by JasperCiti** [rjaros/kvision#295]
I followed the instructions on https://kvision.gitbook.io/kvision-guide/part-1-fundamentals/setting-up#debugging (last note) in an attempt to enabled source code debugging. First prize would be if I can add breakpoints directly in Intellij and step through the code but even in the browser will also be acceptable.

What I did:

1. Used your addressbook-fullstack-spring-boot example (haven't tried the examples ones yet):
2. In build.gradle.kts I set sourceMaps = true
3. In webpack.js I set config.devtool = 'source-map' (the KVision docs says just remove it, but it seems like it defaults to no source maps so I am not sure)

However, with these changes and some experimental variations I tried, I still do not see the source code in my browser and also the IntelliJ ignores my breakpoints.

I have tried the frontendRun and frontendBrowserDevelopmentRun run configuration in IntelliJ. Neither seems to work.

Did I misunderstood the guide?

Any advise on how to debug my KVision app?

**Comment by rjaros** [comment]
KVision examples are using IR backend by default, which doesn't support source maps yet (it will in Kotlin 1.5.30).
So you need to also change:
```
 kotlin.js.compiler=ir
```
to
```
kotlin.js.compiler=legacy
```
in your `gradle.properties`.

**Comment by rjaros** [comment]
Guide updated. Thanks for your feedback!

**Comment by JasperCiti** [comment]
It works!

Thank you for the quick feedback. It even fixed another unexplainable Tabulator bug that I discovered in a similar KVision project I had (which I wanted to debug originally). I am really impressed.

Not sure why the KVision Tabulator component is not compatible with ir, but that is a separate issue.

**Comment by rjaros** [comment]
Check related issues for info about Tabulator and IR backend:
https://github.com/rjaros/kvision/issues/277
https://github.com/rjaros/kvision/issues/282
https://github.com/rjaros/kvision/issues/278
