### ISSUE TITLE
How to use this framework with gradle?

### ISSUE THREAD

**Issue by ricmf** [rjaros/kvision#3]
Hi, this looks very nice and it's much easier to understand coming from desktop java than other web frameworks.

I tried adding a gradle dependency "pl.treksoft:kvision:0.0.12" to my project (after digging a little through the code) but when i build try to run it in the browser it says "Error loading module 'mymodule-js'. Its dependency 'kvision' was not found. Please, check whether 'kvision' is loaded prior to 'mymodule-js'."

I'm not using webpack or kotlin frontend pluging, because i have an existing project using spring boot. Is there a way to use kvision as a dependency using gradle?

**Comment by ricmf** [comment]
I have a structure very similar to this project: https://github.com/techprd/spring-boot-kotlin-js, with spring boot module and a frontend kotlin2js module which copies the generated files into the static folder of the spring boot module. The frontend module compiles normally and is able to see kvision classes, but i can't run it. I'm new to web development, maybe all that's needed is to include a kvision js file bundled with it's dependencies in my html page, but i'm not sure where to find/how to generate such file.

**Comment by rjaros** [comment]
I've found some incompatibilities between this project and kvision. The main index.html includes files in AMD module format. This file should include all files generated in js/lib/kotlin folder from kvision dependencies. It should look probably a bit like this:

`<script type="text/javascript" src="js/lib/kotlin/jquery-kotlin.js"></script>`
`<script type="text/javascript" src="js/lib/kotlin/kotlin-observable-js.js"></script>`
`<script type="text/javascript" src="js/lib/kotlin/kotlinx-coroutines-core.js"></script>`
`<script type="text/javascript" src="js/lib/kotlin/navigo-kotlin.js"></script>`
`<script type="text/javascript" src="js/lib/kotlin/snabbdom-kotlin.js"></script>`
`<script type="text/javascript" src="js/lib/kotlin/kvision.js"></script>`

But almost all these projects are built with:

`kotlinOptions.moduleKind = 'commonjs'`

and that is why these scripts can't be included in index.html. If these projects were built with 'umd' moduleKind option, it probably would work fine. I can change this in next version of kvision and other my projects (jquery-kotlin, kotlin-observable-js, navigo-kotlin). But I can't make this change in at least https://github.com/gbaldeck/snabbdom-kotlin - you would have to fill an issue there. And remember there are more dependencies needed - a lot of javascript dependencies from npm repository. Some of them may also be incompatible with AMD module kind (as far as I know node.js uses commonjs format).

**Comment by ricmf** [comment]
Thanks, i ended up getting it to work by copying a build.gradle from the showcase. Though there should probably be instructions on the readme on how to change your current build.gradle file to use kvision.
