### ISSUE TITLE
Not able to require a local css file

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#30]
My resources folder looks like this:
```
resources
    -css
       -bootstrap.min.css
```
I am trying to require a new bootstrap file like this in my start function:
```
...
pl.treksoft.kvision.require("./css/bootstrap.min.css")
...
```
However, I get a 404 not found error. Just as in the showcase example, I've got this copy resources task defined in my build.gradle:
```
task copyResources(type: Copy) {
    from "src/main/resources"
    into file(buildDir.path + "/js")
}
```
The `copyResources` task does the right thing and copies it into `build/js/css/bootstrap.min.css`, but it doesn't let me require the css file in my code

**Comment by rjaros** [comment]
Could you paste here the log with this 404 error? Is it from the browser console or from gradle process?
Do you have this problem during development or production build?

**Comment by robert-cronin** [comment]
Sorry I realize its a different error when using kvision require, the 404 error came from including it in my html file. If I use require, this is the browser console output:
```
Uncaught Error: Cannot find module './js/css/bootstrap.min.css'
    at webpackMissingModule (client.js:320)
    at FleetHomeElectron.start_x7u0o8$ (client.js:320)
    at start (client.js:222)
    at HTMLDocument.eval (client.js:194)
...
client:180 ./client.js
Module not found: Error: Can't resolve './js/css/bootstrap.min.css' in '/Users/rob/Documents/GitHub/Fleet-CG-Java/client/build/js'
```
That is in development, in production I actually get a gradle error when running shadowJar:
```
ERROR in ./css/bootstrap.min.css (../node_modules/css-loader/dist/cjs.js!./css/bootstrap.min.css)
Module not found: Error: Can't resolve '../fonts/glyphicons-halflings-regular.eot' in '/Users/rob/Documents/GitHub/Fleet-CG-Java/client/build/js/css'
 @ ./css/bootstrap.min.css (../node_modules/css-loader/dist/cjs.js!./css/bootstrap.min.css) 5:41-93 6:41-93
 @ ./css/bootstrap.min.css
 @ ./client.js

ERROR in ./css/bootstrap.min.css (../node_modules/css-loader/dist/cjs.js!./css/bootstrap.min.css)
Module not found: Error: Can't resolve '../fonts/glyphicons-halflings-regular.svg' in '/Users/rob/Documents/GitHub/Fleet-CG-Java/client/build/js/css'
 @ ./css/bootstrap.min.css (../node_modules/css-loader/dist/cjs.js!./css/bootstrap.min.css) 10:41-93
 @ ./css/bootstrap.min.css
 @ ./client.js

ERROR in ./css/bootstrap.min.css (../node_modules/css-loader/dist/cjs.js!./css/bootstrap.min.css)
Module not found: Error: Can't resolve '../fonts/glyphicons-halflings-regular.ttf' in '/Users/rob/Documents/GitHub/Fleet-CG-Java/client/build/js/css'
 @ ./css/bootstrap.min.css (../node_modules/css-loader/dist/cjs.js!./css/bootstrap.min.css) 9:41-93
 @ ./css/bootstrap.min.css
 @ ./client.js

ERROR in ./css/bootstrap.min.css (../node_modules/css-loader/dist/cjs.js!./css/bootstrap.min.css)
Module not found: Error: Can't resolve '../fonts/glyphicons-halflings-regular.woff' in '/Users/rob/Documents/GitHub/Fleet-CG-Java/client/build/js/css'
 @ ./css/bootstrap.min.css (../node_modules/css-loader/dist/cjs.js!./css/bootstrap.min.css) 8:41-94
 @ ./css/bootstrap.min.css
 @ ./client.js

ERROR in ./css/bootstrap.min.css (../node_modules/css-loader/dist/cjs.js!./css/bootstrap.min.css)
Module not found: Error: Can't resolve '../fonts/glyphicons-halflings-regular.woff2' in '/Users/rob/Documents/GitHub/Fleet-CG-Java/client/build/js/css'
 @ ./css/bootstrap.min.css (../node_modules/css-loader/dist/cjs.js!./css/bootstrap.min.css) 7:41-95
 @ ./css/bootstrap.min.css
 @ ./client.js
```

**Comment by rjaros** [comment]
I think the source of the problem is the content of this bootstrap.min.css file itself. To confirm, please replace this file with an empty one and try to run the build process again.
But first just try to put `fonts` folder from bootstrap distribution to your `resources` dir. It has resolved similar problem for me.

**Comment by robert-cronin** [comment]
I tried to modify the bootstrap file to just contain:
```
body {
    background-color: lightblue;
}
```
The require line in the start method did not do anything but putting it in the html file disabled the default bootstrap theme, as the guide alludes to, and seemed to allow the require in the start method to finally work:
```
 <link href="./css/bootstrap.min.css" rel="stylesheet">
```
However I still get a 404 error of not found: 
```
GET http://localhost:8088/css/bootstrap.min.css net::ERR_ABORTED 404 (Not Found)
```
Is there any way to override the default bootstrap with just kotlin code? just adding a require didn't seem to do anything, to be expected I suppose

**Comment by rjaros** [comment]
To override default bootstrap css you should add the `<link href="css/bootstrap.min.css" rel="stylesheet">` to the `index.html` file, but the `bootstrap.min.css` file you want to use should be put into `src/main/web/css` directory (not in the `src/main/resources`). No `require()` is necessary. This file (all files and directories from `web`) will be copied "as is" to the `build/distributions/*` and will be included in the page as a normal static file. You probably need to put `fonts` directory into `web` as well.

**Comment by robert-cronin** [comment]
great, thanks for that

**Comment by robert-cronin** [comment]
I have a new issue along the lines of this old one so decided to keep it in the same thread. I am trying to require a CSS file as a string and apply it to a single div, I am using an external library (https://printjs.crabbly.com/) so would like to require a single CSS file and use its string to pass to this external library.

I have a CSS file `paper.css` in `src/main/resources/css` directory and trying to load it in with `val paperCss = require("./css/paper.css")` but when I try `console.log(paperCss)` all I get is an empty object. Do you know the proper way to webpack require a CSS file?

**Comment by rjaros** [comment]
Have you tried `toString` method?
https://github.com/webpack-contrib/css-loader#tostring

**Comment by robert-cronin** [comment]
yes, if I do `require("....").toString()`, it just returns this: `[object Object]` I'm not sure if thats right

**Comment by rjaros** [comment]
This works for me:
`require("!!css-loader!./css/paper.css").toString()`

**Comment by robert-cronin** [comment]
yep that worked for me! I guess I just don't know my webpack require well enough!
