### ISSUE TITLE
Request - support for simple table component outside of bootstrap module

### ISSUE THREAD

**Issue by reubenfirmin** [rjaros/kvision#302]
I'm working on slimming down the distribution for my app, and would like to avoid using bootstrap. I use a table in the help section of my application (but nowhere else) - I can't really justify including bootstrap's module just for that (although the tree shaking may be eliminating what I'm not using, tbd.) For now I'll use a flexgrid, but it'd be nice to have simple table support in the core component library.

**Comment by rjaros** [comment]
`Table` component was always designed for Bootstrap CSS (it uses enums for Bootstrap colors, style types and responsive types). That's why I decided to move it into Bootstrap module. 

But you can always use html tables with components from `io.kvision.html` package:
```
            table {
                thead {
                    tr {
                        th("Header 1")
                        th("Header 2")
                        th("Header 3")
                    }
                }
                tbody {
                    tr {
                        td("Column 1")
                        td("Column 2")
                        td("Column 2")
                    }
                }
            }

```

**Comment by reubenfirmin** [comment]
Ah, nice - exists already. I'll make sure this is covered in docs.
