### ISSUE TITLE
Request - ability to suspend snabbdom and then resync it

### ISSUE THREAD

**Issue by reubenfirmin** [rjaros/kvision#304]
Use case: I'm using a drag & drop library that likes to insert / remove elements from the DOM. Under load (i.e. whipping dragged elements around the page over a half dozen containers) snabbdom eventually gets out of sync and starts throwing exceptions. This is just as likely an issue with the drag & drop implementation than it is snabbdom; nevertheless, it'd be very useful if I could "pause" snabdom when I know the UI's entering dangerous territory and then resume/resync it when I know it's safe (i.e. on drag start & drag end events.)

**Comment by rjaros** [comment]
Released with 5.2.0
