### ISSUE TITLE
CSS Tablator table-sm

### ISSUE THREAD

**Issue by GrishinSergeyAl** [rjaros/kvision#305]
Hello!
In version 4.8.*  the tabulator was displayed correctly.
Moved to 5.1.1 yesterday and got a problem. Tabulator drawing incorrectly for complex headers and style "table-sm"

![Screenshot_1](https://user-images.githubusercontent.com/45869875/133558526-8995005c-fb67-4020-ad9f-b6ccf9125b4f.png)

**Comment by rjaros** [comment]
Probably an issue with Bootstrap 5 styling. I'll look into it.

**Comment by rjaros** [comment]
I've published new assets to NPM, so this should be fixed even without new KVision release. Just clean the project and rebuild.
