### ISSUE TITLE
How to set initial value to a Select with Ajax

### ISSUE THREAD

**Issue by tfonrouge** [rjaros/kvision#306]
Hello all,

Surely I've missed something but I'm unable to set the initial value displayed in the displayed field area.

It works okay with Select without Ajax simply by setting the value property to the desired initial value.

But with Ajax datasource I've tried without success set the text value in the field, or the id to the value property.

thanks in advance for any hints !

**Comment by rjaros** [comment]
Unfortunately this is not supported by the original Ajax-Bootstrap-Select component. There are even some issues closed without resolution, e.g. https://github.com/truckingsim/Ajax-Bootstrap-Select/issues/150

The problem is the component needs to know both value and the label for this value. And you set only the value. The ajax endpoint defines no function to fetch the label for given value - it's just know how to search.

So the only way to workaround the problem is setting both value and the label manually. Of course your application needs to know both. You can use this code for that:
```
var Select.buttonLabel: String
    get() {
        val button = input.getElementJQuery()?.next()
        return button?.prop("title").toString()
    }
    set(value) {
        val button = input.getElementJQuery()?.next()
        button?.removeClass("bs-placeholder")
        button?.prop("title", value)
        button?.find(".filter-option-inner-inner")?.html(value)
    }

class App : Application() {
    override fun start() {
        root("kvapp") {
            vPanel(spacing = 5) {
                margin = 10.px
                val select = select(value = "120835750", label = "Select with ajax data source") {
                    emptyOption = true
                    ajaxOptions = AjaxOptions("https://api.github.com/search/repositories", preprocessData = {
                        it.items.map { item ->
                            obj {
                                this.value = item.id
                                this.text = item.name
                                this.data = obj {
                                    this.subtext = item.owner.login
                                }
                            }
                        }
                    }, data = obj {
                        q = "{{{q}}}"
                    }, minLength = 3, requestDelay = 1000)
                    onEvent {
                        jqueryEvent("loaded.bs.select") { _ ->
                            self.buttonLabel = "kvision" // correct label for value "120835750"
                            true
                        }
                    }
                }
                button("Set value and label").onClick {
                    select.value = "120835750"
                    select.buttonLabel = "kvision"
                }
                button("Get value and label").onClick {
                    console.log(select.value)
                    console.log(select.buttonLabel)
                }
            }
        }
    }
}

fun main() {
    startApplication(::App, module.hot, BootstrapModule, BootstrapCssModule, BootstrapSelectModule, CoreModule)
}
```

**Comment by rjaros** [comment]
I could integrate this extension property into `Select` component itself in the next release.

**Comment by tfonrouge** [comment]
Hi Robert,

Thank you 😊 !

This is exactly what I tried: just set the internal state of the button label to the correct value, unfortunately my knowledge on these internals are growing slowly .

I'm sure that this extension will enhance the usability of this powerful select control, please add it to your next release.

best regards,

Teo

**Comment by rjaros** [comment]
I've added `selectedLabel` property, similar to the existing `selectedIndex` property.

**Comment by tfonrouge** [comment]
Thank you Robert,

I'll it check today.


best regards,

Teo

**Comment by rjaros** [comment]
It will be available in the next release.
