### ISSUE TITLE
Add complex elements in table cells.

### ISSUE THREAD

**Issue by bjonnh** [rjaros/kvision#31]
What would be the best way to add non-text things to cells? In this case I specifically wanted to add buttons in a cell.

**Comment by rjaros** [comment]
A `Cell` component is also a container (it inherits from `Tag`, which inherits from `SimplePanel`). You can add any component to it, just like to all other containers. 
Using the KVision DSL you can write:
```
        row {
            cell {
                button("col 1 button")
            }
            cell {
                button("col 2 button")
            }
            cell {
                button("col 3 button")
            }
        }
```

**Comment by bjonnh** [comment]
Of course I found just after asking:
```
cell {
                        add(button("Delete") {
                            style = ButtonStyle.INFO
                        })
                    }
```

**Comment by bjonnh** [comment]
Thanks!
