### ISSUE TITLE
Unable to get access to KVision root application injector

### ISSUE THREAD

**Issue by fsmorygo** [rjaros/kvision#310]
The usecase is that I want to have a `@Singleton` bean injected not only into `ApplicationCall`, but also access it during App initialization stage to set up some properties and run some background tasks from this singleton bean.

Only workaround I see is to have this bean as an `object MyBean` rather than a `class MyBean`, but this prevents Guice from injecting other fields into that class.

**Comment by rjaros** [comment]
Could you provide some more details? I'm not Guice expert, but I think you should be able to define your own Guice module, with configuration of your singleton (e.g. with `asEagerSingleton()` method). Then you can pass your module to `kvisionInit()` function and it will be used by KVision injector.

**Comment by fsmorygo** [comment]
I use same `Module` class, that's not a problem. The problem is that bean scope is only effective while using same `Injector`. But KVison's one is created as a local varialbe in` io.kvision.remote.KVModulesKt#kvisionInit(io.ktor.application.Application, boolean, com.google.inject.Module...)`.

Even if I create my own `Injector` with same module, it will not share any data with KVision's one and there will be 2 `@Singleton`s, one for every `Injector`

The solution could be either to init KVision with already existing `Injector`, or to expose the one KVision creates somehow.

**Comment by rjaros** [comment]
I've changed `kvisionInit()` to return the created injector. Hope this will help you. The next release should be published this weekend.

**Comment by fsmorygo** [comment]
Yes, thanks a lot for a quick fix!
