### ISSUE TITLE
kvision.io Homepage 'Get Started' link broken

### ISSUE THREAD

**Issue by prakis** [rjaros/kvision#311]
On Kvision.io Hompage clicking on 'Get Started' Button is going to 'page not found'.

Its going to the following broken link
https://kvision.gitbook.io/kvision-guide/part-1-fundamentals/setting-up

Maybe it should be refering to the following link
https://kvision.gitbook.io/kvision-guide/1.-getting-started-1/setting-up

**Comment by rjaros** [comment]
Yes, thank you for noticing!
