### ISSUE TITLE
kvision-bootstrap-select select element isn't updated properly via binding

### ISSUE THREAD

**Issue by IvanPavlov1995** [rjaros/kvision#312]
When using binding with select component, the component isn't updated correctly. It shows *previous* state instead of current one.
Code to reproduce:
```kotlin
val values = MutableStateFlow(listOf<StringPair>())
select().bind(values) { options = it }
button("Add value") {
    var count = 0
    onClick {
        values.update { it + ("$count" to "$count") }
        count++
    }
}
```
1. Click button - no options in select, state is `listOf("0" to "0")`
2. Click button - only "0" option in select, state is `listOf("0" to "0", "1" to "1")`
3. Click button - options "0" and "1" in select, state is `listOf("0" to "0", "1" to "1", "2" to "2")`

Also it's not possible to select an option in such select sometimes, but I'm not sure if it is the same bug.

**Comment by rjaros** [comment]
Fixed in 5.2.1
