### ISSUE TITLE
Auto-generated sources are not created

### ISSUE THREAD

**Issue by GrishinSergeyAl** [rjaros/kvision#319]
Hello!
I transferred the source directory to another computer and tried to compile the project. The compiler did not find any autogenerated files. The "generated-src" folder is not even created inside the "build" folder. I can't get the plugin to re-generate the sources ((

**Comment by rjaros** [comment]
Could you give some more details? Have you run `./gradlew compileKotlinMetadata` task? Does it give you any errors?

**Comment by GrishinSergeyAl** [comment]
I copy the directories 
```
  src
  webpack.config.d , 
```
and files 
```
  build.gradle.kts 
  gradlew 
  gradlew.bat 
  gradle.properties 
  settings.gradle.kts 
  app.json 
  .gettext.json 
  .gitignore 
  Procfile 
  README.md 
  system.properties 
```

Opened this project in Idea. Launched backendRun. Folders appeared in the build folder
```
classes 
kotlin 

```


> Have you run ./gradlew compileKotlinMetadata task? Does it give you any errors?
sergey@astra:/mnt/hdd_e/Programs/Kotlin/cc1$ ./gradlew compileKotlinMetadata
```

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 774ms
1 actionable task: 1 up-to-date
```

**Comment by rjaros** [comment]
You should copy `gradle` folder as well - it contains Gradle wrapper files. Also make sure you are running your build in a local directory (not on some kind of a network volume).

**Comment by GrishinSergeyAl** [comment]
Copying the Gradle folders did not help. In addition, the Idea itself creates them.

**Comment by GrishinSergeyAl** [comment]
[cc1.zip](https://github.com/rjaros/kvision/files/7555109/cc1.zip)

**Comment by rjaros** [comment]
I confirm it doesn't work as expected. I'm investigating the problem.

**Comment by rjaros** [comment]
Your project is using KVison 4.8.3 which was targeting Kotlin 1.5.10. You have upgraded to Kotlin 1.5.20 and you can't do this. The compiler plugin from 4.8.3 will not work correctly with Kotlin 1.5.20. If you want to upgrade Kotlin you need to upgrade KVision as well.
Or you can just downgrade Kotlin to 1.5.10 - your project builds fine with this version.

**Comment by GrishinSergeyAl** [comment]
I confirm it works. Thanks!
