### ISSUE TITLE
Can't seem to tell the difference between Button and button

### ISSUE THREAD

**Issue by Doenut999** [rjaros/kvision#321]
Hope the way I have written it isn't too weird, but when I create a variable of type button (small **B**) it renders simply, but when I make do the same with a **B**utton(upper case **b**), it doesn't show on the screen. Upon further inspection, I noticed that button is an extension function for **Container** and **Button** is a constructor. What I'm asking is, why the difference, and what is the Button [ constructor type] used for in Kvision

**Comment by rjaros** [comment]
https://kvision.gitbook.io/kvision-guide/2.-frontend-development-guide/ui-structure#dsl-builders
