### ISSUE TITLE
Inserting a tag within a string

### ISSUE THREAD

**Issue by Doenut999** [rjaros/kvision#323]
A line of code in the form
`p("Paragraph here"){
                content = "Kvision is great! ${tag(TAG.MARK, "though hard to start with")}"
}`

Doesn't apply the tag. Sometimes it applies the tag at the end of  the line, and it renders as some different words, like [object Object]. Thanks for the patience. Also apologise for bad formatting

**Comment by rjaros** [comment]
It's not possible to do it this way, because Kotlin string interpolation knows nothing about KVision components. There are two ways to mix tags and text content in KVision.
1. Use DSL builders and `+` operator:
```
    p {
        +"Paragraph here"
        br()
        +"KVision is great! "
        tag(TAG.MARK, "and quite easy to start with")
    }
```
2. Use `rich = true` property:
```
    p("Paragraph here<br>KVision is great! <mark>and quite easy to start with</mark>", rich = true)
```

**Comment by Doenut999** [comment]
p("Thanks sir"){
                br()
                +"KVision "
                tag(TAG.MARK, "Makes my wildest dreams come true!!")
                br()
            }
