### ISSUE TITLE
Failing to create nested table

### ISSUE THREAD

**Issue by chavu** [rjaros/kvision#328]
I'm trying to create a nested table using the tabulator's rowFomatter function. My challenge is creating and adding the sub table to the row. Checking the Tabulator library page they use the following javascript which I'm failing to do in Kotlin because I can't find a way to create the 'Node' parameter required by the row.getElement().appendChild() function.

'''
       var holderEl = document.createElement("div");
       holderEl.appendChild(tableEl);

       row.getElement().appendChild(holderEl);

       var subTable = new Tabulator(tableEl, {
           layout:"fitColumns",
           data:row.getData().serviceHistory,
           columns:[
           {title:"Date", field:"date", sorter:"date"},
           {title:"Engineer", field:"engineer"},
           {title:"Action", field:"actions"},
           ]
       })
'''

**Comment by chavu** [comment]
I managed to add a subtable using this line:

```
row.getElement().appendChild(subTable.getElement()!!)
```

**Comment by rjaros** [comment]
Hi,
Instead of using JavaScript component directly you could stay in KVision world with something like this:
```
rowFormatter = { row ->
    val holderEl = document.createElement("div")
    row.getElement().appendChild(holderEl)
    Root(holderEl.unsafeCast<HTMLElement>()) {
        // KVision code goes here ...
        tabulator(...)
    }
}
```

**Comment by chavu** [comment]
Thanks so much. Using your approach I no longer have JS errors I was getting.
