### ISSUE TITLE
Problem with row height in tabulator 

### ISSUE THREAD

**Issue by rojeras** [rjaros/kvision#332]
When the table is initially displayed the “tabulator-row” is much to high, much higher than the cells in the row. It means that only the first row is visible. If the user scroll the table the row immediately resize correctly and the full table is visible.

An inherited value need to be change. 

Temporary workaround provided:
Add the following to css file:
`.tabulator.table-sm > :not(caption) > * > * {
    padding: 0;
}`

**Comment by rjaros** [comment]
`kvision-assets-5.0.8` module has been published to npm so the issue should be fixed now (removing `.kotlin-js-store/yarn.lock` could be necessary)
