### ISSUE TITLE
How to allow client to use a post request(ktor server)

### ISSUE THREAD

**Issue by diogo10** [rjaros/kvision#34]
Hello there, thanks for sharing this framework. It is amazing.

I would like to have a client-side requesting data from server-side(ktor). The server-side will be API. See below, a sample...

<img width="561" alt="Screenshot 2019-04-18 at 13 17 34" src="https://user-images.githubusercontent.com/1541244/56360374-5cd9fc80-61dc-11e9-9a11-b1cef6a6df34.png">

I got a Forbidden(403) request when I try to use the POST method. The GET function works fine.

<img width="561" alt="Screenshot 2019-04-18 at 13 17 34" src="https://user-images.githubusercontent.com/1541244/56360446-91e64f00-61dc-11e9-8f50-7b0b58ef5254.png">

![Screenshot 2019-04-18 at 13 20 23](https://user-images.githubusercontent.com/1541244/56360512-c528de00-61dc-11e9-979a-efafe1ed69d7.png)

How can I get it to work? Am I missing a config here?

**Comment by rjaros** [comment]
What's your client side code?
I'm not sure if you are trying to use server-side interfaces of kvision or if you are creating your api endpoints manually? Because on this screenshots I see a mix of those two.

**Comment by diogo10** [comment]
The client-side is kvision. I took the numbers-fullstack-ktor template samples as a start point. And then, I was trying to create a simples get API using the ktor server on the same project.

Sorry if I miss some info.

**Comment by rjaros** [comment]
The fullstack examples are all dedicated to show how kvision's server-side interfaces work. These interfaces allow you to make client connections to the server without writing any get/post endpoints manually. You just declare an interface in the common part, add some "boilerplate" code in the form of ServiceManager objects, implement the interface on the client and the server part and then just call Kotlin methods. You can read about those interfaces in the [Part 3 of the KVision Guide](https://app.gitbook.com/@kvision/s/kvision-guide/part-3-server-side-interface).

On the other hand you can of course create any api manually, and then just use it with kvision's [RestClient class](https://rjaros.github.io/kvision/api/pl.treksoft.kvision.rest/-rest-client/index.html). All RestClient methods (`call` and `remoteCall`) have a `method` parameter which has default value `HttpMethod.GET`. Just use `HttpMethod.POST` value and it will work with POST endpoints.

**Comment by diogo10** [comment]
Humm ok, Thanks for that. I got it right now. 

Nice work! Just love it already
