### ISSUE TITLE
Using RestClient - turn off serialization

### ISSUE THREAD

**Issue by benbve** [rjaros/kvision#341]
Hi,

I'm attempting to replace a JS front end with KVision which needs to talk to an existing backend. Thus I need to use the RestClient.

However, I want to send a JSON String for the "data" in the call. Issue is when I send a JSON String (the type that some from JSON.Stringify what is received on the backend is a String withing a String)

Thus
`val rc = RestClient()
 rc.post<String,String>(purl, fdata) {
     contentType = "application/json"
 }`

where "fdata" is something like "{ "aname": "b" }"

is received on the backend as
""{\"aname\":\"b\"}""

Which does not parse correctly since it's a string wrapped in a String.

It appears serialization is wrapping the json string in a string - can serialization be turned off?

**Comment by rjaros** [comment]
Unfortunately currently there is no way to disable serialization. When the `contentyType` is set to `application/json` the `data` parameter is expected to contain raw data, which will be stringified with the kotlinx.serializer or `JSON.stringify()` native JS function. If your data is originally a `String` you can just call `JSON.parse(data)` first. I can also add a new option to `RestRequestConfig` if you want.

**Comment by benbve** [comment]
Thanks Robert.  I thought it best to check.  Not familiar with Kotlin serialization at this stage and as long as it can handle complex structures then I can likely handle it all with data classes.  No need to add option yet.

Love your work so far and am keen to get Kvision-Ktor full stack running soon
