### ISSUE TITLE
Configure custom serialization modules

### ISSUE THREAD

**Issue by rocketraman** [rjaros/kvision#342]
There should be a way to configure kvision-remote with one or more custom `SerializersModule`'s. This would allow serializing / deserializing classes that require additional configuration.

Without this capability, it is impossible to use several features of kotlinx-serialization, including open polymorphism.

**Comment by rjaros** [comment]
There are two methods of using custom serialization modules. You can pass a list of modules as parameter to client side service constructor on the client side and as the parameter to the `applyRoutes()` function (for Ktor, Javalin, Jooby, Vert.x) or via dependecy injection (for Spring Boot and Micronaut).
Alternatively you can set `RemoteSerializaton.customConfiguration = ...` even in the common module and it will be automatically applied to both client and server serialization.

**Comment by rjaros** [comment]
Released with 5.8.0
