### ISSUE TITLE
TypeError: targets.row.findCell for button inside a tabulator

### ISSUE THREAD

**Issue by chavu** [rjaros/kvision#344]
I am getting the error below when I click any button inside a tabulator column cell.

```
Uncaught TypeError: targets.row.findCell is not a function
    at InteractionManager.bindComponents (tabulator_esm.js?c148:21446:1)
    at InteractionManager.track (tabulator_esm.js?c148:21371:1)
``

**Comment by rjaros** [comment]
Do you mean KVision `Button` inside `formatterComponentFunction`? How do you define it?

**Comment by rjaros** [comment]
Unfortunately I can't reproduce. I've used exactly your code (both versions), just removing some undefined stuff and I can click buttons without any problems. 
So the questions now:
- what KVision version do you use?
- which tabulator module?
- which compiler backend (IR or legacy)?
- do you have any custom even handlers for other cells or rows?
- can you post more lines of your error stacktrace?
