### ISSUE TITLE
How can  convert KFIle to java.File object

### ISSUE THREAD

**Issue by chavu** [rjaros/kvision#347]
I'm trying to upload an Excel file and process it using apache.poi. My current approach is to use the Kvision's FileUpload component client  side file handling and call a backEnd service method passing the KFile object. My challenge now is at backend, apache.poi fucntion to create a Excel workbook require a java.File type. How do I convert the Kfile to java File? Is this approach the recommended way?

**Comment by rjaros** [comment]
Apache POI `WorkbookFactory` allows you to create workbook both from `File` and `InputStream`. It will be easier to just decode KFile's content to a stream.
```kotlin
val kFile: KFile = ...
val stream = kFile.content?.split(",")?.getOrNull(1)?.let { Base64.getDecoder().decode(it) }?.inputStream()
if (stream != null) {
    val workbook = WorkbookFactory.create(stream)
    // ...
}
```

**Comment by rjaros** [comment]
I've added some new extension functions and properties to work with `KFile objects`. Please look at the commit above. 
With the new release it will be possible to just call `kFile.inputStream`, `kFile.byteArray` or `kFile.contentType`.
