### ISSUE TITLE
Tabulator table totals

### ISSUE THREAD

**Issue by chavu** [rjaros/kvision#351]
Since totals and groupings are not yet implemented for the Tabulator table. What's the recommended and fastest way to add totals row at the bottom of the table?

**Comment by rjaros** [comment]
Perhaps I don't understand correctly, but please specify how this question differs from #346 ?

**Comment by rjaros** [comment]
Oh I see! :-) You want to use column calculations (http://tabulator.info/docs/5.1/column-calcs)
Most of calculations parameters is implemented in KVision component, e.g. you can add `bottomCalc = Calc.SUM` to your `ColumnDefinition` to display sum in the last row.

**Comment by chavu** [comment]
This worked. thanks.
