### ISSUE TITLE
How to validate form fields?

### ISSUE THREAD

**Issue by chavu** [rjaros/kvision#352]
I am trying to put a simple ' field required' validartion my forms but the not working as expected. I have some form panels defined  in Forms.kt file.  as below.
```
class FunctionalAreaFormPanel() : FormPanel<FunctionalArea>(
    type = FormType.HORIZONTAL,
    method = FormMethod.GET,
    action = "form",
    enctype = FormEnctype.MULTIPART,
    serializer = FunctionalArea.serializer()
) {
    init {
        add(
            FunctionalArea::code,
            Text(label = "Code") { placeholder = "Enter TestCase Grouping Code" },
            required = true,
            requiredMessage = "This field is required",
        )
        add(FunctionalArea::name,
            Text(label = "Name") { placeholder = "Enter TestCase Grouping Name" },
            required = true,
            requiredMessage = "This field is required",
        )
    }

```

Then I use this form in another file called ProjectView.kt as below. I called teh validate() method inside the Save onclick handler but this is not preventing submission of empty fields.

```
   val launchAddFunctionalAreaDialog = fun(projectId: String) {
        var myForm : FormPanel<FunctionalArea>
        var validationResult:  Boolean
        var newFunctionalArea: FunctionalArea

        val dialog = Dialog<FunctionalArea>(caption = "New Functional Area", size = ModalSize.LARGE, closeButton = true)
        myForm = TestCaseFunctionalAreaFormPanel()

        newFunctionalArea = FunctionalArea(null,"","",projectId)
        myForm.setData(newFunctionalArea)
        validationResult = myForm.validate(true)
        dialog.add(myForm)
        dialog.addButton(Button("Save").onClick {
            validationResult = myForm.validate(true)
            if (validationResult) {
                dialog.setResult(myForm.getData())
            }
        })
        dialog.show()
        appScope.launch {
            validationResult = myForm.validate(true)
            newFunctionalArea = dialog.getResult()!!
            if (newFunctionalArea != null) {

                UatManager.addFunctionalArea(newFunctionalArea)
            }
        }
    }

```

**Comment by tfonrouge** [comment]
Hi Lenny,

The validations are correctly defined in the class FunctionalAreaFormPanel, however in your implementation you're using a different class 'TestCaseFunctionalAreaFormPanel':

        myForm = TestCaseFunctionalAreaFormPanel()

May be If this class has not form-validation then this can be the source of the problem.


Best regards,

Teo

**Comment by chavu** [comment]
No. I changed the name of the teh formPAnel class when I pasted in this issue form and forgot to change it on the dialog. But in my code they're aligned and still not working.

**Comment by chavu** [comment]
Also another related question: How/where do I specify the "required = true" when using custom binding like below.

```
                functionalAreaElement = simpleSelect(
                    label = "Func. area",
                      options = state.functionalAreaCollection.map { item -> Pair(item.id.toString(), item.name!!) }
                ) {
                    value = null
                    width = 14.perc
                }.bindCustom(IssueLogFilterFormModel::functionalArea)
```

**Comment by tfonrouge** [comment]
bindCustom( key = IssueLogFilterFormModel::functionalArea, required = true)    ?


Best regards,

Teo

**Comment by chavu** [comment]
Thanks [tfonrouge]. I await your help  on the  first issue.

**Comment by tfonrouge** [comment]
Hi Lenny,

Your example runs well for me, at least it returns the correct value for the 'validationResult' value when you click "Save" to false if the fields are empty.

<img width="640" alt="Screen Shot 2022-02-07 at 15 46 21" src="https://user-images.githubusercontent.com/1561244/152877309-a5650970-d154-4d64-adaf-ad8069864d7c.png">

The validation properties for the fields in your FunctionalAreaFormPanel class are correctly working, attached you'll find my test.

May be the error is in another place on your project.

Best regards,

Teo

[App.kt.zip](https://github.com/rjaros/kvision/files/8019014/App.kt.zip)

**Comment by chavu** [comment]
I have check again I narrowed it down to the line below. When commend it out the validation works. 
```
 myForm.setData(newFunctionalArea)
```
I was using it to set projectId value field which should not be populated by the user.  I'm now setting it  after getting the form result from dialog. And it works okay, at least for this form. 

Thanks for your help.

**Comment by rjaros** [comment]
I think you are setting "" (an empty string) as the initial field value and that'a why it's treated as not-null. In KVision empty fields return `null` values and those `null`s are checked by the required validator. Your empty string will be converted to `null` only after some interaction with the form (by the `change` event listener). I'll check if this could be implemented a bit better.

**Comment by rjaros** [comment]
I've fixed text inputs to always return null values when empty.
