### ISSUE TITLE
How to convert from java File to KFile?

### ISSUE THREAD

**Issue by chavu** [rjaros/kvision#353]
Below is the function I created to read file and return a KFile. This function will be called by a service method to retun the Kfile object to the frontend app. 

```
 fun getFile(path: String): KFile{
        var kFile: KFile? = null
       val file = File(path)
       kFile = KFile(
           name = file.name,
           content = file.outputStream().toString(),
           size = 0
       )
        return kFile
    }
```
1. Is this the correct way to convert from file to KFile. 
2. How do I determine the 'size' property? 
3. At the front-end, how do I enable user to view the file in browser (images and pdf) or download for other file types?

**Comment by rjaros** [comment]
Hi,
The `outputStream().toString()` is definitely wrong and won't give you usable result. If you really want to transfer file content from the backend to the frontend you should use base64 encoding:
```
content = Base64.getEncoder().encodeToString(file.readBytes())
```
Having base64 encoded content on the client side you have a few different ways of handling this. I've personally been using  https://www.npmjs.com/package/file-saver JS library with similar code:
```kotlin
            val fileSaver = require("file-saver")
            val base64Content = ... // base64 encoded content from the server
            val url = "data:image/png;base64,$base64Content"
            button("Save as PNG").onClick {
                window.fetch(url).then { it.blob() }.then {
                    fileSaver.saveAs(it, "fileName.png")
                }
            }
```

**Comment by rjaros** [comment]
And generally in my opinion it's not very good idea to transfer file content to the client application just to download it by the user. The server and the browser are the tools already designed for this task :-) So I would just create an endpoint on the server which serves the file and redirect user to this endpoint (perhaps with some temporary random token parameter to distinguish different files).

**Comment by chavu** [comment]
Thank you for the quick response and the recommendation. Let me try this out and will give update.  You didn't respond to ite, 2) WHat is that 'size' required. I checked the API docs but could find it explained.

**Comment by rjaros** [comment]
`KFile` type is designed to get the file data from the `Upload` component and to transfer data from the client to the server. I've never planned to create `KFile` objects manually :-)
But if you need, the `size` property is just for the file length, so it can be initialized with byte array size or `File.length().toInt()`
