### ISSUE TITLE
Handle exception hierarchies

### ISSUE THREAD

**Issue by rocketraman** [rjaros/kvision#354]
It would be great if KVision remoting could handle user-defined exception hierarchies, or alternatively, have a way to send a custom serializable payload in an exception.

Slack thread reference: https://kotlinlang.slack.com/archives/CL4C1SLKC/p1644502241357749

**Comment by rjaros** [comment]
You can now declare user-defined exceptions inherited from `AbstractServiceException`
```
@Serializable
class MyFirstException(override val message: String) : AbstractServiceException()

@Serializable
class MySecondException(override val message: String) : AbstractServiceException()
```
Initialize serialization configuration for them with a function in the common module:
```
fun initSerialization() {
    RemoteSerialization.customConfiguration = Json {
        serializersModule = SerializersModule {
            polymorphic(AbstractServiceException::class) {
                subclass(MyFirstException::class)
                subclass(MySecondException::class)
            }
        }
    }
}
```
Call this function on both the frontend and the backend (e.g. in `main()`)
And then you should be able to throw custom exceptions on the backend side and catch them on the frontend side.

**Comment by rjaros** [comment]
Released with 5.8.2

**Comment by tomwyr** [comment]
It would be super helpful to have it documented in the guide for newcomers.

**Comment by rjaros** [comment]
It is documented here: https://kvision.gitbook.io/kvision-guide/6.-full-stack-development-guide/exception-handling#user-defined-exceptions
It's just simpler now - you no longer need to manually register exceptions - just use `@KVServiceException` annotation.

**Comment by tomwyr** [comment]
I misunderstood the issue initially, you're right. I'm struggling right now with modelling my error hierarchy using sealed classes:
```kotlin
sealed class MyFirstException : AbstractServiceException()
class MySecondException : MyFirstException()
class MyThirdException : MyFirstException()
```

@rjaros Should the deserialization be possible out of the box in such case as well? Because the above so far gives me:
```
Serializer for LateServiceException can't be registered as a subclass for polymorphic serialization because its kind SEALED is not concrete. To work with multiple hierarchies, register it as a base class.
``` 
which I'm not sure yet how to deal with.

**Comment by rjaros** [comment]
This should work:
```kotlin
@Serializable
sealed class MyFirstException : AbstractServiceException()
@KVServiceException
class MySecondException : MyFirstException()
@KVServiceException
class MyThirdException : MyFirstException()
```

**Comment by tomwyr** [comment]
Tried the above but when one of the exception is returned from a call, I get the following exception on the server side:
```
kotlinx.serialization.SerializationException: Class 'CurrentStreamUnavailable' is not registered for polymorphic serialization in the scope of 'AbstractServiceException'.
To be registered automatically, class 'CurrentStreamUnavailable' has to be '@Serializable', and the base class 'AbstractServiceException' has to be sealed and '@Serializable'.
Alternatively, register the serializer for 'CurrentStreamUnavailable' explicitly in a corresponding SerializersModule.
```

The error hierarchy is declared as follows:
```

@Serializable
sealed class LateServiceException(override val message: String) : AbstractServiceException() {
    @KVServiceException
    data object CurrentStreamUnavailable : LateServiceException("Unable to retrieve current stream data. Please try again later.")

    @KVServiceException
    data object NewestVideoUnavailable : LateServiceException("Unable to retrieve newest video data. Please try again later.")
}
```

**Comment by rjaros** [comment]
Currently our KSP processor only supports top level classes when processing `@KVServiceException` annotations.

**Comment by tomwyr** [comment]
I was able to properly deserialize the response after switching to top level classes. Thanks for looking into this @rjaros. Amazing work with this project.
