### ISSUE TITLE
Compiler errors after deleting KVService interface

### ISSUE THREAD

**Issue by rocketraman** [rjaros/kvision#355]
Currently if a KVService interface is deleted, you end up with compile errors because the corresponding generated classes are not removed.

This requires a manual `rm` of those specific generated files, or a clean of the entire build directory.

Ideally, this would not be an issue.

**Comment by rjaros** [comment]
I've tried, but it's not possible, because of some issues with currently used annotation processor. I'll probably try to migrate to KSP in the near future so I'm leaving this issue open.

**Comment by rjaros** [comment]
Should work fine now with the new KSP processor.
