### ISSUE TITLE
How to update tabulator row data without re-rending whole table 

### ISSUE THREAD

**Issue by chavu** [rjaros/kvision#359]
I'm using redux state property to populate tabulator table. I use a form in dialog window to enable user to edit a single record in the table. After submiting/saving form data the whole page and table are being reloaded and filters are reset. How can I make sure that the page and table are not reload but only the updated row is re-rended?

**Comment by rjaros** [comment]
Do you use built-in Tabulator component data binding? As you can see here:
https://github.com/rjaros/kvision/blob/master/kvision-modules/kvision-tabulator/src/main/kotlin/io/kvision/tabulator/Tabulator.kt#L862 
the `Tabulator.replaceData()` method is used. According to the [tabulator documentation](http://tabulator.info/docs/5.1/update#alter-replace) it should not reset tabulator state.
