### ISSUE TITLE
Pie chart ChartJS 2 -> 3 sizing options missing

### ISSUE THREAD

**Issue by drammelt** [rjaros/kvision#361]
In chartjs 2 module the pie charts scaled with the surrounding div and was responsive as per...
![Screenshot from 2022-03-31 11-44-40](https://user-images.githubusercontent.com/11844017/160944600-c0d5c726-a2cd-4cf4-a707-219e417a5c74.png)

However since upgrading to chartjs 3 the pie charts appear to be fixed size. Even if I try to force div height to 200 using chartjs 3 this is the result.
![Screenshot from 2022-03-31 11-44-00](https://user-images.githubusercontent.com/11844017/160944739-c6c60a81-58e6-444b-91dd-1200a604429e.png)

I cannot find anywhere to specify the radius/scale size for the chart. PieControllerChartOptions does not contain these options.

Using chartjs directly it is possible to set the radius under options...
```
const config = {
  type: 'pie',
  data: data,
  options: {
    radius: 50 // pixels or "50%"
  }
};
```
https://www.chartjs.org/docs/latest/charts/doughnut.html#pie

**Comment by rjaros** [comment]
Chart.js usues namespaces to allow setting the same options in different places. KVision limits this a bit, because of more static typing. Currently you should be able to set the same `radius` option within `datasets` namespace:
```Kotlin
        Configuration(
                ChartType.PIE,
                listOf(
                    DataSets(
                        data = ...,
                        radius = listOf(50)
                    )
                )
        )
```
I've added some more dynamic configuration parameters, so you would be able to do:
```Kotlin
        Configuration(
                ChartType.PIE,
                listOf(
                    DataSets(
                        data = ...,
                    )
                ), optionsDynamic = obj {
                    radius = 50 // or even "50%"
                }
        )
```
or
```Kotlin
        Configuration(
                ChartType.PIE,
                listOf(
                    DataSets(
                        data = ...,
                    )
                ), options = ChartOptions(
                    datasets = obj {
                        pie = obj {
                            radius = 50
                        }
                    }
                )
        )
```
in the next release.

**Comment by drammelt** [comment]
I tried this but it does not behave correctly, the parent container height is still sized as if you did not set a radius which breaks the layout.
![Screenshot from 2022-04-01 05-13-03](https://user-images.githubusercontent.com/11844017/161101742-0f4ab698-b92f-4d00-a2f4-d75e357c628f.png)

However, it would be nice if the chart just used flex sizing when specified and followed the parent container size as per the old version of kvision-chart2, and the other charts like LINE in the current version of kvision-chart.

**Comment by rjaros** [comment]
Please try to specify `maintainAspectRatio = false` option.

**Comment by drammelt** [comment]
This works thank you, I could not find any mention of this in the chartjs 2 -> 3 migration notes. Was this a change on their end and KVision followed the new default?

**Comment by rjaros** [comment]
There is one mention in the [guide](https://www.chartjs.org/docs/latest/getting-started/v3-migration.html#specific-changes) about `aspectRatio` default value for doughnut, pie, polarArea, and radar charts. I assume it's the reason of this different behavior.

**Comment by drammelt** [comment]
Ok thank you very much for your help.
