### ISSUE TITLE
Please remove assumption that multimodule project will have a backend

### ISSUE THREAD

**Issue by reubenfirmin** [rjaros/kvision#364]
I am experimenting with multimodule instead of js in order to build a webworkers project (it will end up with two js modules). It seems that the kvision plugin has an assumption that multimodule projects will always have a backend. Can this be optional? 

> Task with name 'compileKotlinBackend' not found in root project 'myproject`

Thanks

**Comment by rjaros** [comment]
I've implemented `io.kvision.plugin.enableBackendTasks=false` property in 5.9.0.
