### ISSUE TITLE
Window close/minimize/maximize buttons are not rendered properly

### ISSUE THREAD

**Issue by mgrouch** [rjaros/kvision#365]
Window close/minimize/maximize buttons are not rendered properly.

I've tried adding them in Showcase example 

Thanks

**Comment by mgrouch** [comment]
The code of CloseIcon.kt looks very different from MaximizeIcon.kt and MinimizaIcon.kt

**Comment by rjaros** [comment]
Why do you think they are not rendered properly? They look ok to me (tested firefox and chrome on linux). 
The buttons are used in the desktop example:
https://rjaros.github.io/kvision-examples/desktop/
My screenshot:
![buttons](https://user-images.githubusercontent.com/5646804/163235179-c6e707d1-2bb9-4937-9c68-32c2711da758.png)

Can you make your own  screenshot with an explanation?

**Comment by rjaros** [comment]
The code is different because close icon is built-in in Bootstrap css. Maximize and minimize icons are not.

**Comment by mgrouch** [comment]
Somewhat weird that I have to style Close and Minimize/Maximize buttons very differently.
