### ISSUE TITLE
zIndexCounter is private in Window

### ISSUE THREAD

**Issue by mgrouch** [rjaros/kvision#369]
But I need to detect if DesktopWindow is on front on not. I could have done it comparing DesktopWindow zIndex with zIndexCounter,
but it is 'private'

In general making things 'private' in a framework makes it difficult to enhance it by subclasses.

I've read this https://stackoverflow.com/questions/1118198/how-can-you-figure-out-the-highest-z-index-in-your-document
but I haven't found way to get Document object via KVision APIs (sorry just learning and starting with it)

Thanks

**Comment by rjaros** [comment]
The `zIndexCounter` is an implementation detail, so it should be private. What you need is a `Window.isActive(): Boolean` method, which is a great feature request. 
BTW just comparing with `zIndexCounter` is not good enough as you can close active windows as well.

**Comment by mgrouch** [comment]
Yes. isActive() is needed.

Also isOverlapped() is needed. There is native JS way 

https://stackoverflow.com/questions/32713250/how-to-detect-if-an-element-is-covered-overlapped-by-another-one

I can't just figure out how to get JS Element of the window in  kvision API and pass it into native javascript via js()

Thanks

**Comment by rjaros** [comment]
For every KVision component you can use `getElement()` method, which returns underlying DOM element. You just need to know this method can return `null`, because elements are created by a virtual DOM library only when it's needed. Check https://kvision.gitbook.io/kvision-guide/2.-frontend-development-guide/dom-bindings for more info about components lifecycle.

**Comment by mgrouch** [comment]
I couldn't figure out how to pass result of getElement() into native javascript function in Kotlin.
js() one.

Thanks

**Comment by rjaros** [comment]
Generally you should use `js()` as a "last resort" for some very specific tasks. For all other things just use Kotlin code (via external declarations or dynamic typing).

**Comment by rjaros** [comment]
I've implemented `isActive()` and component function `Window.getActiveWindow()` for the next release
https://github.com/rjaros/kvision/commit/98b46a72a87065c1c07613c1372f501f7d5df35c

**Comment by rjaros** [comment]
Released with 5.10.0
