### ISSUE TITLE
Options (Chart) now conflicts with Options (Tabulator)

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#37]
I guess the fix is a simple rename of the modules to something like ChartOptions and TabulatorOptions. It would only come up if you were to use both in the same namespace.

**Comment by robert-cronin** [comment]
For charts there exists already a ChartOptions interface in the pl.treksoft.kvision.chart.js package so I'm not sure if the rename will affect this but I would guess not. I've submitted a PR, feel free to rename them or ignore it completely if you feel there's a good reason to keep it that way 👍

**Comment by rjaros** [comment]
Will you create also PR for the guide and for the examples (addressbook-tabulator and showcase)?

**Comment by robert-cronin** [comment]
certainly, I shall create one today

**Comment by robert-cronin** [comment]
PR reference: https://github.com/rjaros/kvision-guide/pull/2#issuecomment-489477506
