### ISSUE TITLE
Add onClose to Modal

### ISSUE THREAD

**Issue by micHar** [rjaros/kvision#371]
Hello Robert 👋 

Please consider adding `onClose` callback to `Modal`. The reason is that we might want to call some side effect upon the modal being closed by the default button.

Right now I'm doing something like this:

```
class ExtendedModal(
    caption: String? = null,
    closeButton: Boolean = true,
    size: ModalSize? = null,
    animation: Boolean = true,
    centered: Boolean = false,
    scrollable: Boolean = false,
    escape: Boolean = true,
    className: String? = null,
    init: (Modal.() -> Unit)? = null,
    private val onClose: (() -> Unit)? = null
) : Modal(
    caption, closeButton,
    size, animation, centered,
    scrollable, escape,
    className, init
) {

    override fun hide(): Widget {
        onClose?.invoke()
        return super.hide()
    }

}
```

If you agree with that, I can prepare pull request.

**Comment by rjaros** [comment]
Why don't you use bootstrap events? The example in the guide is just about modals:
https://kvision.gitbook.io/kvision-guide/2.-frontend-development-guide/events#bootstrap-custom-events

**Comment by micHar** [comment]
Just because I'm absolutely new both to web frontends and kotlin js :) 
Makes sense, thank you for the hint!
