### ISSUE TITLE
Hard to use navbar with submenus with just a keyboard 

### ISSUE THREAD

**Issue by mgrouch** [rjaros/kvision#376]
It’s very difficult to use the apps generated by framework without mouse with just a keyboard. Natural way to navigate via menus would be keyboard arrows. Switching focus between windows with keyboard is not clear how to do. 
Thanks

**Comment by rjaros** [comment]
KVision currently doesn't address desktop-like keyboard support at all. With typical websites and web applications the general requirement is WCAG accessibility, which usually comes down to sane TAB navigation between components and some sort of concise keyboard support in advanced controls (like date picker, select etc.).

But of course nothing stands in the way of implementing advanced keyboard support for menus. All menus are components with open/close methods. You would have to listen to some keyboard events and implement the appropriate handlers.

**Comment by mgrouch** [comment]
In current desktop example when I click on 'Menu' I can't go down the menu with keyboard arrow 'down'
even if I select with a mouse an item in menu dropdown I can't navigate with keyboard arrow 'down'

I'll try to work on the desktop example to improve it when I get some more time available.

**Comment by mgrouch** [comment]
I've looked at bootstrap examples of dropdowns. They work just fine with keyboard.

**Comment by rjaros** [comment]
The menu in the desktop example just doesn't have any links or buttons, which would allow keyboard navigation. In this case it's enough to add `#` as the urls of all these links:
```Kotlin
ddLink("Calculator", "#", icon = "fas fa-calculator").onClick {
    Calculator.run(this@root)
}
```

**Comment by mgrouch** [comment]
OK. Thanks. It works

**Comment by mgrouch** [comment]
In general 'roles' do they have to be set for keyboard to be handled? On bootstrap components?
Thanks

**Comment by rjaros** [comment]
In general 'roles` are designed to support screen readers. But I'm not an expert, so there may be some kind of keyboard support as well.
