### ISSUE TITLE
Error distributing Fullstack: Browser shows "POST http://localhost:8000/kv/routePingServiceManager0 501 (Unsupported method ('POST'))"

### ISSUE THREAD

**Issue by tfonrouge** [rjaros/kvision#377]
Hello,

As subject I'm getting the above error when creating the distributing files with './gradlew jar'

Testing with a simple "Ktor full stack project" with current KVision plugin on current IntelliJ Idea

* KVision 5.9.0
* Kotlin 1.6.20
* Serialization version 1.3.2
* KTor 2.0.0

Tests made on Mac OS X and Raspberry Pi (Raspbian 11 (bullseye))

Under the IDE the fullstack project works ok, only when you create the distribution files and run it then it fails with the error the console, and in the browser doesn't appear the return message from the ping service.
<img width="893" alt="Screen Shot 2022-04-22 at 10 23 10" src="https://user-images.githubusercontent.com/1561244/164745392-6a21abbe-2098-4ea9-9164-03445c986021.png">

**Comment by rjaros** [comment]
I've tested creating new Ktor project and the distibution jar works ok for me. Are you sure you are using latest version of the KVision Project Wizard plugin (0.4.0)? If yes, could you please zip and send me the whole project which was generated by the plugin (without the `build` subfolder)?

**Comment by tfonrouge** [comment]
Forgot to answer you: I've builded this project with the 0.4.0 Kvision wizard plugin

**Comment by rjaros** [comment]
I've cloned your project, executed `./gradlew jar` and run `java -jar build/libs/rbpiHmi-1.0.0-SNAPSHOT.jar` without any problems. I've tested with both JDK 1.8 and 11 to be sure.

**Comment by rjaros** [comment]
Do you see anything in Ktor logs?

**Comment by tfonrouge** [comment]
Nothing out of common:

[2022-04-22 11:40:05,137]-[main] INFO  Application - No ktor.deployment.watch patterns match classpath entries, automatic reload is not active
[2022-04-22 11:40:05,735]-[main] INFO  Application - Application auto-reloaded in 0.595 seconds.
[2022-04-22 11:40:06,016]-[DefaultDispatcher-worker-1] INFO  Application - Responding at http://0.0.0.0:8080

I'm using python3 -m http.server ...

Oh mi gosh... sorry . I've just guessed what the problem is...

I need to give the proxy address for the backend process....

My fault ... :-(

Sorry for make you loose your time in this dumb error of mine.

thank you and best regards ...
