### ISSUE TITLE
Frontend service not starting

### ISSUE THREAD

**Issue by chavu** [rjaros/kvision#378]
I created a new project using the Kvision wizzard and when I try to run it, the frontend service is not starting giving the error message below.

```
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 34s
10 actionable tasks: 7 executed, 3 up-to-date

Waiting for changes to input files of tasks... (ctrl-d then enter to exit)
[webpack-cli] Unable to load '@webpack-cli/serve' command
[webpack-cli] TypeError: options.forEach is not a function
[webpack-cli] TypeError: options.forEach is not a function
    at WebpackCLI.makeCommand (E:\DEV_PROJECTS\CMIS\build\js\node_modules\webpack-cli\lib\webpack-cli.js:108:21)
    at ServeCommand.apply (E:\DEV_PROJECTS\CMIS\build\js\node_modules\@webpack-cli\serve\lib\index.js:42:19)
    at loadCommandByName (E:\DEV_PROJECTS\CMIS\build\js\node_modules\webpack-cli\lib\webpack-cli.js:797:35)
    at Command.<anonymous> (E:\DEV_PROJECTS\CMIS\build\js\node_modules\webpack-cli\lib\webpack-cli.js:1255:23)
    at Command.listener [as _actionHandler] (E:\DEV_PROJECTS\CMIS\build\js\node_modules\commander\index.js:922:31)
    at Command._parseCommand (E:\DEV_PROJECTS\CMIS\build\js\node_modules\commander\index.js:1503:14)
    at Command.parse (E:\DEV_PROJECTS\CMIS\build\js\node_modules\commander\index.js:1292:10)
    at Command.parseAsync (E:\DEV_PROJECTS\CMIS\build\js\node_modules\commander\index.js:1318:10)
    at WebpackCLI.run (E:\DEV_PROJECTS\CMIS\build\js\node_modules\webpack-cli\lib\webpack-cli.js:1287:28)
    at runCLI (E:\DEV_PROJECTS\CMIS\build\js\node_modules\webpack-cli\lib\bootstrap.js:11:19)
```

**Comment by rjaros** [comment]
Are you using current version of the KVision Project Wizard - 0.4.0?

**Comment by chavu** [comment]
> 

Yes using v 0.4.0 of 15 Apr-2022

**Comment by rjaros** [comment]
> What i know is that I used same folder name of an old project done using a different dev platform called Jmix after I had deleted it first. Another thing is that I upgraded Kotlin after generating the project. Anyway I tried it for the second time and it is generating correct config.

OK. So I'm closing the issue.
 
> Out of interest is java 1.8 the recommended java version?

Works fine with JDK 11 as well. 
I haven't tried newer JDKs myself (I keep supporting some older, 1.8-only systems and don't like to switch too often ;-)

**Comment by chavu** [comment]
But it's now failing to locate io.ktor:ktor-auth:2.0.0

```
A problem occurred configuring root project 'cmis'.
> Could not resolve all files for configuration ':backendRuntimeClasspath'.
   > Could not find io.ktor:ktor-auth:2.0.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/io/ktor/ktor-auth/2.0.0/ktor-auth-2.0.0.pom
       - https://jcenter.bintray.com/io/ktor/ktor-auth/2.0.0/ktor-auth-2.0.0.pom
       - file:/C:/Users/hp/.m2/repository/io/ktor/ktor-auth/2.0.0/ktor-auth-2.0.0.pom
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

```

**Comment by rjaros** [comment]
`build.gradle.kts` seems to be old as well - please check this commit to see correct dependencies: 
https://github.com/rjaros/kvision-examples/commit/1594f789c043bf6a203db3ee8ed2f8631ad75f5f#diff-ef747d391de7684d15b930b13c3b893677eef9397906fec039770aaf031a8d68

**Comment by rjaros** [comment]
And I won't be surprised if your `Main.kt` is also wrong:
https://github.com/rjaros/kvision-examples/commit/1594f789c043bf6a203db3ee8ed2f8631ad75f5f#diff-766190aff329e3f31e067bfc9c82b5f55ca1eda3f3f2d5976c04c9df395d5094

**Comment by rjaros** [comment]
And this definitely shouldn't have happened with the project wizard 0.4.0. Perhaps this is some caching issue.

**Comment by chavu** [comment]
You're right @rjaros , my apologies,  the Kvision wizzard version was 0.3.0. I didn't check the version correctly. In IntelliJ plugins screen I searched under "Marketplace" tab instead of "Installed" tab. I have upgraded to 0.4.0 it's generating  config files correctly
