### ISSUE TITLE
Tabulator to show model List<List<String>> doesn't fill cells with values

### ISSUE THREAD

**Issue by mgrouch** [rjaros/kvision#379]
All examples seems to assume List<Bean>.
But what if I just have List<String> instead of Bean. Basically matrix of Strings.

Thanks

**Comment by rjaros** [comment]
Generally you need a class to be able to designate field names. But you can use indexes if you want. Just provide a serializer to your `Tabulator` component, so it could correctly convert your matrix to JS arrays. This works for me:
```Kotlin
            val data = listOf(listOf("A", "B", "C"), listOf("D", "E", "F"), listOf("G", "H", "I"))
            tabulator(
                data,
                options = TabulatorOptions(
                    columns = listOf(
                        ColumnDefinition("First", "0"),
                        ColumnDefinition("Second", "1"),
                        ColumnDefinition("Third", "2")
                    )
                ), serializer = ListSerializer(String.serializer())
            )

```

**Comment by mgrouch** [comment]
Thanks

In my case I needed ListSerializer(String.serializer()).nullable()

Thanks
