### ISSUE TITLE
Redux sample or template project

### ISSUE THREAD

**Issue by chavu** [rjaros/kvision#380]
Do you have a sample or template project that shows best practices for implementing  redux state managemnt especially in a project that uses complex (stepped/tabbed) forms and tabulator tables.

**Comment by rjaros** [comment]
Unfortunately all my more complex apps are commercial and I can't share the code. But if you want to talk about this, the best place would be Slack or Discord channel.

**Comment by chavu** [comment]
> You may want to have a look at:
> 
> * https://github.com/apache/isis/blob/master/incubator/clients/kroviz/adoc/modules/kroviz/pages/DevelopmentGuide.adoc and
> * https://github.com/apache/isis/blob/master/incubator/clients/kroviz/adoc/modules/kroviz/partials/design/uml-overview.png
> 
> It's still work in progress, though.

I don't see anything to do with redux in these two links

**Comment by chavu** [comment]
> Unfortunately all my more complex apps are commercial and I can't share the code. But if you want to talk about this, the best place would be Slack or Discord channel.

Noted. WIll try the channels. Thanks

**Comment by joerg-rade** [comment]
@chavu : the redux pattern is used.
