### ISSUE TITLE
FormPanel.getData() fails with 'MissingFieldException' when class property is empty string

### ISSUE THREAD

**Issue by tfonrouge** [rjaros/kvision#381]
As subject, the FormPanel.getData() function fails with exception error 'MissingFieldException' if the data class contains a property with a empty string, if the string is not "" then it works ok.

* Simple Frontend project builded with current KVision plugin.

Seems that serialization process simply exclude any string property with a empty string value

See the sample:

```kotlin
package com.example.project

import io.kvision.*
import io.kvision.form.formPanel
import io.kvision.form.text.text
import io.kvision.panel.SimplePanel
import io.kvision.panel.root

class App : Application() {
    override fun start() {
        root("kvapp") {
            add(View1())
        }
    }
}

@kotlinx.serialization.Serializable
class Class1(
    val text: String
)

class View1 : SimplePanel() {

    init {
        val form1 = formPanel<Class1> {
            text { }.bind(key = Class1::text)
        }
        form1.setData(Class1(text = ""))
        form1.getData() /* here fails when text is empty string */
    }
}

fun main() {
    startApplication(
        ::App,
        module.hot,
        BootstrapModule,
        BootstrapCssModule,
        CoreModule
    )
}
```

**Comment by rjaros** [comment]
Empty string in the `Text` component is always converted to the `null` value (this convention applies to all KVision forms components). So you should either use nullable `String?` type for your backing property or provide a default value for it:
```Kotlin
@Serializable
data class Class1(
    val text: String?
)

@Serializable
data class Class2(
    val text: String = ""
)
```

**Comment by tfonrouge** [comment]
Noted, I reported issue just because this behavior changed from previous versions.

I'm closing the issue.

thank you

**Comment by rjaros** [comment]
> Noted, I reported issue just because this behavior changed from previous versions.

Yes, the change is caused by the fix for https://github.com/rjaros/kvision/issues/352
