### ISSUE TITLE
Built-in feature for masking form on submission

### ISSUE THREAD

**Issue by mgrouch** [rjaros/kvision#384]
Built-in feature for masking form on submission to prevent any editing while form is being submitted.

Does it exist?

Thanks

**Comment by rjaros** [comment]
No, such feature doesn't exist. 
But in single page applications you hardly ever need to submit a form. Typically you just collect the data from the fields on the page (html form is only an optional element) and call some kind of backend endpoint (e.g. with a REST client). After the data is collected, any changes made by the user are no longer relevant. You can easily just disable or hide the whole form before sending the data to the server.

**Comment by mgrouch** [comment]
How is 'Submit' button disabled automatically right now to prevent double clicking?
I think when form is submitted it should be masked and some kind of progress bar or spinner should be displayed on the mask

**Comment by rjaros** [comment]
Sorry for the delayed answer. 
You can use this to prevent double clicking the submit button on the standard form:
```Kotlin
            form(method = FormMethod.GET, action = "/test") {
                text(label = "Input text", name = "text")
                input(InputType.SUBMIT).onClick {
                    this.disabled = true
                    this@form.submit()
                }
            }
```
