### ISSUE TITLE
Check box label option to put label before the checkbox as on all other form fields is needed

### ISSUE THREAD

**Issue by mgrouch** [rjaros/kvision#385]
Check box label option to put label before the checkbox as on all other form fields is needed.
If I build a form with right aligned labels and all fields aligned vertically.
Thanks

**Comment by rjaros** [comment]
This is a bit problematic at the moment because this label position is defined in Bootstrap css. But I've just checked at Bootstrap 5.2.0-beta and they added `form-check-reverse` modifier to reverse the label position. I'll wait till 5.2 is released and then get back to this issue.

**Comment by rjaros** [comment]
I've added  new `reversed` and `labelFirst` properties in KVision 5.14.0. `labelFirst` works with horizontal form layouts.
