### ISSUE TITLE
Clickjacking defence is missing

### ISSUE THREAD

**Issue by mgrouch** [rjaros/kvision#389]
See more on it:

https://cheatsheetseries.owasp.org/cheatsheets/Clickjacking_Defense_Cheat_Sheet.html

Thanks

**Comment by rjaros** [comment]
From what I can see anything added to the framework will not be as effective as adding this code snippet to the `index.html` page itself:
https://cheatsheetseries.owasp.org/cheatsheets/Clickjacking_Defense_Cheat_Sheet.html#best-for-now-legacy-browser-frame-breaking-script
