### ISSUE TITLE
Error when using Formatter.DATETIME as a column format in Tabulator

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#39]
This is the error I am getting when trying to set format = Formatter.DATETIME in a ColumnDefinition:
```
Uncaught (in promise) ReferenceError: moment is not defined
    at C.datetime (tabulator.min.js:11)
    at C.formatValue (tabulator.min.js:11)
    at l._generateContents (tabulator.min.js:8)
    at l.setValueActual (tabulator.min.js:8)
    at l.build (tabulator.min.js:8)
    at new l (tabulator.min.js:8)
    at t.i.generateCell (tabulator.min.js:6)
    at eval (tabulator.min.js:6)
    at Array.forEach (<anonymous>)
    at t.generateCells (tabulator.min.js:6)
```
My Class has a date field of type `pl.treksoft.kvision.types.Date` as I am using Ktor for my backend

**Comment by rjaros** [comment]
Tabulator data/time functions (formatters, editors, validators etc) require [moment.js](https://momentjs.com/) library. I didn't add it as a dependency in tabulator module, because it is quite large library and it makes the output js code size a lot bigger. So at the moment, if you need to use data/time functions, you can add this library directly into the main `index.html` page. In fact the [showcase](https://github.com/rjaros/kvision-examples/blob/master/showcase/src/main/web/index.html) example includes this library.

Of course I forgot to mention about it in the guide ;-)

**Comment by robert-cronin** [comment]
Thanks, seems like an easy fix then. I can add this into the guide with my next commit

**Comment by robert-cronin** [comment]
I think the `momentjs` module would be useful for other reasons, at least in my project but I can imagine others using it as well. I'm in the process of creating the kotlin wrapper but for some reason, I can't solve the above problem with a simple KVision require. I am bringing `moment` in during my `gradle` build:
```
...
    npm {
        dependency("moment", "2.24.0")
    }
...
```
As you suggested, the import in `index.html` solves the problem, now I just want to replace that with a KVision require:
```
pl.treksoft.kvision.require("moment/min/moment-with-locales.js")
```
This doesn't solve the problem. Is there something extra we have to do to make a KVision require add the package to the global namespace?

**Comment by rjaros** [comment]
Have you tried configuring webpack.ProvidePlugin? Here is the configuration for jQuery https://github.com/rjaros/kvision-examples/blob/master/template/webpack.config.d/jquery.js

**Comment by robert-cronin** [comment]
That helped, I just added a new file `moment.js` under webpack.config.d:
```
config.plugins.push(new webpack.ProvidePlugin({
    $: "moment",
    moment: "moment",
    "window.moment": "moment"
}));
```
This allows me to use Formatter.DATETIME in Tabulator. I've also defined a separate `Moment` module I'm using in my local project. If you think it would be useful for KVision, I can make a PR to add the module. If not, I'll just use it in my local project.

**Comment by rjaros** [comment]
With this line `$: "moment",` you are probably overwriting jQuery global symbol ;-) Some other functions may stop working. The second and third line should be enough.

**Comment by robert-cronin** [comment]
ok no worries, I wasn't sure what that line was for, thanks for the info 👍
