### ISSUE TITLE
Feature request: make `requestFilter` suspending

### ISSUE THREAD

**Issue by rocketraman** [rjaros/kvision#390]
For KVision RPC, the `requestFilter` parameter of type `(RequestInit.() -> Unit` is useful for things like injecting authorization data into the request. However, because this lambda is non-suspending, it is difficult to integrate solutions that may require a suspending call.

Example: a token-based authorization system with logic to conditionally refresh a token may need to make a suspending call to do the token refresh.

This becomes even more problematic because there is no ability to use `runBlocking` on Kotlin/JS.

**Comment by rjaros** [comment]
Released with 5.10.1
