### ISSUE TITLE
Window frame close, minimize, maximize inconsistency in roles

### ISSUE THREAD

**Issue by mgrouch** [rjaros/kvision#391]
Close role is button and keyboard focusable
Minimize/Maximize role is generic and not keyboard focusable. 
they should be as ‘close’

thanks

**Comment by mgrouch** [comment]
Also they have different css classes. Makes it difficult to style and align consistently

**Comment by rjaros** [comment]
I'm not sure where do you see these roles? Minimize and maximize buttons are just copies of the close button with some css properties overwritten and added different icons.

![buttons](https://user-images.githubusercontent.com/5646804/170863054-d5bb2ce3-e449-4f12-ae6e-96efc8f70fce.png)
