### ISSUE TITLE
Grid loses sort state if window content is hidden on window drag

### ISSUE THREAD

**Issue by mgrouch** [rjaros/kvision#395]
Grid loses sort state if window content is hidden on window drag.
Paint Canvas also loses its paintings. 

Thanks

**Comment by rjaros** [comment]
Could you please provide some more details or examples?

**Comment by mgrouch** [comment]
All based on desktop example. 
Hiding window content in resize and drag listeners. 
Thanks

**Comment by rjaros** [comment]
The canvas content is cleared after canvas element is resized, hidden and so on. The Paint example currently calls `redraw()` method after resize. Just save the reference to the `canvas` component and call `redraw()` in your event handlers:
```
            dragEndWindow = {
                innerContent.show()
                canvas.redraw()
            }
            resizeWindow = {
                innerContent.show()
                canvas.redraw()
            }
```

As for the `Tabulator` - it's a very complex JS component, with it's own virtual dom rendering engine and its integration with KVision has some limitations. Tabulator uses its own persistence mechanism for its internal state (sorting, filtering, columns sizing etc.). Check: http://tabulator.info/docs/5.2/persist . In KVision you can use:
```
            persistence = true,
            persistenceMode = true,
            persistenceID = "some_unique_id",
```
in `TabulatorOptions`.

**Comment by mgrouch** [comment]
Thanks again! It worked
