### ISSUE TITLE
FormType.INLINE still renders fields vertically

### ISSUE THREAD

**Issue by mgrouch** [rjaros/kvision#399]
FormType.INLINE still renders fields vertically. The field is Select

Thanks

**Comment by rjaros** [comment]
Could you provide some code example? I'm using horizontal forms quite often without any problems.

**Comment by mgrouch** [comment]
Does it work for you with Bootstrap Select and label?

**Comment by rjaros** [comment]
Yes. Here is my screenshot of the showcase example form with `FormType.HORIZONTAL`
![form-horizontal](https://user-images.githubusercontent.com/5646804/169142698-9e65ded9-c2a4-458e-a85f-0654261e7706.png)

**Comment by mgrouch** [comment]
Looks like you have same issue in the example. See 'Typeahead' label is missing and it is not on the side

**Comment by mgrouch** [comment]
Actually yes. It works in example. After removing floating=true
