### ISSUE TITLE
Progress bar is missing 'label' property.

### ISSUE THREAD

**Issue by null-dev** [rjaros/kvision#4]
The Bootstrap progress bar actually supports adding a label, which is unsupported in `kvision` since the `ProgressBar` class is missing the `label` property.

Workaround, we set the content of the ProgressIndicator to the desired label:
```kotlin
progressBar(10) {
    (getChildren().first() as Tag).content = "My label"
}
```

**Comment by null-dev** [comment]
@rjaros Dang, that was crazy fast. Thanks!

**Comment by rjaros** [comment]
Unfortunately you will have to wait a bit longer for the next version release, because I'm doing some serious refactoring at the moment.

**Comment by rjaros** [comment]
The new release has been published.

**Comment by null-dev** [comment]
@rjaros Thanks for notifying me, upgrading now!
