### ISSUE TITLE
Hiding form labels

### ISSUE THREAD

**Issue by mgrouch** [rjaros/kvision#401]
According to bootstrap doc labels for form inputs are always required but can be hidden.

https://getbootstrap.com/docs/4.0/components/forms/#inline-forms

Assistive technologies such as screen readers will have trouble with your forms if you don’t include a label for every input. For these inline forms, you can hide the labels using the .sr-only class. 

I do not see in KVision API to make label hidden, nor to set its class.

Thanks

**Comment by rjaros** [comment]
You can use `flabel.addCssClass("sr-only")` for every form component.

**Comment by mgrouch** [comment]
Oh. Missed it. Thanks!
