### ISSUE TITLE
Tabulator filters (filter function) is not persistent

### ISSUE THREAD

**Issue by mgrouch** [rjaros/kvision#402]
I have window with a content of filter form and tabulator grid. I hide content on window resize and move for performance.
After resize and move content is restored with column order, soft order but not filters invoked by applyFilters()

Thanks

**Comment by rjaros** [comment]
It seems to be the limitation of the base JavaScript component: http://tabulator.info/docs/5.2/persist#filter
But I'll check if it can be fixed by KVision.

**Comment by rjaros** [comment]
Filter function should be restored in the next release

**Comment by rjaros** [comment]
Fixed in 5.10.1
