### ISSUE TITLE
Expose API for controlling select dropdown max height

### ISSUE THREAD

**Issue by mgrouch** [rjaros/kvision#403]
Expose API for controlling select dropdown max height

It looks like currently it's only done via CSS, which is very time consuming.

Thanks

**Comment by rjaros** [comment]
Currently you can use `input.setAttribute("data-size", "5")` to control dropdown max height (set the number of visible options or `false` to always show all options). I'll add direct properties for this.

**Comment by rjaros** [comment]
I've added `dropdownShowAll: Boolean` and `dropdownSize: Int?` properties to all `Select` based components.

**Comment by rjaros** [comment]
Released with 5.10.1
