### ISSUE TITLE
Distribution Path Returns Null

### ISSUE THREAD

**Issue by k4future** [rjaros/kvision#408]
**When i try to build project, i get this error because distribution in build.gradle.kts returns null** 

```
val distribution =
                project.tasks.getByName("frontendBrowserProductionWebpack", KotlinWebpack::class).destinationDirectory
```
`"Task with name 'frontendBrowserProductionWebpack' not found in root project"`

![resim](https://user-images.githubusercontent.com/87473707/172068277-72acf6f8-028f-42a6-81fd-d9244e8eb504.png)

**But when i change distribution value with this static one, its working fine**

`val distribution = "build/distributions"`

![resim](https://user-images.githubusercontent.com/87473707/172068794-bc31b421-0e34-4a02-907a-3b0891f6b85f.png)

**UPDATE**
The source of the problem is that I am using the computer in Turkish language and `println(project.tasks.names)` returns this:

`[allMetadataJar, allTests, assemble, backendJar, backendMainClasses, backendProcessResources, backendSourcesJar, backendTest, backendTestClasses, backendTestProcessResources, build, buildDependents, buildEnvironment, buildKotlinToolingMetadata, buildNeeded, check, clean, cleanAllTests, compileCommonMainKotlinMetadata, compileKotlinBackend, compileKotlinFrontend, compileKotlinMetadata, compileTestKotlinBackend, compileTestKotlinFrontend, components, dependencies, dependencyInsight, dependentComponents, frontendArchive, frontendBrowserDevelopmentRun, frontendBrowserDevelopmentWebpack, frontendBrowserDistributeResources, frontendBrowserDistribution, frontendBrowserProduct�onRun, frontendBrowserProduct�onWebpack, frontendBrowserRun, frontendBrowserTest, frontendBrowserWebpack, frontendGenerateExternals, frontendGenerateExternalsIntegrated, frontendJar, frontendMainClasses, frontendPackageJson, frontendProcessResources, frontendPublicPackageJson, frontendRun, frontendSourcesJar, frontendTest, frontendTestClasses, frontendTestPackageJson, frontendTestProcessResources, frontendTestPublicPackageJson, generateKVisionSources, generatePotFile, generateProjectStructureMetadata, help, init, javaToolchains, kotlinDslAccessorsReport, kotlinNodeJsSetup, kotlinNpmCachesSetup, kotlinNpmInstall, kotlinRestoreYarnLock, kotlinStoreYarnLock, kotlinYarnSetup, metadataCommonMainClasses, metadataJar, metadataMainClasses, metadataSourcesJar, model, nodeKotlinClean, outgoingVariants, packageJsonUmbrella, prepareKotlinBuildScriptModel, processDceDevFrontendKotlinJs, processDceFrontendKotlinJs, projects, properties, rootPackageJson, tasks, transformCommonMainDependenciesMetadata, wrapper, yarnKotlinClean]`

**Comment by rjaros** [comment]
This is a problem with a Turkish language of the operating system. It's a known problem with Gradle.
See: https://github.com/gradle/gradle/issues/2661 or https://discuss.gradle.org/t/locale-specific-tolowercase-and-touppercase-breaks-the-build-on-turkish-os/17840/4
The simplest workaround is to change the locale in the `gradle.properties` file by changing the last line to:
```
org.gradle.jvmargs=-Xmx2g -Duser.country=US -Duser.language=en
```

**Comment by rjaros** [comment]
There is already an old issue on Kotlin youtrack https://youtrack.jetbrains.com/issue/KT-38712
