### ISSUE TITLE
Tabulator - updating the ObservableList when Table is edited

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#41]
I'm a little stumped on how to get the underlying ObservableList to change when
I've got a table like below:
```
@Serializable
data class Numbers(val number1: Int, val number2: Int)

val someObservableList= observableListOf(
    Numbers(2, 4),
    Numbers(3, 1)
)

tabulator(
        someObservableList,
        pl.treksoft.kvision.tabulator.Options(
                dataEdited = {
                    someObservableList.clear()
                    someObservableList.addAll(it as List<dynamic>)
                    someObservableList.addAll(it as Array<dynamic>)
                },
                reactiveData = true,
                layout = Layout.FITCOLUMNS,
                columns = listOf(
                        ColumnDefinition("Number 1", "number1", editor = Editor.INPUT),
                        ColumnDefinition("Number 2", "number2", editor = Editor.INPUT)
                )
        )
) {
    height = 100.perc
    width = 100.perc
}
```
I've tried accepting the data back into the observable list with the `dataEdited` parameter but I get a casting error. 
Any ideas?

**Comment by rjaros** [comment]
When the tabulator component is bound to the model, you should not use this "native" `dataEdited` property. This property is automatically generated and the data is internally converted by tabulator component. You can use custom event `tabulatorDataEdited` to get the data after editing.
```
                        tabulator.setEventListener<Tabulator<Row>> {
                            tabulatorDataEdited = {
                                println(self.getData(false))
                            }
                        }
```

**Comment by robert-cronin** [comment]
That worked a treat, I wonder if this can be a built in feature for the tabulator module, let's say if we have a parameter called something like `doesUpdate: Boolean` that allow any edits to be automatically persisted back into the underlying observable list

**Comment by rjaros** [comment]
Great idea. I have implemented `dataUpdateOnEdit: Boolean = true` and it will work out of the box for any MutableList data model (ObservableList is a MutableList as well).

**Comment by robert-cronin** [comment]
Great! thank you, that will reduce our code a bit
