### ISSUE TITLE
cli.isMultipleCompiler is not a function

### ISSUE THREAD

**Issue by chavu** [rjaros/kvision#410]
The FrontEnd service is failing to start on a new laptop due to the error below. I tried uninstalling and reinstalling latest version of webpack-cli using npm  but that did not work. I also reinstalled lastest versions of IntelliJIDEA Community  and NodeJS without success. The same project is running on my regular laptop but failing on this new laptop. Further investiogation shows that  the ./kotlin-js-store/yarn.lock file on this new machine has different entries from that on a working laptop, It's refering to @webpack-cli/serve version 1.7.0. instead of 1.6.1. This file is autogenerated so I can't edit it. Where in Kvision project are these webpack dependencies setup? I tried putting in the  'package.json' file in the root folder but that did not work.

```
BUILD SUCCESSFUL in 15s
16 actionable tasks: 5 executed, 11 up-to-date

Waiting for changes to input files of tasks... (ctrl-d then enter to exit)
[webpack-cli] TypeError: cli.isMultipleCompiler is not a function
[webpack-cli] TypeError: cli.isMultipleCompiler is not a function
    at Command.<anonymous> (C:\DevProjects\XXXX\build\js\node_modules\@webpack-cli\serve\lib\index.js:146:35)
    at async Promise.all (index 1)
    at async Command.<anonymous> (C:\DevProjects\XXXX\build\js\node_modules\webpack-cli\lib\webpack-cli.js:1674:7)
```

**Comment by rjaros** [comment]
Hi. This was already reported as Kotlin/JS issue (https://youtrack.jetbrains.com/issue/KT-52776). As a workaround you can add this to your `build.gradle.kts`:
```Kotlin
afterEvaluate {
  rootProject.extensions.configure<org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootExtension> {
    versions.webpackCli.version="4.10.0"
  }
}
```
It will be also fixed by the KVision gradle plugin in the next release (should be available this week).

**Comment by chavu** [comment]
Thank you so much. This worked.

**Comment by LinXiaoTao** [comment]
> Hi. This was already reported as Kotlin/JS issue (https://youtrack.jetbrains.com/issue/KT-52776). As a workaround you can adding this to your `build.gradle.kts`:
> 
> ```kotlin
> afterEvaluate {
>   rootProject.extensions.configure<org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootExtension> {
>     versions.webpackCli.version="4.10.0"
>   }
> }
> ```
> 
> It will be also fixed by the KVision gradle plugin in the next release (should be available this week).

groovy version.
``` groovy
afterEvaluate {
    rootProject.getExtensions().configure(Class.forName("org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootExtension")) {
        it.versions.webpackCli.version = "4.10.0"
    }
}
```
