### ISSUE TITLE
Support dynamic values in view

### ISSUE THREAD

**Issue by kartrus** [rjaros/kvision#411]
adding support for dynamic fields and dynamic objects, as well as by kproperty,
common validator,
and such functions that you can add elements in the same way and that their appearance does not differ (regardless of property or dynamically, regardless of whether someone prefers to add a value in add in Text or in bind)

**Comment by rjaros** [comment]
Released with 5.13.1

**Comment by rjaros** [comment]
For more info see: https://kvision.gitbook.io/kvision-guide/2.-frontend-development-guide/forms#dynamic-forms
