### ISSUE TITLE
Update TabulatorRemote row data without change the current page selected

### ISSUE THREAD

**Issue by tfonrouge** [rjaros/kvision#413]
Hi,

I'm using TabulatorRemote to display data, and I need to periodically update the showed data by using the Tabulator.replaceData() method, however the current selected page always goes to the page 1, so it's not possible to keep any page above page 1 selected because the periodic update moves the selected page to page 1.

Is there any chance to have a hook that triggers just before the remote call to the backend is made in order to review/change the page number requested ?

Seems that the Tabulator.replaceData() function always makes that the ajax call send the page number parameter as 1.

Another solution is write a customized pagination button widget in order to totally control the request made to the backend.

thanks for any insight.

best regards,

Teo

**Comment by rjaros** [comment]
I think you can use `tabulator.setPage(tabulator.getPage())` instead of `tabulator.replaceData()`. It should update the data on the current page. You can disable loader popup with `dataLoader = false` to avoid flickering.

**Comment by tfonrouge** [comment]
It works, thank you !

For the moment, no need to know the state of the page selector buttons before sending request to the backend.

best regards,

Teo
