### ISSUE TITLE
Bootstrap module - Dropdown component is missing menu alignment option

### ISSUE THREAD

**Issue by JoonasC** [rjaros/kvision#415]
According to the Bootstrap documentation, dropdown menus can be aligned: [https://getbootstrap.com/docs/5.2/components/dropdowns/#menu-alignment](https://getbootstrap.com/docs/5.2/components/dropdowns/#menu-alignment). Currently the dropdown component of the bootstrap module is missing this option.

**Comment by rjaros** [comment]
Released in 5.12.0
