### ISSUE TITLE
[Feature] Replace toastr with Bootstrap toasts

### ISSUE THREAD

**Issue by JoonasC** [rjaros/kvision#420]
The [toastr](https://github.com/CodeSeven/toastr) library that is currently used to implement the toast functionality in Kvision seems dead (the last commit was in 2018). In addition to this, Bootstrap supports toasts: [https://getbootstrap.com/docs/5.2/components/toasts/](https://getbootstrap.com/docs/5.2/components/toasts/). Wouldn't it make sense to replace toastr with Bootstrap toasts?

**Comment by rjaros** [comment]
Perhaps not necessarily to replace (toastr can still be used without bootstrap module and it works quite well), but it would be nice to add Bootstrap toasts to `kvision-bootstrap` module for completeness.

**Comment by rjaros** [comment]
Bootstrap toasts added in 5.13.0.
https://kvision.gitbook.io/kvision-guide/3.-optional-ui-functionality-via-modules/bootstrap/windows-and-modals#toasts
