### ISSUE TITLE
Documentation on creating custom components is lacking

### ISSUE THREAD

**Issue by JoonasC** [rjaros/kvision#422]
Currently the documentation on how to create custom components is lacking in my opinion: [https://kvision.gitbook.io/kvision-guide/2.-frontend-development-guide/basic-components#extending-kvision-dsl](https://kvision.gitbook.io/kvision-guide/2.-frontend-development-guide/basic-components#extending-kvision-dsl), it only shows how to create a custom DSL function. This is not useful if the custom component needs to have state, because you would need a class to contain that state. I know that the documentation mentions classes/interfaces such as `Component`, `Widget` and `Container` which the KVision components use ([https://kvision.gitbook.io/kvision-guide/2.-frontend-development-guide/ui-structure#component](https://kvision.gitbook.io/kvision-guide/2.-frontend-development-guide/ui-structure#component)), but it doesn't show how you are supposed to use them if you want to create more complex custom components. Having more documentation on this topic would be nice.

**Comment by rjaros** [comment]
I have assumed (probably too optimistic) the standard object-oriented design of the library is enough. I did not take into account that nowadays people think about libraries and components in a different way than they used to be :-) So you are absolutely right because there is no documentation about creating components in an object-oriented way. I'll try to add a chapter about this.

**Comment by lppedd** [comment]
I have to agree. I'm used to the Angular/React/Vue docs, where an explicit example is given. Having the same approach for KVision would jump start a lot of people interested in building custom&reusable widgets.

**Comment by rjaros** [comment]
I've added a new chapter to the guide. Any feedback is welcomed.
https://kvision.gitbook.io/kvision-guide/2.-frontend-development-guide/custom-components

**Comment by JoonasC** [comment]
Looks good to me. Adding a subchapter about using Snabbdom life cycle methods in inheritance based components would be good, but otherwise that pretty much covers everything.

**Comment by JoonasC** [comment]
@rjaros  Quick question, when an inheritance based component gets re-rendered by way of the `refreshOnUpdate` method, will the whole component class be re-instantiated or will certain overridden methods get called?

**Comment by JoonasC** [comment]
Actually never mind, I figured it out.

**Comment by rjaros** [comment]
Classes are only auto re-instantiated when using reactive programming model and state binding methods. In all other cases the lifecycle methods are called (https://kvision.gitbook.io/kvision-guide/2.-frontend-development-guide/dom-bindings#lifecycle-hooks).

**Comment by JoonasC** [comment]
Is there a reason to keep this open still?
