### ISSUE TITLE
SelectRemote fails when a initial value is given

### ISSUE THREAD

**Issue by tfonrouge** [rjaros/kvision#426]
Hello,

As subject, if you set a initial value to the SelectRemote control, then it allways send this value as the 'initial: String' value on the backend function:

In the frontend :

```kotlin
        val root = root("kvapp") {
            selectRemote(
                label = "Country(ok):",
                serviceManager = PingServiceManager,
                function = IPingService::country,
            )
            selectRemote(
                label = "Country(fail):",
                serviceManager = PingServiceManager,
                function = IPingService::country,
                value = "MEX"
            )
        }

```

In the backend, the worker function always receive the 'initial' string parameter as not null containing the value declared in the SelectRemote control frontend:

```kotlin
    private val countryList = listOf(
        "MEX" to "Mexico",
        "USA" to "United States",
        "CAN" to "Canada"
    )

    override suspend fun country(search: String?, initial: String?, state: String?): List<RemoteOption> {
        if (initial != null) {
            val item = countryList.find { it.first == initial }
            return listOf(RemoteOption(value = item?.first, text = item?.second))
        }
        return countryList.mapNotNull { pair ->
            search?.let { string ->
                if (pair.second.contains(other = string, ignoreCase = true))
                    RemoteOption(value = pair.first, text = pair.second)
                else
                    null
            }
        }
    }
```

The KVision documentation states:

"The initial parameter is send with the initial value of the select control. If it's not null, the option bound to the given value should be returned (even if search is not null and does not match the initial value)."

So the backend function always process the initial value from the SelectRemote with initial value.

Any help will be appreciated

best regards,

Teo

(An small example showing this behavior is in the following github rep:

https://github.com/tfonrouge/selectRemoteTest

)

**Comment by rjaros** [comment]
I'm definitely better in writing code then describing it in English ;-) Your `country` method should look like this to make the `SelectRemote` control work as designed:
```Kotlin
    override suspend fun country(search: String?, initial: String?, state: String?): List<RemoteOption> {
        return countryList.filter { (code, name) ->
            val searchCondition = search?.let { name.startsWith(it, ignoreCase = true) }
            if (initial != null) {
                code == initial || searchCondition ?: false
            } else {
                searchCondition ?: true
            }
        }.map { (code, name) ->
            RemoteOption(code, name)
        }
    }
```
The conditions are a lot more intuitive when building SQL query with my favorite query builder: 
```Kotlin
       val query = query {
            select("SELECT code, name FROM countries")
            whereGroup("or") {
                if (search != null) {
                    where("name ilike '%'+:search+'%'")
                    parameter("search", search)
                }
                if (initial != null) {
                    where("code = :initial")
                    parameter("initial", initial)
                }
            }
            orderBy("name")
        }
```

**Comment by tfonrouge** [comment]
Okay, I incorrectly understood that if 'initial' parameter was not null, then I'll need to return that single value ignoring the 'search' parameter.

Noted !    :-)

Thanks for your code, it makes sense now


best regards,

Teo
