### ISSUE TITLE
How to load page data in the background

### ISSUE THREAD

**Issue by chavu** [rjaros/kvision#427]
I have a web page with a tabPannel that has 7 tabs. I'm loading 8 data collections displayed in tables on the tabs during page load, but it takes a lot of time to fully load the data from the server and the page is not responsive during that time. How can I make sure the data contintiues to load in the background while I can access other tabs which have loaded data.

**Comment by rjaros** [comment]
How do you load the data from the server? Almost all networking operations in JS are asynchronous, so there should be nothing blocking the page.
