### ISSUE TITLE
Help to locally build KVision library

### ISSUE THREAD

**Issue by tfonrouge** [rjaros/kvision#429]
Hello,

I want to do some hacking with the KVision library, my final goal is contribute with some enhancements or simply test new ideas.

But, I'm stuck with building the library in my computer. I'm naive enough that I did the following:

* opened it in Idea/IntelliJ
* cloned the KVIsion in a local repo
* bravely in the terminal I send the `./gradlew publishToMavenLocal` in order to have my own local hacked version
* totally failed ...

At first sight seems that I need a gradle plugin installed by seeing the error: "Could not resolve dev.petuska:npm-publish:2.1.2" - How to install it ???

Any help ll'be much appreciated :-)

best regards,

Teo

**Comment by rjaros** [comment]
Try using JDK 11.
I've updated `CONTRIBUTING.md` file.

**Comment by tfonrouge** [comment]
I'm too big a fan of java 1.8 ... 

JDK 11 did the trick.

Thank you !
