### ISSUE TITLE
LinkButton with Tabulator tables?

### ISSUE THREAD

**Issue by joerg-rade** [rjaros/kvision#43]
With DataContainer tables I could use 
```
    is EventState -> cell {
            button(I18n.tr(logEntry.title), icon = v.iconName, style = ButtonStyle.LINK)
    }
```
in order to get LinkButtons in tables.

How can I do it with Tabolator based tables?

**Comment by robert-cronin** [comment]
This would also solve a problem for me. I guess we could achieve it with a custom formatter like this: http://tabulator.info/docs/4.1/format#icon
But that would require modifying the `formatter` parameter to accept anonymous functions.

**Comment by rjaros** [comment]
You can use `formatterFunction` property.

**Comment by robert-cronin** [comment]
@joerg-rade just for your reference, I'm able to get it working, looks a bit like this:
![image](https://user-images.githubusercontent.com/8540764/57204039-74402480-6fe7-11e9-8574-70456d25a798.png)
Here is the code I used:
```
val dateEditor = fun(cell: CellComponent, onRendered: dynamic, success: dynamic): dynamic {
    //cell - the cell component for the editable cell
    //onRendered - function to call when the editor has been rendered
    //success - function to call to pass the successfuly updated value to Tabulator

    //create and style editor
    val editor = document.createElement("input")

    editor.setAttribute("type", "date")

    //create and style input
    editor.setAttribute("padding", "3px")
    editor.setAttribute("width", "100%")
    editor.setAttribute("boxSizing", "border-box")

    //Set value of editor to the current value of the cell
    editor.setAttribute("value", Moment(cell.getValue() as String).format("YYYY-MM-DD"))

    //when the value has been set, trigger the cell to update
    fun successFunc(){
        success(Moment(editor.getAttribute("value") ?: "", "YYYY-MM-DD").format("DD/MM/YYYY"))
    }

    editor.addEventListener("change", {successFunc()})
    editor.addEventListener("blur", {successFunc()})

    //return the editor element
    return editor
}
.....
 ColumnDefinition("DATE", "date", formatterFunction = dateEditor),
.....
```

**Comment by robert-cronin** [comment]
I'm running into a problem when trying to use a formatterFunction and `Button` or `button`. I'm trying to use `Button` like below:
```
val deleteButton = fun(cell: CellComponent, onRendered: dynamic, success: dynamic): dynamic {
    //cell - the cell component for the editable cell
    //onRendered - function to call when the editor has been rendered
    //success - function to call to pass the successfuly updated value to Tabulator

    //create and style editor
    val editor = Button("Delete").onClick {
        Alert.show("Placeholder for delete function")
    }

    //return the editor element
    return editor
}
```
Using it this way doesn't seem to render the button. If I replace `Button` with `button`, it renders it too many times. What would be the correct way to add a button in this anonymous function?

**Comment by rjaros** [comment]
I'm afraid it may not be possible to use KVision components inside custom tabulator formatters (or editors). Tabulator requires formatter function to return native DOM node. And KVision component is not a DOM node. It's just an object bound to virtual DOM implementation underneath. Both KVision and Tabulator use virtual DOM, but probably incompatible with each other on such low level.

But I will still experiment a bit with this.

**Comment by rjaros** [comment]
After many hours of struggle I've managed to do it. I'm closing this issue and I will give more information in #40.

**Comment by joerg-rade** [comment]
I could not find an example in the showcase project, nor the docs.
Please pass on a pointer.

**Comment by rjaros** [comment]
Just use `formatterComponentFunction` described [here](https://app.gitbook.com/@kvision/s/kvision-guide/part-2-advanced-features/tabulator-tables#custom-formatters). An example:
```
                    ColumnDefinition(
                        "Name",  "name", headerFilter = Editor.INPUT,
                        formatterComponentFunction = { cell, onRendered, data ->
                            Button(data.name ?: "").onClick {
                                console.log(data.id)
                            }
                        }
                    )
```
