### ISSUE TITLE
Bad link in docs to Bootstrap customizer

### ISSUE THREAD

**Issue by aSemy** [rjaros/kvision#434]
https://kvision.gitbook.io/kvision-guide/2.-frontend-development-guide/themes

> You can create such a file manually, [build your own Bootstrap](https://getbootstrap.com/docs/5.1/customize/overview/) version from sources or use a third party [customizer](REMOVED). To include a local version of Bootstrap, simply place mybootstrap.min.css in the src/main/web/css directory.

(I've removed the link, so as not to promote it)

the 'customer' link goes to `bootstrapcustomizer com`, but that redirects to some spam domain

**Comment by rjaros** [comment]
Fixed that. Thanks!
