### ISSUE TITLE
Request - add support to Style for list styling

### ISSUE THREAD

**Issue by reubenfirmin** [rjaros/kvision#449]
Please add support for:

* list-style
* counter-reset
* counter-increment
* the counter() css function

**Comment by rjaros** [comment]
Remember you can always use `setStyle()`, like this:
```
val olStyle = Style("ol") {
    setStyle("counter-reset", "section")
    setStyle("list-style-type", "none")
}

val liStyle = Style("li", pElement = PElement.BEFORE) {
    setStyle("counter-increment", "section")
    setStyle("content", "counters(section, \".\") \" \"")
}
```

**Comment by rjaros** [comment]
I've implemented type-safe `listStyle` property, but counter and content css properties are just strings, so in my opinion it's better to just use `setStyle`.
