### ISSUE TITLE
Sass and Scss with KVision

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [rjaros/kvision#454]
How can I use KVision with something like scss?

**Comment by rjaros** [comment]
Yes, you can. See how KVision website is built (it's using Bulma's scss):
https://github.com/rjaros/kvision-io

**Comment by rjaros** [comment]
This configuration file is important:
https://github.com/rjaros/kvision-io/blob/main/webpack.config.d/sass.js

**Comment by FleetAdmiralJakob** [comment]
> This configuration file is important: [rjaros/kvision-io@`main`/webpack.config.d/sass.js](https://github.com/rjaros/kvision-io/blob/main/webpack.config.d/sass.js?rgh-link-date=2022-12-07T17%3A01%3A00Z)

If I add this file I can use .scss files and .sass files?

**Comment by rjaros** [comment]
You also need sass dependencies:
https://github.com/rjaros/kvision-io/blob/main/build.gradle.kts#L59-L60

After that it should work like this:
https://github.com/rjaros/kvision-io/blob/main/src/main/kotlin/io/kvision/website/App.kt#L16

**Comment by FleetAdmiralJakob** [comment]
Thank you. Maybe you can add it to the documentation
