### ISSUE TITLE
When the root container is initialized, the element tag changes to <div>

### ISSUE THREAD

**Issue by weedb** [rjaros/kvision#457]
I noticed that when using `root()` the container tag is changed to a div, is this the intended behavior ? 

If so, then it is possible that in this case it is worth clarifying this in the documentation about the root container.
in index.html i have `<nav id="menu-path"></nav>`

I do so
`root("menu-path")`

and expect
`<nav id="menu-path"></nav>`

but the result
`<div id="menu-path"></div>`

**Comment by rjaros** [comment]
It's an oversight. It will be fixed in the next release.

**Comment by rjaros** [comment]
Fixed in 6.0.6
