### ISSUE TITLE
Cordova integration

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#46]
Figure I may as well start. This issue for future, you mentioned a while ago that you were looking at Cordova integration. 
I just want to flesh out a plan for how to go about it. We will eventually need to release our apps on Android and iOS. 

It looks like you can create a Cordova app using [npm](https://cordova.apache.org/#getstarted), we're you thinking something like an npm package that creates a cordova-kvision app for the various platforms? Or something in gradle? I'm not sure how the latter would work in production

**Comment by rjaros** [comment]
I've made some first experiments with Cordova and managed to run simple KVision app on the android emulator and on my own xperia phone over usb. It's not even very difficult if you have all the required tools installed (cordova, android studio and gradle). The development process is not as nice as I'm used to (no HMR, not even hot-reload at the moment), but it works.

It will be a much bigger challenge to create kvision-cordova module with complete API bindings. I'll probably prepare a skeleton of this module and create some very basic core components. And next it will be possible to implement bindings for core cordova plugins step by step.

Unfortunately I do not have any Mac machine, so someone else will have to try testing iOS integration.

**Comment by robert-cronin** [comment]
Sounds good, once we have a basic skeleton for Android, I can do some testing on my local Mac machine.

**Comment by rjaros** [comment]
I've finished implementing api for all core cordova plugins (device, battery, screen orientation, vibration, camera, file, geolocation, dialogs, inappbrowser, statusbar, splashscreen, network information, media and media capture). I have wrapped most of the orignal, callback-based api into simple suspending functions, so it seems very easy to use, although I've tried to closely follow Cordova's usage patterns (which are not very consistent in my opinion), so the standard Cordova documentation should give enough knowledge to work with KVision.

I've only tested the Android platform, but I've finally managed to get quite nice development experience with the Android emulator. Webpack HMR is working, hot-reload is just as fast as with the browser and Chrome DevTools allow to fully debug the application.

The module will be available in the coming release. Next I'll publish template-cordova example (with some basic api usage) and start writing new chapter for the guide.

**Comment by rjaros** [comment]
There are thousands of Cordova external plugins, and surely it's impossible to create bindings for all of them. But we can choose at least a few - the most used and useful - and create new KVision modules for them, too.

**Comment by robert-cronin** [comment]
I wonder if we can get the same sort of development experience with AppCode for iOS. Yes, there are many, I guess something like a wrapper for a database plugin would be useful, something like SQLite or [KStitch](https://github.com/fortytwoapps/kstitch) where the latter would actually need a plugin developed.

I've also heard there are some problems with the keyboard on cordova so something like [Ionic Keyboard](https://github.com/ionic-team/cordova-plugin-ionic-keyboard) would be fundamental too.

**Comment by rjaros** [comment]
I've published template-cordova project in kvision-examples repository. I'll try to update the guide soon. In the meantime, if somebody have any questions about cordova module, please ask here.

**Comment by rjaros** [comment]
I've updated the guide with the new chapter about Cordova. It probably could be better, more precise and comprehensive, but along with the template-cordova example and the official cordova docs it should give enough info to get started.
