### ISSUE TITLE
500 error with Spring Framework 5.3.x

### ISSUE THREAD

**Issue by LiYing2010** [rjaros/kvision#475]
hi dear team

thank you very much for your great work.

I am trying to use kvision in our project (using old `Spring Boot 2.7.x` + `Spring Framework 5.3.x`), but get 500 error on server side.

I did a little investigation, it turn out that:
(1) `KVHandler.init()` is NOT executed
code: https://github.com/rjaros/kvision/blob/master/kvision-modules/kvision-server-spring-boot/src/jvmMain/kotlin/io/kvision/remote/KVRouterConfiguration.kt#L78-L81

(2) `KVServiceManager.deSerializer` are all `null`

(3) 500 error occurs when `KVServiceManager` try to use `deSerializer` to write response body
code: https://github.com/rjaros/kvision/blob/master/kvision-modules/kvision-server-spring-boot/src/jvmMain/kotlin/io/kvision/remote/KVServiceManager.kt#L70

I checked [kvision-examples](https://github.com/rjaros/kvision-examples),
looks like the `foo-spring-boot` projects are all using `Spring Boot 3.0.x` + `Spring Framework 6.0.x`

and `KVHandler.init()` is using annotation `jakarta.annotation.PostConstruct`

I also checked source code of Spring Framework
looks like 
(A) `Spring Framework 5.3.x` supports `javax.annotation.PostConstruct`
source code:
https://github.com/spring-projects/spring-framework/blob/5.3.x/spring-context/src/main/java/org/springframework/context/annotation/CommonAnnotationBeanPostProcessor.java

(B) `Spring Framework 6.0.x` supports `jakarta.annotation.PostConstruct`
source code:
https://github.com/spring-projects/spring-framework/blob/6.0.x/spring-context/src/main/java/org/springframework/context/annotation/CommonAnnotationBeanPostProcessor.java

I guess that's why `KVHandler.init()` works fine with `Spring Framework 6.0.x`, but not with `Spring Framework 5.3.x`

maybe you want only to support the latest version of `Spring Framework 6.0.x`, but I think there are still many legacy projects are still using old `Spring Framework 5.3.x`

so I think it will be better if kvision can support both,
for example, not use `javax.annotation.PostConstruct` or `jakarta.annotation.PostConstruct` annotations,
but use `@Bean(initMethod = "init")` for `KVHandler` ?

if you agree, I can make PR for this

**Comment by rjaros** [comment]
Unfortunately there are also some other incompatibilities between Spring Boot 2 and 3, which doesn't allow code compiled for SP3 to work with SP2 (e.g. `request.method()` now returns a class instead of an enum - see https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x#web-applications). So there is no simple and efficient way to support old Spring Boot with a single KVision module.

Though it could be possible to create a new module for Spring Boot 2. Unfortunately, this would require significant work on maintaining such a module and I would really like to avoid this. 

Perhaps using the older KVision version (5.x) is a workaround for you, at least until you can upgrade your Spring application?

**Comment by LiYing2010** [comment]
> Unfortunately there are also some other incompatibilities between Spring Boot 2 and 3, which doesn't allow code compiled for SP3 to work with SP2

I don't know why,
but somehow `kvision 6.3.1` works fine in my project (using `Spring Framework 5.3.x` and webflux)


> at least until you can upgrade your Spring application?

this approach also need significant work,
we are planing upgrade it, but not now, maybe a few months later when we get some free time

anyway, I made a workaround in my project:
```
@Bean(initMethod = "init")
fun kvHandlerInit(kvHandler: KVHandler): KVHandlerInit =
    KVHandlerInit(kvHandler)

class KVHandlerInit(
    private val kvHandler: KVHandler,
) {
    fun init() {
        // !!! this is a workaround, remove it later !!!
        // see: https://github.com/rjaros/kvision/issues/475
        kvHandler.init()
    }
}
```

I will use this workaround until we upgrade Spring Boot and Spring Framework

thank you for your help, and I will close this issue
