### ISSUE TITLE
How to deploy to Heroku

### ISSUE THREAD

**Issue by diogo10** [rjaros/kvision#48]
Hi, 

I was playing with the **numbers-fullstack-ktor** sample. I could not get to work when pushing to Heroku. Did you not place the "stage" task on the sample? Just wondering how did you push it to Heroku.

`!     Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
			Detected buildpacks: Gradle,Node.js
			See https://devcenter.heroku.com/articles/buildpacks#buildpack-detect-order
-----> Gradle app detected
-----> Installing JDK 1.8... done
-----> Building Gradle app...
-----> executing ./gradlew stage
       Downloading https://services.gradle.org/distributions/gradle-5.3.1-all.zip
       ..............................................................................................................................
       
       FAILURE: Build failed with an exception.
       
       * What went wrong:
       Task 'stage' not found in root project 'build_ec5df8584cf853f6eed8de6fbf8979ff'.
       
       * Try:
       Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
       
       * Get more help at https://help.gradle.org
       
       BUILD FAILED in 27s
 !     ERROR: Failed to run Gradle!
       It looks like your project does not contain a 'stage' task, which Heroku needs in order
       to build your app. Our Dev Center article on preparing a Gradle application for Heroku
       describes how to create this task:
       https://devcenter.heroku.com/articles/deploying-gradle-apps-on-heroku
       
       If you're stilling having trouble, please submit a ticket so we can help:
       https://help.heroku.com
       
       Thanks,
       Heroku
 !     Push rejected, failed to compile Gradle app.
 !     Push failed`

**Comment by rjaros** [comment]
In the "Settings" -> "Config Vars" I've defined `GRADLE_TASK` as `-Pprod=true bootJar` and in
"Buildpacks" I've selected `heroku/nodejs` and `heroku/gradle`. That's all.

**Comment by rjaros** [comment]
It should definitely go to the guide :-)

**Comment by diogo10** [comment]
Thanks Robert! I will try it out today. Great work pal!

**Comment by diogo10** [comment]
Just to leave for future notes....

<img width="1232" alt="Screenshot 2019-05-27 at 22 07 58" src="https://user-images.githubusercontent.com/1541244/58439447-0493f580-80cc-11e9-91b6-fe6fa6de08b0.png">

<img width="1245" alt="Screenshot 2019-05-27 at 22 08 06" src="https://user-images.githubusercontent.com/1541244/58439456-0c539a00-80cc-11e9-952e-85d550a4d224.png">

Thanks Robert!

**Comment by rjaros** [comment]
The gradle task for the current version of examples should be `-Pprod=true jar`.

**Comment by Solidogen** [comment]
@rjaros I have problems pushing template app to heroku

I added empty package.json file and set GRADLE_TASK to `-Pprod=true JsJar` since `jar` is not found.
App compiles and gets pushed correctly, but it then crashes with:
`npm ERR! missing script: start`

Is there something obvious that I'm missing?

**Comment by rjaros** [comment]
Are you trying to push simple, frontend-only application to Heroku? Why do you want to do this? Frontend application doesn't need any server to run. You just need plain, static hosting - e.g. on Netlify.
