### ISSUE TITLE
Row Menu with Tabulator?

### ISSUE THREAD

**Issue by joerg-rade** [rjaros/kvision#488]
Hi,

after migrating from 5.x to 6.6 my row (context) menus do not pop up anymore:
What am I missing?

```
    private fun columnForObjectMenu(): ColumnDefinition<dynamic> {
        return ColumnDefinition(
            "",
            field = "menuCol", // field is created dynamically
            formatter = Formatter.TICKCROSS,
            formatterParams = menuFormatterParams,
            hozAlign = Align.CENTER,
            width = "40",
            headerSort = false,
            cellClick = { _: dynamic, cellComponent: dynamic ->
                buildObjectMenu(cellComponent.unsafeCast<Tabulator.CellComponent>())
            }
        )
    }

    private fun buildObjectMenu(cell: Tabulator.CellComponent): dynamic {
        val row = cell.getRow()
        val exposer = row.getData() as Exposer
        val tObject = exposer.delegate
        val menu = DynamicMenuBuilder().buildObjectMenu(tObject)
        console.log("[CF_buildObjetMenu]")
        console.log(menu)
        return menu
    }
```
```
```
![2023-07-31 17_22_01-kroViz](https://github.com/rjaros/kvision/assets/4637858/2008936e-769f-4f44-aca6-40aa222c217c)

**Comment by rjaros** [comment]
I don't see here how the menu is opened. You have a click handler which generates the menu options but nothing more. What was your code for the older version?

**Comment by joerg-rade** [comment]
`ColumnFactory `contains both `columnForObjectMenu `and buildObjectMenu see the old implementation for 5.5 at https://github.com/apache/causeway/blob/spring6/incubator/clients/kroviz/src/main/kotlin/org/apache/causeway/client/kroviz/ui/core/ColumnFactory.kt

`ColumnFactory `is used in `RoTable `. Current ->
```
class RoTable(displayCollection: CollectionDM) : SimplePanel() {

    init {
        title = StringUtils.extractTitle(displayCollection.title)
        width = CssSize(100, UNIT.perc)
        val columns = ColumnFactory().buildColumns(displayCollection)
        val model = displayCollection.data
        val options = TabulatorOptions(
            movableColumns = true,
            height = Constants.calcHeight,
            layout = Layout.FITDATASTRETCH,
            columns = columns,
            persistenceMode = false,
        )
        val tabulator = createTabulator(model, options)
        tabulator.setEventListener<Tabulator<dynamic>> {
            cellClickTabulator = {
                val cc = it.detail.unsafeCast<CellComponent>()
                val column = cc.getColumn().getField()
                if (column == "iconUrl") {
                    val exposer = cc.getData() as Exposer
                    val tObject = exposer.delegate
                    ResourceProxy().load(tObject)
                }
            }
        }
        tabulator.addCssClass("horizontal-tb")
        add(tabulator)
    }

    private fun createTabulator(
        data: MutableList<dynamic>,
        options: TabulatorOptions<dynamic>
    ): Tabulator<dynamic> {
        val dataUpdateOnEdit = true
        val className: String? = null
        val init: (Tabulator<dynamic>.() -> Unit)? = null
        val tableTypes = setOf(TableType.STRIPED, TableType.HOVER)
        val tabulator = Tabulator(null, dataUpdateOnEdit, options.copy(data = data.toTypedArray()), tableTypes)
        if (className != null)
            tabulator.addCssClass(className)
        init?.invoke(tabulator)
        return tabulator
    }

}
```

5.5 code at: https://github.com/apache/causeway/blob/spring6/incubator/clients/kroviz/src/main/kotlin/org/apache/causeway/client/kroviz/ui/core/RoTable.kt

**Comment by rjaros** [comment]
You were using `clickMenu` - a dedicated Tabulator property for menus. You can still use it the same way, but now you try to use `cellClick` - an event handler, which is totally different. Why this change?

**Comment by joerg-rade** [comment]
despair ;-) - I'll change it back ...

**Comment by joerg-rade** [comment]
Doesn't make a difference.

**Comment by rjaros** [comment]
Can you share the code you are testing now?

**Comment by joerg-rade** [comment]
Sure, here you go: https://github.com/apache/causeway/tree/kvision-6-upgrade
(+THX!)

**Comment by rjaros** [comment]
From what I can see the menu is correctly generated and the popup container is added to the dom at the correct position. But there is something preventing it from being visible (the container has no css position property). And made some tests and even simple, static popup is not visible. It's probably something in the application code - I'll try to investigate further.

**Comment by rjaros** [comment]
You are missing `TabulatorCssBootstrapModule` initializer in your `main()` function.
