### ISSUE TITLE
SplitPanel modifies style attribute on unrelated div in DOM

### ISSUE THREAD

**Issue by kormik** [rjaros/kvision#489]
SplitPanel sets style attribute `width: calc(59.7074% - 4.5px);` on div element inside and the component. Thevalue corresponds to the splitter position. But this value is also set on unrelated div in parent panel.

SplitPanel should have set distinct snabbdom key added automatically to avoid collision.

**Comment by rjaros** [comment]
Fixed in 7.0.0
