### ISSUE TITLE
Client side port customization

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#49]
Is it possible to change the client side port to something other than 8088? I am trying to deploy my ktor-kvision app to GCP and there is only port 443 available for HTTPS

**Comment by rjaros** [comment]
Deploy for production or development? 8088 is the port of the webpack development server, but I think you want to change 8080 - the default port of Ktor?

**Comment by robert-cronin** [comment]
Ah yes, thats the one, I solved my problem and it wasn't a kvision issue, sorry for the confusion!
