### ISSUE TITLE
Static resources missing after running gradle script for deployment.

### ISSUE THREAD

**Issue by nt1r** [rjaros/kvision#491]
Hi there, I'm very new to Kvision. I created a template hello world project using Jetbrains IDEA plugin(kvision project wizard).
After running deployment script below, it seems that static image resources are missing in the zip file generated by:
```
./gradlew.bat clean zip # Windows
```

build.gradle.kts
```gradle
import org.jetbrains.kotlin.gradle.targets.js.webpack.KotlinWebpackConfig

plugins {
    val kotlinVersion: String by System.getProperties()
    kotlin("plugin.serialization") version kotlinVersion
    kotlin("multiplatform") version kotlinVersion
    val kvisionVersion: String by System.getProperties()
    id("io.kvision") version kvisionVersion
}

version = "1.0.0"
group = "com.example"

repositories {
    mavenCentral()
    mavenLocal()
}

// Versions
val kotlinVersion: String by System.getProperties()
val kvisionVersion: String by System.getProperties()
val koinVersion: String by System.getProperties()

kotlin {
    js(IR) {
        browser {
            commonWebpackConfig(Action {
                outputFileName = "main.bundle.js"
            })
            runTask(Action {
                sourceMaps = false
                devServer = KotlinWebpackConfig.DevServer(
                    open = false,
                    port = 3000,
                    proxy = mutableMapOf(
                        "/kv/*" to "http://localhost:8080",
                        "/kvsse/*" to "http://localhost:8080",
                        "/kvws/*" to mapOf("target" to "ws://localhost:8080", "ws" to true)
                    ),
                    static = mutableListOf("${layout.buildDirectory.asFile.get()}/processedResources/js/main")
                )
            })
            testTask(Action {
                useKarma {
                    useChromeHeadless()
                }

            })
        }
        binaries.executable()
    }
    sourceSets["jsMain"].dependencies {
        implementation("io.kvision:kvision:$kvisionVersion")
        implementation("io.kvision:kvision-bootstrap:$kvisionVersion")
        implementation("io.kvision:kvision-tom-select:$kvisionVersion")
        implementation("io.kvision:kvision-imask:$kvisionVersion")
        implementation("io.kvision:kvision-toastify:$kvisionVersion")
        implementation("io.kvision:kvision-fontawesome:$kvisionVersion")
        implementation("io.kvision:kvision-bootstrap-icons:$kvisionVersion")
        implementation("io.kvision:kvision-tabulator:$kvisionVersion")
        implementation("io.kvision:kvision-rest:$kvisionVersion")
        implementation("io.kvision:kvision-routing-navigo-ng:$kvisionVersion")
        implementation("io.kvision:kvision-state:$kvisionVersion")
        implementation("io.kvision:kvision-state-flow:$kvisionVersion")

        implementation("io.insert-koin:koin-core:$koinVersion")
    }
    sourceSets["jsTest"].dependencies {
        implementation(kotlin("test-js"))
        implementation("io.kvision:kvision-testutils:$kvisionVersion")
    }
}
```

This is how the image is used:
```kotlin
fun Container.pageHeader(viewModel: ViewModel) {
    hPanel {
        ......

        image("img/ubuntu-logo.png") {
            margin = 36.px
        }

        ......
    }
}
```

The zip file generated by the gradle script(./gradlew.bat clean zip):
![QQ截图20230915103215](https://github.com/rjaros/kvision/assets/15714924/56028839-eb14-4ebf-b8d9-71b0ac9b3e81)

My IDEA project structure(red color of the image filename causes by untracked Git file, not in this issue):
![QQ截图20230915103142](https://github.com/rjaros/kvision/assets/15714924/d5c4e250-0378-4bdd-a899-ba7981dfc720)

Missing images in index.html:
![QQ截图20230915103321](https://github.com/rjaros/kvision/assets/15714924/f41813a0-f0d9-4085-9586-8f98087c70f1)

But it works well if I put the resource folder into the root path of generated zip file:
![QQ截图20230915103509](https://github.com/rjaros/kvision/assets/15714924/034c6163-142c-4c37-9c98-dbbf12658157)

**Comment by rjaros** [comment]
Hello,
Please check https://kvision.gitbook.io/kvision-guide/2.-frontend-development-guide/icons-and-images#images

If you put images into `src/jsMain/resources/img`, you should be using `image(require("img/company_logo.png"))`. The file will be processed by Webpack and saved with a mangled name in the output directory.

If you want to work with the original image files, put them into `src/jsMain/web/img` and use `image("img/company_logo.png")`.

**Comment by nt1r** [comment]
Thank you, rjaros. It works pretty well now if I add ```require``` before the image path. Sorry for my oversight on documentation and not familiar with Webpack. Sorry for taking up your valuable time.
