### ISSUE TITLE
Request - documentation/showcase-demos for using Kotlin-ringui and Kotlin-mui

### ISSUE THREAD

**Issue by reubenfirmin** [rjaros/kvision#493]
It looks like Jetbrains have done some nice work in wrapping RingUI (https://github.com/JetBrains/kotlin-wrappers/tree/master/kotlin-ring-ui) and MUI (https://github.com/JetBrains/kotlin-wrappers/tree/master/kotlin-mui). Could you provide a showcase and/or a doc article demonstrating a "hello world"/how to proceed with each? That'd potentially let you add "MUI" and "RingUI" as alternates to Bootstrap in the marketing material, which would be good for adoption.

(They also have a bunch of other stuff in https://github.com/JetBrains/kotlin-wrappers/, some of which may have overlaps with KVision, e.g. electron, and might let you reduce some code.)

**Comment by reubenfirmin** [comment]
Including these as options in the intellij wizard would be great too:

```
Base layout library:
[ ] Bootstrap 5
[ ] MUI
[ ] Ring UI
```

(And then if Bootstrap is selected, giving all of the various kvision/bootstrap related options as additional  things that can be included.)

**Comment by rjaros** [comment]
Both RingUI and MUI are libraries of components for React. While there is support for using React components in KVision, it's not (and can't be) really designed to build whole applications but rather just single, advanced components for some tasks. Trying to use these component libraries will make you just create a kotlin-react application and not KVision application.

**Comment by reubenfirmin** [comment]
Yeah, fair enough. I'm seeing that as I look at their source code. :(
