### ISSUE TITLE
Ktor template feature request

### ISSUE THREAD

**Issue by picoworm** [rjaros/kvision#5]
Hi! Thanks for your awesome framework
Do you have any plans to create reference template with [Ktor](https://ktor.io/)?

**Comment by francismariano** [comment]
@rjaros Do you have any plans to integrate KVision with Ktor in nearest future?

**Comment by rjaros** [comment]
Actually, I'm working on it at the moment :-) Not sure yet, if it will be a success.

**Comment by francismariano** [comment]
Good news!! I will appreciate test it for you.

**Comment by rjaros** [comment]
Done :-) 
New release and examples are on the way.
