### ISSUE TITLE
setAttribute being applied to parent

### ISSUE THREAD

**Issue by markjfisher** [rjaros/kvision#50]
I have the following code

```
    div(classes = setOf("alert", "alert-dismissible")) {
                maxWidth = 20.rem
                button(text = "×", classes = setOf("close")) {
                    setAttribute("data-dismiss", "alert")
                }
            }
    }
```

which I'm expecting to add a data-dismiss attribute to the button, but is actually being applied to the parent div.

Is this correct behaviour? Is it possible to achieve without wrapping the button in another div?

Many Thanks.

**Comment by rjaros** [comment]
At the moment custom attributes are supported for `Tag` class (and it's subclasses). And a `Button` is not a subclass of `Tag`. I was experimenting a bit with this feature and for some reason I have not added custom attributes to the `Widget` class, but I will take a look at this topic once again.

**Comment by markjfisher** [comment]
Thankyou @rjaros

**Comment by rjaros** [comment]
I've commited support for custom attributes for the `Component` interface and the `Widget` class, so it will be available for all KVision components.

**Comment by rjaros** [comment]
I'll close the issue after new version release.

**Comment by robert-cronin** [comment]
@rjaros I'm also trying to set an attribute on a non-tag element (VPanel so not sure if the new code will work with this as well), is there any shortcut you can recommend while we wait for the new version?

**Comment by rjaros** [comment]
Sorry for the late answer but I had to earn some money for my life, and had little time for other things ;-) Now I'm getting ready for KVision and the new release will be very soon.

**Comment by robert-cronin** [comment]
no problems at all, all of us appreciate the awesome work that goes into KVision but money is an important part of life! I'll hopefully be able to add the pace module to before the new version releases
