### ISSUE TITLE
Component lifecycle

### ISSUE THREAD

**Issue by Manriif** [rjaros/kvision#507]
Currently, regarding component lifecycle and without inheritance, we have two important functions `addAfterInsertHook()` and `addAfterDestroyHook()`. These two functions are sufficient in most cases.

However, I had a case where I have to perform a one time action after the component has been inserted for the first time in order to have access to the DOM element. So I used `addAfterInsertHook()` but I didn't see its opposite function `removeAfterInsertHook()`. For such a case, a  `firstTime` boolean allows you to get around the fact that the hook is called every time the component is re-inserted, but that's probably a bad design.

I have another case where I have to perform a task before the component is added to the dom in order to restore its state, but there's no `addBeforeInsertHook()` function.

So, to cover all the scenarios tied to lifecycle without inheritance, I suggest adding the following methods:

- `addBeforeInsertHook()` : Add a hook that will be triggered each time before the component element is added to the DOM.
- `removeBeforeInsertHook()`:  Remove a hook that was previously added.
- `removeAfterInsertHook()`:  Remove a hook that was previously added.
- `addBeforeDestroyHook()` : Add a hook that will be triggered each time before the component element is removed from the DOM.
- `removeBeforeDestroyHook()`:  Remove a hook that was previously added.
- `removeAfterDestroyHook()`:  Remove a hook that was previously added.

I mainly do native mobile development where there is full control over the lifecycle. I don't know about Snabbdom limitations regarding lifecycle.

**Comment by rjaros** [comment]
Unfortunately snabbdom is not so flexible. You can read here about snabbdom hooks: https://github.com/snabbdom/snabbdom#hooks
In short:
- There is a "create" snabbdom hook, which theoretically should be called before inserting to dom. You could try using inheritance and override protected `afterCreate` method. I could also add `addAfterCreateHook()` method to avoid the need of inheritance - unfortunately with a bit of performance cost.
- We can't have "before destroy" hook. There is a "remove" hook in snabbdom, but it is called only in specific cases and I think it will not work well with KVision's component model.
- I can add "remove" methods, but you will have to pass the same references to both "add" and "remove". As you will probably need to call "remove" from the "add" lambda parameter, I'm not sure whether it will work.

**Comment by Manriif** [comment]
My goal is to avoid inheritance and use KVsion components whenever it is possible. Evenly, if adding a method such as `addAfterCreateHook()` will impact the performances, it is better to leave the component as is.

For now, the remove methods for both `addAfterInsertHook()` and `addAfterDestroyHook()` are welcome and it will be the developer responsibility to known how to keep references to its lambdas. A fast and naive exemple on how to store such references could be: 

```kotlin
val myObject = obj {}
val myComponent = div()

myObject.afterInsertHook = { _: VNode ->
    myComponent.removeAfterInsertHook(myObject.afterInsertHook)
}

myComponent.addAfterInsertHook(myObject.afterInsertHook)
```

To make things even simpler, there could be parameterless methods `clearAfterInsertHooks()` and `clearAfterDestroyHooks()` which could simply remove all matching hooks. This way, developers will not have to worry about references keeping. But for these methods, I don't know if there's internal hooks stored by the library for components.

**Comment by rjaros** [comment]
> By the way, what happens to these hooks after a component has been disposed ? Are they removed ?

I think they should be just collected by the GC with the component instance inself.

**Comment by rjaros** [comment]
I've decided to add all these methods, including "create" hooks.

**Comment by Manriif** [comment]
> I've decided to add all these methods, including "create" hooks.

Nice !! better than expected. Thank you for the release and for that awesome web framework by the way !
