### ISSUE TITLE
Wrong module in kvision.gitbook.io.

### ISSUE THREAD

**Issue by CodeServant** [rjaros/kvision#509]
Wrong module in [kvision.gitbook.io](https://kvision.gitbook.io/kvision-guide/2.-frontend-development-guide/form-controls-guide#i.k.f.text.tomtypeaheadremote). Can see that `kvision-bootstrap-typeahead-remote` is deprecated and should be `kvision-tom-select-remote` as in [here](https://kvision.gitbook.io/kvision-guide/7.-full-stack-components/tom-typeahead-remote).

**Comment by rjaros** [comment]
Fixed that. Thanks!
