### ISSUE TITLE
Routing without a hash

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#51]
is it possible to use the inbuilt Navigo routing API without having the hash show up?
This is what I have tried so far to no avail:
```
val customRouter = Navigo("/", false)
customRouter
        .on("/some-url", { _ ->
            console.log("currently on some-url!")
        })
        .resolve()
```
It just throws a 404 error when visiting the url

**Comment by rjaros** [comment]
It's probably possible, but you have to make your http server redirect all traffic to your application. See https://stackoverflow.com/questions/14845048/client-side-javascript-app-url-routing-with-no-hash-tag
You should probably use https://webpack.js.org/configuration/dev-server#devserverhistoryapifallback in custom webpack config (similar to /webpack.config.d/watch.js config). But I havn't tested it.

**Comment by robert-cronin** [comment]
this one is resolved for me
