### ISSUE TITLE
overrides of `SimplePanel.AddAll` call refresh outside of a `singleRender` wrapper.

### ISSUE THREAD

**Issue by wagyourtail** [rjaros/kvision#511]
Several components, 

the ones I checked being: `FlexPanel`, `DockPanel`, `ResponsiveGridPanel`.
use `children.forEach { this.add(it) }` as their implementation of addAll, which ends up calling reRender multiple times.

this is bad for performance.

**Comment by rjaros** [comment]
Fixed in 7.4.0
