### ISSUE TITLE
Removing the title from form elements

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#52]
I'm not sure if there is a simple attribute we can set, but I would like to somehow remove the title from form elements, here is one embedded into a tabulator table:
![image](https://user-images.githubusercontent.com/8540764/58848551-a2ce1f80-86b9-11e9-8ca0-f752db6e49e6.png)
I've tried setting the label to null, but there seems to still be a space for the label:
![image](https://user-images.githubusercontent.com/8540764/58848665-fe001200-86b9-11e9-843e-9c8955debae3.png)

**Comment by robert-cronin** [comment]
Well I think I just figured it out, I just call `flabel.hide()`
![image](https://user-images.githubusercontent.com/8540764/58848955-fdb44680-86ba-11e9-95ad-2cc115bd9297.png)

**Comment by robert-cronin** [comment]
If I can I'd also like to know how to color the actual text box in a Text form element, the above yellow highlighting is set using ``background = Background(Col.YELLOW)` however, the formatting is only applied to the field label

**Comment by robert-cronin** [comment]
well I think I've solved my problem yet again ;) 
I just set the following:
`it.input.background = Background(Col.YELLOW)`
Here is the output:
![image](https://user-images.githubusercontent.com/8540764/58849471-073eae00-86bd-11e9-9c6b-998d8552e561.png)

**Comment by rjaros** [comment]
You could also just use `TextInput` instead of `Text` component.

**Comment by robert-cronin** [comment]
I didn't know I could do that, thanks Robert!

**Comment by rjaros** [comment]
All form controls have two versions (with and without `Input`). It's described here: https://kvision.gitbook.io/kvision-guide/part-2-advanced-features/form-controls-guide
