### ISSUE TITLE
can't make tabulator selectable with kvision v7.4.4

### ISSUE THREAD

**Issue by CodeServant** [rjaros/kvision#524]
Setting `selectableRows` in tabulator kvision `7.4.4` does not make a row selectable.
Tried it with `7.4.3` and works fine. Example usage in [my repo](https://github.com/CodeServant/test-kvision-tab-v7.4.4).

**Comment by rjaros** [comment]
Confirmed. KVision still uses some deprecated options, removed in Tabulator 6.
7.4.5 is on the way.

**Comment by rjaros** [comment]
Fixed in 7.4.5
