### ISSUE TITLE
My tabulator not selecting data

### ISSUE THREAD

**Issue by CodeServant** [rjaros/kvision#525]
I want to generate table that enables me to select one row and under the table to appear a form to edit data or add data. 
I wanted to do it without inline function, so the code looks like the code above. The table appears, the selection works, button shows but no selected value is beeing fetched. This worked as reified tabulator (provided by kvision).
```kotlin
fun <T : Any> Container.insertUpdateTable(
    summaryList: List<T>,
    columnsDef: List<ColumnDefinition<T>>,
    onSelected: (T?) -> Unit,
    formPanel: () -> Component? = { null },
    onInsert: (() -> Unit)? = null,
    onUpdate: (() -> Unit)? = null,
    serializer: KSerializer<T>
) {
    val buttonType = ObservableValue(ButtonType.ADD)
    val onlyEdit = onInsert == null && onUpdate != null
    simplePanel {
        val tab = Tabulator(
            summaryList, options = TabulatorOptions(
                layout = Layout.FITCOLUMNS,
                columns = columnsDef,
                selectableRows = 1,
            ), serializer = serializer
        )
        add(tab)
        tab.onEvent {
            rowSelectionChangedTabulator = {
                buttonType.value =
                    if (tab.getSelectedRows().size == 1) ButtonType.EDIT else ButtonType.ADD
                onSelected(tab.getSelectedData().firstOrNull())
            }
        }
        hPanel(useWrappers = true).bind(buttonType) {
            simplePanel {
                if (it == ButtonType.ADD) {
                    if (!onlyEdit) {
                        addButton {
                            onClick {
                                onInsert?.invoke()
                            }
                        }
                    }
                } else {
                    editButton {
                        onClick {
                            onUpdate?.invoke()
                        }
                    }
                }
            }
            formPanel()?.let(::add)
        }
    }
}
```
But when I try to print
`tab.getSelectedData().firstOrNull()` it won't gove me a result but `[object Object]`.
So the conclusion is that i don't knew which value where selected with tabulator.

**Comment by rjaros** [comment]
What do you pass as the `serializer` parameter?

**Comment by rjaros** [comment]
You should also pass `kClass` parameter to the constructor. It should fix your problem.

**Comment by rjaros** [comment]
To correctly process kotlin data model `Tabulator` component needs to know both the class of the model and its serializer. That's why the constructor have `kClass` and `serializer` parameters. The inline functions are defined to simplify things, because both values can be "guessed" by the reified type parameter. But if you can't use inline functions, you just need to provide both manually.

**Comment by CodeServant** [comment]
to serializer I passed kvision's serializer() function

**Comment by CodeServant** [comment]
Ok, aafter adding kClass it works. Thanks.
