### ISSUE TITLE
kvision gradle plugin not works well with Spring-Web-Flux

### ISSUE THREAD

**Issue by LiYing2010** [rjaros/kvision#527]
looks like there is a func `getServerType()`  in source code of kvision gradle plugin

https://github.com/rjaros/kvision/blob/e9f3eb843777fbb4176c9986e3f4aa425654cbaf/kvision-tools/kvision-gradle-plugin/src/main/kotlin/io/kvision/gradle/KVisionPlugin.kt#L605-L607

but it only checks the dependency name `spring-boot-starter-web`, which is for `Spring Web MVC`

my project is using `spring-boot-starter-webflux`, which is for `Spring Web Flux`,
and it does not works well with `kvision gradle plugin`

I guess it's because of func `getServerType()` does not support `spring-boot-starter-webflux`

I suggest to add `spring-boot-starter-webflux` into func `getServerType()`, how do you think?

if you agree, I will make PR to fix this

**Comment by rjaros** [comment]
Hello. This check is just a simple addon, contributed by KVision user not long ago: https://github.com/rjaros/kvision/pull/516
In general KVision plugin detects Spring Boot by `kvision-server-spring-boot` module dependency. I understand you don't use this module and still want to use KVision tasks for Spring Boot. If so, we can add starter-webflux detection. Feel free to make a PR.

**Comment by LiYing2010** [comment]
> If so, we can add starter-webflux detection

I made PR #528 to fix this
please review when you get time
thanks


> In general KVision plugin detects Spring Boot by kvision-server-spring-boot module dependency.
> I understand you don't use this module and still want to use KVision tasks for Spring Boot. 

Yes, I read this doc [6. Full Stack Development Guide / Common Code / Build configuration ](https://kvision.gitbook.io/kvision-guide/6.-full-stack-development-guide/common-code#build-configuration)

and noticed that I should add `kvision-server-spring-boot` as an `api` dependency to source set `commonMain`

by in my own opinion,
(1) `commonMain` is a common source set, which is used by both `JS` and `JVM` platform
(2) but `foo-server-bar` dependency should be used only by `JVM`, since its name imply it is for `Server Side`

that's why I feel a little strange about `JS` module depends on a `foo-server-bar` dependency

**Comment by rjaros** [comment]
The `kvision-server-spring-boot` dependency is a multiplatform module. It contains code for all three targets - common, JS and JVM. Thats why it needs to be added to the common module. 
But you are right, this name is probably a bit confusing. I've chosen a different name in my new Kilua RPC project, which extracts KVision fullstack code into a separate project.

**Comment by rjaros** [comment]
Fixed in 7.5.x
