### ISSUE TITLE
Error trying the showcase

### ISSUE THREAD

**Issue by rojeras** [rjaros/kvision#53]
Hi,

I think Kvision looks very promising!  To try it out I followed the quickstart instructions, cloned the repo and tried to run. Result is:

npm ERR! notarget No matching version found for kotlinx-serialization-runtime-js@0.11.0 

Any suggestions what I can do to solve this?

BTW, I am using MacOS. 

Regards/LEO

**Comment by rjaros** [comment]
Have you looked at this issue: https://github.com/rjaros/kvision-examples/issues/5 ? Can you confirm you have all [required](https://kvision.gitbook.io/kvision-guide/part-1-fundamentals/setting-up#requirements) tools installed and available on the system path?
