### ISSUE TITLE
Make Alert Button Text Customizable

### ISSUE THREAD

**Issue by mhellmeier** [rjaros/kvision#535]
For the Bootstrap `Confirm` dialog, it is currently possible to set the names of the Buttons (with the parameters, `yesTitle`, `noTitle` and `cancelTitle`):
https://github.com/rjaros/kvision/blob/8f2b3c96dcc9ad594995367ad138a37328244bb9/kvision-modules/kvision-bootstrap/src/jsMain/kotlin/io/kvision/modal/Confirm.kt#L53

Unfortunately, this is not possible with the `Alert`, because it is fixed to the hard-coded value "Ok":
https://github.com/rjaros/kvision/blob/8f2b3c96dcc9ad594995367ad138a37328244bb9/kvision-modules/kvision-bootstrap/src/jsMain/kotlin/io/kvision/modal/Alert.kt#L80

It would be great if the KVision user could customize this value.

**Comment by rjaros** [comment]
Fixed in 8.0.0-RC
