### ISSUE TITLE
Incorrect checkbox size

### ISSUE THREAD

**Issue by s18535** [rjaros/kvision#536]
By default, the checkbox size should be larger, but it is smaller.
![image](https://github.com/user-attachments/assets/34f82dbe-ed57-4c84-b23e-40f156826604)
This should be default size.

![image](https://github.com/user-attachments/assets/c4246f31-ee32-45bb-a330-41495e83652d)
currently it is for short size

**Comment by rjaros** [comment]
Fixed in 8.0.0-RC
