### ISSUE TITLE
Tabulator in DarkMode

### ISSUE THREAD

**Issue by may-day** [rjaros/kvision#540]
In KVision 8.0 dark mode the tabulator cell background stays the same as in light mode. Bug or am i missing something?
Light mode:
![grafik](https://github.com/user-attachments/assets/c8c38c0d-1307-4aaa-829e-1404d160dc56)

Dark mode:
![grafik](https://github.com/user-attachments/assets/a288c863-259b-4518-936d-80b7d46c18a8)

**Comment by rjaros** [comment]
It should work. Check the showcase example (light/dark mode switch is at the bottom):
https://rjaros.github.io/kvision-examples/showcase/#/tabulator

**Comment by rjaros** [comment]
Please check your modules initializers list (especially check if you have `CoreModule` at the end):
https://github.com/rjaros/kvision-examples/blob/master/showcase/src/jsMain/kotlin/com/example/Showcase.kt#L117-L133

**Comment by may-day** [comment]
Turns out it only workes if `TableType.BORDERED` is one of the types in tabulator.

**Comment by rjaros** [comment]
So it's a bug, thanks for reporting.

**Comment by rjaros** [comment]
Fixed in 8.0.1
