### ISSUE TITLE
unexposed Tabulator events

### ISSUE THREAD

**Issue by may-day** [rjaros/kvision#543]
In KVision 8.0 there are some of the Tabulator events exposed, e.g. `rowClickTabulator` that is mentioned in the guide.
Others are not, like the `columnWidth` event. How would i add a handler for that?

**Comment by rjaros** [comment]
You can use `jsTabulator` variable inside `addAfterInsertHook` call and bind event handlers directly to it. An example:
```kotlin
tabulator(...) {
    addAfterInsertHook {
        jsTabulator?.on("dataLoadError") { error: Exception ->
            // do something
        }
        jsTabulator?.on("renderComplete") {
            // do something
        }
    }
}
```

**Comment by may-day** [comment]
Thanks, that did the trick.
