### ISSUE TITLE
Internal css styles with an !important flag interference

### ISSUE THREAD

**Issue by bonzaiferroni** [rjaros/kvision#545]
I've run into some difficulty with internal styles from this file:

https://github.com/rjaros/kvision/blob/7daa34594be70c037bfbaeefbfd1e3d7629e1e0b/kvision-assets/src/css/style.css#L18

For example, text-center is a style used in my css configuration, but in my usage it must sometimes be overridden, so the important flag makes it difficult to work with.

Some of the other styles in that file are given a prefix kv-*. My suggestion is to apply a prefix to styles flagged with !important to allow them to function without interference.

**Comment by rjaros** [comment]
Fixed in 8.1.0
