### ISSUE TITLE
FormPanel and layout

### ISSUE THREAD

**Issue by may-day** [rjaros/kvision#546]
Is there a way to use `vPanel`s and `hPanel`s inside `formPanel`? Something like this:
```kotlin
formPanel<FormData>(type = FormType.HORIZONTAL) {
    hPanel{
        vPanel{
            add(FormData::name1, Text(label = "NAME1"))
            add(FormData::name2, Text(label = "NAME2"))
        }
        vPanel{
            add(FormData::name3, Text(label = "NAME3"))
            add(FormData::name4, Text(label = "NAME4"))
        }
    }
    hPanel{
        add(FormData::streetName, Text(label = "Street"))
        add(FormData::streetNo, Text())
    }
}
```
Since the add extension function is invoked on the FormPanel, the hPanel and vPanel remain empty.

**Comment by rjaros** [comment]
Yes, it is possible. Just use more flexible `bind` instead of `add`. It's documented here:
https://kvision.gitbook.io/kvision-guide/2.-frontend-development-guide/forms#manual-binding

**Comment by rjaros** [comment]
Yes. Fieldsets need to be created manually.
