### ISSUE TITLE
Full stack development - is it possible to use Form result in a service?

### ISSUE THREAD

**Issue by RORAKUS** [rjaros/kvision#553]
Is there any way to automatically send form result to a KVService method?

**Comment by rjaros** [comment]
In typical scenarios you add some kind of "submit/save" button and inside the `onClick` or `onClickLaunch` handler you can use something like that:
```kotlin
button("Submit") {
    onClickLaunch {
        if (form.validate()) {
            service.saveData(form.getData())
        }
    }
}
```
I'm not sure if this is what you are asking.

**Comment by RORAKUS** [comment]
Thanks for the answer. I was asking if there is any direct way by just passing the Service::method object to the form.
Guess there's not. Thanks!
