### ISSUE TITLE
Unable to build jar

### ISSUE THREAD

**Issue by pambrose** [rjaros/kvision#555]
I upgraded to 8.1.0 and I am able to run the server and client in IJ without an issue. However, when I try to compile the code to build a jar file with `./gradlew clean build` I get:
```
> Task :compileCommonMainKotlinMetadata FAILED
e: file:///Users/pambrose/git/canvas-cache/canvas-cache/build/generated/ksp/metadata/commonMain/kotlin/com/canvascache/AdminService.kt:10:8 Class 'AdminService' is not abstract and does not implement abstract member 'clientEnvVars'.
e: file:///Users/pambrose/git/canvas-cache/canvas-cache/build/generated/ksp/metadata/commonMain/kotlin/com/canvascache/DetailService.kt:10:8 Class 'DetailService' is not abstract and does not implement abstract member 'sectionAssessmentsBySection'.
e: file:///Users/pambrose/git/canvas-cache/canvas-cache/build/generated/ksp/metadata/commonMain/kotlin/com/canvascache/QueryService.kt:10:8 Class 'QueryService' is not abstract and does not implement abstract member 'triggerAuth'.
```

Aside from the same code working fine when I run the client and server, the reported missing abstract member of all three classes is the first member of the parent interface (which are implemented in all 3 cases.

Also, the same code worked fine prior to upgrading to 8.1.0, so it seems to be something in the update. 

Any thoughts would be greatly appreciated.

**Comment by rjaros** [comment]
Don't use `build`, use `jar`. Remember #537 :-)

**Comment by pambrose** [comment]
Ha!! I knew it seemed familiar! Sorry about wasting your time. Thanks Robert.
