### ISSUE TITLE
Compiling Ktor and Kvision into a war file

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#56]
I have a `shadowJar` gradle task that compiles my frontend and backend assets into a jar file. Is it possible to compile into a war file instead?

**Comment by rjaros** [comment]
As far as I know, it should be possible to target WAR with Ktor. You should try adding `gretty` plugin to `server/build.gradle` file as described [here](https://ktor.io/servers/deploy/packing/war.html). Let me know if you encounter any problems with this.

**Comment by robert-cronin** [comment]
great that should do it, thanks
