### ISSUE TITLE
Missing hr TAG?

### ISSUE THREAD

**Issue by markjfisher** [rjaros/kvision#57]
I couldn't find a hr TAG type, is this a deliberate omission?

**Comment by robert-cronin** [comment]
I had the same issue the other day, there is no way to extend Tag for custom TAG elements so I'd suggest using jQuery while we wait. Here is a custom classes I created for a dedicated hr tag:
```
class HR: Div() {
    override fun afterInsert(node: VNode) {
        this.getElementJQuery()?.append("<hr />")
    }
}
```
then just call it like this:
```
HR().apply{
    add(this)
}
```

**Comment by markjfisher** [comment]
Thanks, that's saved me a lot of working out how to write one myself, and a good pattern to know.

**Comment by markjfisher** [comment]
Based on your version, I went with this in the end to give a hr() container method, and allow classes

    import com.github.snabbdom.VNode
    import pl.treksoft.kvision.core.Container
    import pl.treksoft.kvision.html.Div
    
    data class HR(
        val classes: Set<String> = setOf()
    ): Div() {
        override fun afterInsert(node: VNode) {
            val classList = classes.joinToString(separator = " ")
            this.getElementJQuery()?.append("<hr class=\"$classList\"/>")
        }
    
        companion object {
            fun Container.hr(
                classes: Set<String> = setOf()
            ): HR {
                val hr = HR(classes = classes)
                this.add(hr)
                return hr
            }
    
        }
    }

which can be used like:

    div {
        hr()
    }

It obviously still contains a superfluous surrounding div, but otherwise fits my need for now.

Again, thanks for your example

**Comment by robert-cronin** [comment]
that's great, thanks for the updates class! I might use it if that's okay

**Comment by markjfisher** [comment]
Polishing it slightly, but my OCD was bothered about the surrounding div, so the new version replaces the div with the hr:

    import com.github.snabbdom.VNode
    import org.w3c.dom.Document
    import pl.treksoft.kvision.core.Container
    import pl.treksoft.kvision.html.Div
    import kotlin.dom.createElement
    
    data class HR(
        val classes: Set<String> = setOf()
    ) : Div() {
        override fun afterInsert(node: VNode) {
            val div = this.getElement()
            val hr = Document().createElement(name = "hr") {
                setAttribute("class", classes.joinToString(separator = " "))
            }
            div?.parentNode?.replaceChild(hr, div)
        }
    
        companion object {
            fun Container.hr(
                classes: Set<String> = setOf()
            ): HR {
                val hr = HR(classes = classes)
                this.add(hr)
                return hr
            }
    
        }
    }

**Comment by rjaros** [comment]
Nice to know it's possible to work around my mistakes ;-) 
Missing `TAG.HR` in already fixed in master branch.

**Comment by robert-cronin** [comment]
I guess this is another tag request so I'll tack it onto this closed issue, I couldn't find the `<br>` tag anywhere either, I'm not sure if there is another way to add a break in KVision. I've submitted a PR (#61) adding it into the enum

**Comment by robert-cronin** [comment]
I've also added a fix for a bug where `vertical-align` wasn't being applied, it was just a spelling error
