### ISSUE TITLE
Restful backend support for kvision

### ISSUE THREAD

**Issue by checketts** [rjaros/kvision#6]
I have an existing SpringBoot RESTful backend that I want to create a kvision frontend for. I can't seem to find any documentation highlighting how that would behave.

Does that support exist? 

Alternatively, is there kvision support for serializing to/from json? If I could find an example of that I could get un-stuck.

**Comment by rjaros** [comment]
You can use kotlinx.serialization library (already a dependency of KVision) for (de)serialization and `pl.treksoft.kvision.remote.CallAgent` class to make calls to your backend. A working example:

```
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.asDeferred
import kotlinx.coroutines.launch
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.list
import pl.treksoft.kvision.hmr.ApplicationBase
import pl.treksoft.kvision.remote.CallAgent
import pl.treksoft.kvision.utils.obj

@Serializable
data class Repository(val id: Int, val full_name: String?, val description: String?, val fork: Boolean)

object App : ApplicationBase {
    val callAgent = CallAgent()

    override fun start(state: Map<String, Any>) {
        GlobalScope.launch {
            val result: dynamic = callAgent.remoteCall("https://api.github.com/search/repositories", obj { q = "kvision" }).asDeferred().await()
            val items: List<Repository> = Json.nonstrict.parse(Repository.serializer().list, JSON.stringify(result.items))
            println(items)
        }
    }
}
```
The `remoteCall` method returns `kotlin.js.Promise` object, so you can use it without coroutines if you want. I will think about adding some helper methods to CallAgent class to simplify above code and I'll put similar example in the docs.

**Comment by checketts** [comment]
Thanks for the great example! Would `DynamicObjectParser` be useful or essentially equivalent?

 https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/runtime_usage.md#dynamic-object-parser-js-only

**Comment by rjaros** [comment]
You are right! This is simpler and probably more efficient:
```
val items: List<Repository> = DynamicObjectParser().parse(result.items, Repository.serializer().list)
```

**Comment by rjaros** [comment]
From KVision 0.0.25, it will be enough to write the whole call as:
```
val items: List<Repository> = callAgent.remoteCall("https://api.github.com/search/repositories", obj { q = "kvision" }, Repository.serializer().list) {
    it.items
}.asDeferred().await()
```

**Comment by checketts** [comment]
In your example, what is `obj { q = "kvision" },` ?

**Comment by rjaros** [comment]
`pl.treksoft.kvision.utils.obj` is a helper function to create a dynamic JS objects. `obj { q = "kvision" }` is an equivalent of `js("{\"q\": \"kvision\"}")` but looks a lot better :)

**Comment by rjaros** [comment]
Fully type-safe calls with 0.0.25 will be possible as well:
```
@Serializable
data class Query(val q: String?)

@Serializable
data class SearchResult(val total_count: Int, val incomplete_results: Boolean)

GlobalScope.launch {
    val searchResult: SearchResult = callAgent.call<SearchResult, Query>("https://api.github.com/search/repositories", Query("kvision")).asDeferred().await()
    println(searchResult)
}
```

**Comment by rjaros** [comment]
Version 0.0.25 is released. The kvision-guide is updated as well.
