### ISSUE TITLE
[feature] Add support for tree and tree-table components

### ISSUE THREAD

**Issue by altavir** [rjaros/kvision#60]
It would be nice to have support for trees and tree tables similar to tornadofx/javafx `TreeView` and `TreeTableView`.

**Comment by robert-cronin** [comment]
I'm not sure about a pure, non-tabulated `TreeView` but `Tabulator` comes with some pretty good support for tree structure and nested data: http://tabulator.info/docs/4.1/tree

**Comment by altavir** [comment]
Simple tree could be implemented using regular bootstrap tree navigation.

**Comment by rjaros** [comment]
Tree data support should be added to our tabulator module.
