### ISSUE TITLE
Inner borders around ResponsiveGridPanel

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#62]
how do I add internal borders to a `ResponsiveGridPanel` in the same way I would add them to a table? perhaps I am using the grid panel in the wrong way and it's not intended to do this

**Comment by rjaros** [comment]
You should be able to get inner borders using dark background color and setting both horizontal and vertical grid gap to 1.px on the GridPanel.

**Comment by rjaros** [comment]
Here is an plain html/css example:
https://codepen.io/mary_pieroszkiewicz/pen/owGzBz

**Comment by rjaros** [comment]
Have you managed to get expected result?

**Comment by robert-cronin** [comment]
yes this is also resolved for me 👍
