### ISSUE TITLE
Scrolling issues on Safari

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#64]
I am having scrolling issues in containers on iOS safari when setting overflow to scroll.
Specifically the issue is that there is no smooth continuous scrolling like there is on the android browser.
Any ideas on how to fix this?

**Comment by rjaros** [comment]
As far as I understand this https://www.w3schools.com/howto/howto_css_smooth_scroll.asp, Safari does not support smooth scroll with CSS.

**Comment by robert-cronin** [comment]
ok looks like I will have to wrap our app in a Cordova project in order to get everything working nicely, thanks
