### ISSUE TITLE
Is it possible to do non-integer CSS sizes?

### ISSUE THREAD

**Issue by markjfisher** [rjaros/kvision#65]
How do I do something like "1.49em" as a size?
It appears the CssSize class is Pair<Int, UNIT>, so do I have to resort to direct CSS for this scenario?

**Comment by rjaros** [comment]
At the moment it's not possible. But definitely it should be fixed.

**Comment by markjfisher** [comment]
Thanks. I can work around it easily, just wondered if I was missing a trick.

**Comment by rjaros** [comment]
Fix commited.
