### ISSUE TITLE
Browser detection

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#66]
Is it possible to detect which type of browser is being used? I want to determine if overflow scrolling is possible. I know of  [Modernizer](https://modernizr.com) but haven't had success with bringing it in as an external library.

**Comment by rjaros** [comment]
You can always just use such simple JS code: https://stackoverflow.com/questions/7944460/detect-safari-browser. The `navigator` object and its properties are all available in Kotlin/JS.

**Comment by robert-cronin** [comment]
got it! thanks @rjaros

**Comment by robert-cronin** [comment]
I am trying to following example: 
```
        val ua = Navigator.userAgent.toLowerCase()
        if (ua.indexOf('safari') != -1) {
            if (ua.indexOf('chrome') > -1) {
                alert("1") // Chrome
            } else {
                alert("2") // Safari
            }
        }
```
But It is telling me there is no member called `userAgent`? how do I access the member properties of Navigator? it is an abstract class. I can create an object that inherits from this class but it has many members that need to be implemented.

**Comment by rjaros** [comment]
```
        import kotlin.browser.window

        val ua = window.navigator.userAgent.toLowerCase()
        if (ua.indexOf("safari") != -1) {
            if (ua.indexOf("chrome") > -1) {
                window.alert("1") // Chrome
            } else {
                window.alert("2") // Safari
            }
        }
```

**Comment by rjaros** [comment]
Can we close this issue?

**Comment by robert-cronin** [comment]
yes all resolved for me
