### ISSUE TITLE
Can Modal Dialogs be Resized and Moved?

### ISSUE THREAD

**Issue by joerg-rade** [rjaros/kvision#67]
Is this possible?
Should I use Window instead?

**Comment by rjaros** [comment]
Standard Bootstrap modals do not have such features, so it's not possible with currently implemented API. There are some possible JS tricks to do this (https://codepen.io/b0y/pen/VegwYd) but what I can see it depends on jquery-ui library.
It would be way simpler to just use Window component.

**Comment by joerg-rade** [comment]
Thanks
