### ISSUE TITLE
Window Icons

### ISSUE THREAD

**Issue by joerg-rade** [rjaros/kvision#68]
Window currently has closeIcon.
Is it possible to have more like:
* a symbol left of caption, e.g. fa-paint-brush for Paint
* left of closeIcon: maximize, minimize

**Comment by rjaros** [comment]
It's probably not possible at the moment because `header` object is private in `Window` class. I'll take a look at this.

**Comment by rjaros** [comment]
Committed. Support for these icons will be available in the next release. The actual implementation of minimization and maximization will be on the application side - KVision will only send events. But I've already tested working example in my `desktop` application.

**Comment by robert-cronin** [comment]
There are a few other font awesome icons I've encountered that don't seem to be working, for example, `fa-weight-hanging` or even strings like the following don't work: `fal fa-cog`, how do I represent these font awesome strings in KVision?

**Comment by rjaros** [comment]
You are probably checking Font Awesome 5.x (the current version). KVision is integrated with older version, Font Awesome 4.7 - https://fontawesome.com/v4.7.0/.
