### ISSUE TITLE
Add PWA example (Progressive Web App)

### ISSUE THREAD

**Issue by checketts** [rjaros/kvision#7]
I'm really enjoying kvision. I'm actually using it to write a simple application, however I haven't found a wrapper for service workers. 

An example for creating a simple Progressive web app would be really useful.

I'll be happy to contribute once I've figured out how to do it.

**Comment by rjaros** [comment]
Unfortunately I have no experience with PWA apps. Do you have a simple example?

**Comment by checketts** [comment]
I'm working through an article that creates on with Angular and highlights the tooling to ensure it is a PWA (https://www.smashingmagazine.com/2018/09/pwa-angular-6/). Once I finish that , I'll try to apply it to kvision.

**Comment by rjaros** [comment]
I've upgraded the Pokedex example to be a fully compatible PWA. It were just a few changes in index.html, some new files (manifest, icons) and additional webpack plugin (workbox).
