### ISSUE TITLE
redux-devtools-extension connection example

### ISSUE THREAD

**Issue by k33ny** [rjaros/kvision#71]
It'd be nice if there'd be a section in the guide for [Redux Devtools Extension](https://github.com/zalmoxisus/redux-devtools-extension#usage) setup.

**Comment by rjaros** [comment]
I've commited a small change in kvision-redux module, and now support for Redux Devtools Extension will be enabled by default in dev mode (of course in the next KVision release). Unfortunately only with the default configuration - at the moment I don't see a nice way to inject custom options. I hope it will be enough, cause it's really nice tool.

**Comment by k33ny** [comment]
Just seeing the state history is a colossal improvement
