### ISSUE TITLE
Tabulator setting width results in an incorrect blown out width

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#72]
When I set the column width in the `ColumnDefinition` to any value, it stretches it out like below:
![image](https://user-images.githubusercontent.com/8540764/61260805-3a8f5500-a7b2-11e9-9905-0bd5fe389382.png)

I have set `layout = Layout.FITCOLUMNS` but it also exhibits the same behaviour for any other choice or no choice at all. Do you have any idea what's going on here? I can't tell if its a Tabulator issue or if I'm just not using it right.

**Comment by rjaros** [comment]
What value do you use for the `witdh` property? Look at this example code, it works fine for me: https://github.com/rjaros/kvision-examples/blob/master/addressbook-tabulator/src/main/kotlin/com/example/ListPanel.kt

**Comment by robert-cronin** [comment]
ahh yeah my bad I was using "60px" for the width property in column definition, when I change it to 60, it works 👍
