### ISSUE TITLE
Short guide on local setup for KVision development

### ISSUE THREAD

**Issue by mpetuska** [rjaros/kvision#75]
Currently I'm struggling to setup my local environment for KVision framework development and testing. A short contributors' guide would be most useful.

**Comment by robert-cronin** [comment]
There are example projects that might help you, have you found those as yet?https://github.com/rjaros/kvision-examples
Also, the guide looks like it has quite a lot of useful info already (https://kvision.gitbook.io/kvision-guide/part-1-fundamentals/setting-up) but perhaps you mean something a bit more detailed

**Comment by rjaros** [comment]
It's about developing KVision itself. I should add such [contributing guidelines](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors) to this github repo.

**Comment by robert-cronin** [comment]
oh yes sorry I didn't see the ontributing part ;)

**Comment by rjaros** [comment]
I've added short [contribution guidelines](https://github.com/rjaros/kvision/blob/master/CONTRIBUTING.md).
