### ISSUE TITLE
Print templates

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#76]
Is there currently any way to create something like an A4 HTML template that can be printed to pdf? 

One way I have tried is to create a print template with kvision components and use the [Print.js](https://printjs.crabbly.com/) library to transform it into a pdf, but I can't seem to translate the inline style elements from kvision to show up on the final print off. Any idea how I can do this? 

There could also be a jQuery print plugin that might make it easier, designing a print off in kvision is very easy, just need a way to translate it to a pdf with styles intact.

**Comment by rjaros** [comment]
Printing support is always a challenge :-) I'll take a look.

**Comment by robert-cronin** [comment]
I've managed to get it to work with the inline styles from kvision, it was just my lack of understanding about the print.js library. 
Print.js is only about 37kb I think, do you want to add it into kvision as a kotlin wrapper? I've basically already created the wrapper so I could commit it into kvision as a new module

**Comment by rjaros** [comment]
Great.

**Comment by rjaros** [comment]
New module is available in 3.16.0.
