### ISSUE TITLE
Positioning of SelectInput in a Tabulator custom component formatter

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#78]
I am having troubles with the position of a `SelectInput ` component in a tabulator column, I have set all padding and margins to `0.px` but the `SelectInput` seems to translate down about `3.px`, any idea why this is? I don't see this on any other form element using within a custom tabulator formatter.
![image](https://user-images.githubusercontent.com/8540764/62111024-40248900-b2e2-11e9-919c-52f02be61737.png)

**Comment by rjaros** [comment]
How did you even manage go get `SelectInput` work inside the Tabulator ? :-) 
I haven't found any way to make it work - that's why I've created `SimpleSelect` component.

**Comment by robert-cronin** [comment]
haha yeah I'm not sure either, I tried `SimpleSelect` but couldn't get the `livesearch` function to work, is this a necessary omission to make the selector work inside tabulator?

**Comment by rjaros** [comment]
I think `Select` is just too complicated to work with tabulator virtual dom. And `SimpleSelect` is just a simple wrapper over HTML `<select>` tag, so no fancy features are available here :-(

**Comment by rjaros** [comment]
I see you use `Select` component as a formatter and I've tried to use it only as an editor. I'll try to play with this configuration.

**Comment by rjaros** [comment]
How did you change tabulator row/cell height and padding?

**Comment by rjaros** [comment]
I have tried this and the `SelectInput` indeed seems to work fine as a formatter. As for the extra padding, this is something most promising in my tests:
```
                        formatterComponentFunction = { cell, _, _ ->
                            cell.getElement().style.paddingTop = "1px"
                            SelectInput(listOf("first" to "First", "second" to "Second"))
                        }

```
I've changed row height with rowFormatter:
```
                rowFormatter = {
                    it.getElement().style.height = "37px"
                }
```

**Comment by robert-cronin** [comment]
yeah that is working for me too, thanks for that 👍 
The only thing I found was that the SelectInput dropdown remains inside the table view and if its the last row, it gets hidden and you have to scroll down. I don't think this happens with the SimpleSelectInput, but I think the original problem is solved 👍
