### ISSUE TITLE
Type mismatch at KVServiceManager

### ISSUE THREAD

**Issue by diogo10** [rjaros/kvision#80]
Hi guys, 

I noticed this issue after I have updated the Kotlin and IDEA. The project runs well, not sure what would be the issue. The IDEA suggestions does not fix the issue.

<img width="616" alt="Screenshot 2019-07-30 at 13 35 42" src="https://user-images.githubusercontent.com/1541244/62129985-e74bf500-b2cf-11e9-9b81-1dfda2bce26a.png">

`
kotlinVersion=1.3.30
kvisionVersion=0.0.35
serializationVersion=0.11.0
frontendPluginVersion=0.0.45
javaVersion=1.8
gradleShadowPluginVersion=5.0.0
ktorVersion=1.2.2
logbackVersion=1.2.3
kotlin.incremental.js=false

`

EDIT:

A method without params seams fine...

**Comment by rjaros** [comment]
It's caused by new type inference, which is enabled by default in IntelliJ IDE since Kotlin 1.3.40. See https://blog.jetbrains.com/kotlin/2019/06/kotlin-1-3-40-released and watch this bug https://youtrack.jetbrains.com/issue/KT-32452

**Comment by rjaros** [comment]
You can safely turn off "Enable new type inference algorithm for IDE analysis" option in IntelliJ on Kotlin compiler options page.

**Comment by diogo10** [comment]
Thanks man!
