### ISSUE TITLE
Chart.js plugins

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#81]
I have a feeling there is an error with the internal code in the kvision Chart.js module. If you look in `js/Chart.kt`, the `ChartOptions` interface defines plugins, however, this method is not accessible. There is also a `ChartOptions` data class defined in Configuration.kt but it doesn't define any plugin methods.

Specifically, I am looking to integrate this pluigin: https://chartjs-plugin-datalabels.netlify.com/

**Comment by rjaros** [comment]
Files in `chart.js` subpackage are generated from original Chart.js TypeScript bindings by ts2kt utility, so they contain all interfaces, classes and methods of Chart.js (at least those possible to convert). The `Configuration.kt` file is written by me, and it doesn't cover the whole Chart.js API. There are some unsupported parts, mostly those I didn't really understand ;-) The plugins API is one of them.

I think it's possible to add some dynamic properties and enable at least some parts of this API. I'll play with this and try to make it possible for the next release.

**Comment by rjaros** [comment]
Fixed in 0.0.39

**Comment by robert-cronin** [comment]
I've just been looking into the plugins part of the library, looks promising, I'm not sure if I'm missing something but it looks like there should be an extra argument in charts to add the initialized plugin:
```
var chart = new Chart(ctx, {
    plugins: [ChartDataLabels],
    options: {
        // ...
    }
})
```
This was taken from the [datalabels](https://chartjs-plugin-datalabels.netlify.com/guide/getting-started.html#registration) plugin website.
Then in options looks like there is also a plugins argument which already exists in the kotlin `Configuration.kt` file, this is how I call it in KVision:
```
plugins = obj {
    datalabels = {
        align = "end"
        anchor = "end"
        formatter = fun(value: dynamic, context: dynamic) {
            return context.chart.data.labels[context.dataIndex]
        }
    }
}
```

**Comment by rjaros** [comment]
For now I've implemented only global plugin registration (with `Chart.registerPlugin()` and `Chart.unregisterPlugin()` functions). But you are right, there should be also possibility to register plugins for specific charts only. I'll add this option in the next release.
