### ISSUE TITLE
Double Navbar

### ISSUE THREAD

**Issue by joerg-rade** [rjaros/kvision#86]
With 
```
object RoMenuBar : Navbar() {
    val nav = Nav()

    init {
        navbar(type = NavbarType.FIXEDTOP) {
            marginLeft = CssSize(-12, UNIT.px)
            add(nav)
            val mainEntry = buildMainEntry()
            nav.add(mainEntry)
        }
    }
[...]
}
```
I get two navbars (full code at: https://github.com/joerg-rade/kroviz/blob/master/src/main/kotlin/org/ro/view/RoMenuBar.kt). 

Am I doing something wrong?

![navbar](https://user-images.githubusercontent.com/4637858/63585991-a2e70880-c5a0-11e9-92d8-eca8e484c3d4.png)

**Comment by rjaros** [comment]
You are using DSL builder function (`navbar(...)`) inside the initialization block. So you are in fact creating a `NavBar` component and then adding it to the `RoMenuBar`, which is also a `NavBar` component (instantiated inside an `Application` object). So you have two navbars.

Remove `navbar` call from init and set `type` property on the `RoMenuBar` component.

**Comment by joerg-rade** [comment]
I switched to delegation instead of inheritance and now it works. Thanks!
There was some nasty interaction with the second navbar (statusbar) at the bottom though ...
