### ISSUE TITLE
Allow to use any arbitrary source of data for `stateBinding`

### ISSUE THREAD

**Issue by jcornaz** [rjaros/kvision#91]
Hi, 

First of all, thanks for the awesome work! This framework looks very nice!

I want to propose an improvement of the `stateBinding` feature. Currently, it is tighly bound to `ReduxStore`. But the only really important thing is that it should observe changing state, and update the component.

So it would be nice if there was an alternative such as: 

```kotlin
fun <S, CONT : Container> CONT.stateBinding(states: Flow<S>, factory: CONT.(S) -> Unit)
```

It would then allow to use any state management technology. Not only redux.

And the redux version could become an overload such as:
```kotlin
fun <S : Any, CONT : Container> CONT.stateBinding(store: ReduxStore<S>, factory: CONT.(S) -> Unit) =
    stateBinding(store.asFlow(), factory)
   
fun <S : Any> ReduxStore<out S, *>.asFlow(): Flow<S> = channelFlow {
  val unsubscribe = subscribe { state -> offer(state) }
  awaitClose { unsubscribe() }
}.conflate()
```

The thing is, despite I like very much the philosophy behind redux and that state binding, I don't like using Redux directly since it forces me to make my in-memory state serializable (which is awkward and limiting). And creating state management based on immutable state and 
pure reducer in Kotlin is far too easy to justify the complexity and limitation of using Redux.

**Comment by rjaros** [comment]
Thx for your feedback. 

We have dropped serialization requirement for Redux module a few months ago (see #58). 

But of course your other arguments are worth attention. What I really would like to avoid is the direct dependency on `kotlinx.coroutines` library. It's currently included for some modules, but not for the core KVision. It just adds a lot of weight to the resulting bundle size. I'll think about this - perhaps it can be done without using `Flow` interface directly.

**Comment by jcornaz** [comment]
>We have dropped serialization requirement for Redux module a few months ago (see #58).

Ok. That's very nice indeed. Thanks!

I don't know why, I was sure `@Serializable` was necessary.


>But of course your other arguments are worth attention. What I really would like to avoid is the direct dependency on kotlinx.coroutines library. 

Fair point. However, KVision could introduce an interface to describe the observable state. 

But my use-case is kind of solved anyway if I can use non-serializable data classes with redux...

**Comment by rjaros** [comment]
I've abstracted the state container with such new interface:
```
interface ObservableState<S> {
    fun subscribe(observer: (S) -> Unit)
}
```
I've moved the `StateBinding` class from the redux module (both of them) to the main module with `ObservableState` instead of `ReduxStore`. Of course `ReduxStore` implements now `ObservableState`. And `ObservableList` implements this interface as well, so it can be used as a data source for the StateBinding. It should be also very easy to create an extension for `Flow<S>` if you want to use it.

Stay tuned for 2.0.0-M2

**Comment by jcornaz** [comment]
>I've abstracted the state container with such new interface:

Cool. How to unsubscribe from that interface?

**Comment by rjaros** [comment]
Until now unsubscribing was not even implemented in `StateBinding` class. I'll take a look at this again :-)

**Comment by rjaros** [comment]
Changed it to:
```
interface ObservableState<S> {
    fun subscribe(observer: (S) -> Unit): () -> Unit
}
```
The return value is an unsubscribe function, just like with the redux store.
