### ISSUE TITLE
Remove application boilerplate

### ISSUE THREAD

**Issue by altavir** [rjaros/kvision#92]
After spending some time trying to work with raw JS libraries, I came back here and decided it is better to have one common library of good quality that a lot of not so good ones. Still there are some not quite obvious decisions I would like to address first. 

First one is the boilerplate around ApplicationBase. Every single application in examples contains the same code for HMR. I suggest to just add a function like [this one](https://github.com/mipt-npm/dataforge-vis/blob/554eaa24d88a5932f54608949dab5ea57ff52326/dataforge-vis-common/src/jsMain/kotlin/hep/dataforge/vis/HMR.kt#L31) into the core and then call `main` method just like this:
```kotlin
fun main(){
    startApplication(::DemoApp)
}
```

Second thing is the generation of Root container. The use of lateinit does not look good. Also the idea of `Root` being created outside application lifecycle looks not safe. My suggestion is to replace the class constructor of root with the function defined on Application like this:

```kotlin
fun Application.root(id: String, block: Root.()->Unit){...}
```
The `Application` here is not the same as `ApplicationBase`, it is an abstract class that counts all roots created in in and automatically disposes them on reload.

I can contribute those solutions if you like the idea.

**Comment by rjaros** [comment]
I've replaced the `ApplicationBase` interface with the abstract `Application` class and added very similar `startApplication()` function. As the roots references are already collected inside the companion object, it was very easy to add your suggestion about automatic disposal. 

In 2.0.0-M2 all this redundant code will be removed from all the examples.

**Comment by altavir** [comment]
Also, while we are on the same wave Root constructor looks really awful. You should never "either or" arguments in this way. There should be a secondary constructor with different input type, or even better, a factory function which accepts different arguments and does what init block does right now.

Experience tells that In Kotlin init blocks should be used only in strictly necessary cases or for parameter checks.
