### ISSUE TITLE
Project setup in IntelliJ IDEA

### ISSUE THREAD

**Issue by g3blv** [rjaros/kvision#94]
Which project type is most appropriate in IntelliJ IDEA when cloning the [template](https://github.com/rjaros/kvision-examples/tree/master/template)? The objective is to follow [Building a Pokedex app with Kotlin, KVision and Redux](https://dev.to/rjaros/building-a-pokedex-app-with-kotlin-kvision-and-redux-part-1-51h5) and build the app.
![image](https://user-images.githubusercontent.com/45568043/67320673-d695ce80-f50e-11e9-8b02-f474303d060a.png)

**Comment by rjaros** [comment]
Just clone the project from github and open in IntelliJ. It will be automatically imported and ready to work.
