### ISSUE TITLE
FeatureRequest: Generate UML diagrams

### ISSUE THREAD

**Issue by joerg-rade** [rjaros/kvision#95]
https://github.com/jgraph/

**Comment by rjaros** [comment]
This looks like a very complicated library. Writing a Kotlin wrapper would require in-depth knowledge of mxgraph API. I'm afraid I won't be able to take care of it, but of course anyone can contribute :-)

**Comment by joerg-rade** [comment]
I'll look for a less complex lib.

My goal is to have something that vizualizes that part of the model the user is currently operating on as UML state/object diagram.

Any suggestions?

**Comment by joerg-rade** [comment]
How about https://www.npmjs.com/package/node-plantuml ?

**Comment by rjaros** [comment]
This one looks like a nodejs library. It won't work in the browser.

**Comment by joerg-rade** [comment]
I'll go with calling a plantuml service, cf. http://plantuml.com/en/server
