### ISSUE TITLE
main.bundle.js missing in /Pokedex/build/resources/main

### ISSUE THREAD

**Issue by g3blv** [rjaros/kvision#96]
I might be running the build process incorrectly or I'm running the app from the wrong location.

**Steps**
Run `./gradlew build` in `/Pokedex/`
Open `index.html` from `/Pokedex/build/resources/main/` in a browser
Console output that `main.bundle.js` is missing from `/Pokedex/build/resources/main/`

Moving `main.bundle.js` to `/Pokedex/build/resources/main/` solves the issue.

Am I running the app from the wrong location?

**Comment by rjaros** [comment]
Thx for your feedback! :-)

First of all look at `README.md` file in the project directory. There are some basic tasks described in this file.
Use `./gradlew zip` to pack all required resources into a single zip file. Add `-Pprod=true` for production ready build.

For development you should use webpack dev server (`./gradlew -t run`). Hot-reload is configured out of the box. 
Also please read the guide: https://kvision.gitbook.io/kvision-guide/part-1-fundamentals/setting-up#development

**Comment by g3blv** [comment]
Thx. Sorry I should have checked the `README.md` and the guide. I'm considering using KVison for a small application. Before making the decision I'd like to ask some more general questions about KVision, like future plans etc. Where can I ask these questions?

**Comment by rjaros** [comment]
It's probably best to join Kotlin Slack #kvision channel.
