### ISSUE TITLE
DateTimeInput is obscured in Tabulator cells

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#97]
I think this might be a similar issue that was showing up for `SelectInput`, I noticed the `DateTimeInput` component gets obscured in Tabulator cells:
![image](https://user-images.githubusercontent.com/8540764/67736561-109d2e00-fa43-11e9-9a02-01df0a4b3bc9.png)

Not sure how it worked last time but perhaps we need a `SimpleDateTimeInput` component? Unless I didn't read the documentation deeply enough!

**Comment by rjaros** [comment]
There is a `DateTimeInput` control inside a tabulator cell used in the `Showcase` example (https://rjaros.github.io/kvision-examples/showcase/#!/tabulator). And it works just fine for me. Could you compare this to your app?

**Comment by robert-cronin** [comment]
I noticed on showcase, with small window sizes, the date input popup is also contained within the tabulator, not sure if this is just how much my setup is working:
![image](https://user-images.githubusercontent.com/8540764/67819575-b22e8900-faf0-11e9-86d6-d7c3b3d8e5fb.png)

**Comment by rjaros** [comment]
I'm afraid nothing can be done about this, because tabulator container has `overflow: auto` in CSS, and it can't be removed (I've tried this). If the scrollbars are not acceptable, you probably need to use built-in tabulator date-time editor.

**Comment by robert-cronin** [comment]
no problems, I will just use the inbuilt datetime selector

**Comment by robert-cronin** [comment]
I'm back to this issue, I'm still trying to figure out a way to make it show outside of the table bounds.
Here is an example I found online where a custom selector can show outside the boundaries (you just need to set the table height to something like 150px to see it)
https://jsfiddle.net/kcf1jes0/7/

**Comment by rjaros** [comment]
This date picker is a bit different (the popup is attached to the body element).
But I've found a way to workaround a problem with our picker based on this solution: https://github.com/Eonasdan/bootstrap-datetimepicker/issues/790#issuecomment-234652413
The fix will be available in 2.10.0

**Comment by robert-cronin** [comment]
awesome! thanks Robert
