### ISSUE TITLE
Handlebar templates within handlebar templates

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#99]
Is there a way of creating a html string with the inbuilt handlebar engine and then use that string as input to another handlebar template?
For example lets say I want to layout multiple tables in a template but I also want to generate those tables based on a row template. So like 5 rows for each table.
Here is what the templates would look like:
Top Template:
```
{{#tables}}
    {{{this}}}
{{/tables}}
```
Table Template:
```
<table>
    <thead>
    <tr>
        <th>Column 1</th>
        <th>Column 2</th>
    </tr>
    </thead>
    <tbody>
        {{{rows}}}
    </tbody>
</table>
```
Row Template:
```
<tr>
    <td>Col 1 value</td>
    <td>Col 2 value</td>
</tr>
```
My current issue is that in order to create the table html strings, I need to use a div like so:
```
div {
    template = require("table_template.hbs")
    templateData = obj {
        rows = arrayOf(...)
    }
}
```
But how do I then use this as a template into the Top Template?

**Comment by rjaros** [comment]
I'm not sure if this is what you are trying to get, but the `require` on `*.hbs` file returns a simple function `(Any) -> String `. You don't need to use KVision components at all. Just call the functions:
```
            val topTemplate = require("hbs/top.hbs")
            val tableTemplate = require("hbs/table.hbs")
            val rowTemplate = require("hbs/row.hbs")

            val resultRow = rowTemplate(obj {
                col1 = "COL1"
                col2 = "COL2"
            })
            val resultTable = tableTemplate(obj {
                rows = resultRow
            })
            val resultTop = topTemplate(obj {
                tables = resultTable
            })
            console.log(resultTop)

```

**Comment by robert-cronin** [comment]
Oh perfect, I wasn't aware we could use it in that way 👍
